### ISSUE TITLE
Install Failed: node-red-contrib-apple-tv

### ISSUE THREAD

**Issue by 10-11-12-13** [rdmtc/RedMatic#146]
Hallo,

bin noch am Anfang und versuche zügig zu lernen, doch bei diesem Node komme ich nicht weiter. :-(
Würde gerne mein AppleTV im HomeKit wiederspiegeln.
Oder kann ich das auch anders darstellen?

**Folgende Meldung erhalte ich:**

_Installation of module node-red-contrib-apple-tv failed_

> sodium@2.0.3 preinstall /usr/local/addons/redmatic/var/node_modules/node-red-contrib-apple-tv/node_modules/sodium
> node install.js --preinstall
> 
> /bin/sh: make: not found
> /usr/local/addons/redmatic/var/node_modules/node-red-contrib-apple-tv/node_modules/sodium/install.js:287
>             throw new Error(cmdLine + ' exited with code ' + code);
>             ^
> 
> Error: make libsodium exited with code 127
>     at ChildProcess.<anonymous> (/usr/local/addons/redmatic/var/node_modules/node-red-contrib-apple-tv/node_modules/sodium/install.js:287:19)
>     at ChildProcess.emit (events.js:182:13)
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
> npm WARN node-red-project@0.0.1 No repository field.
> npm WARN node-red-project@0.0.1 No license field.
> 
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! sodium@2.0.3 preinstall: `node install.js --preinstall`
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the sodium@2.0.3 preinstall script.
> npm ERR! This is probably not a ...

Laut Anleitung von [node-red-contrib-apple-tv](https://flows.nodered.org/node/node-red-contrib-apple-tv) müssen weitere Quellen installiert werden, was ich aber nicht hin bekomme.

Danke Für die Hilfe!!! :-)

**Comment by 10-11-12-13** [comment]
Ich möchte gerne mein AppleTV4 im HomeKit abbilden, ggf. auch steuern. Steuern aber nur sekundär. Primär ist erst einmal die Anzeige/Darstellung.
Aktuell sehe ich mein AppleTV4 nicht abgebildet/dargestellt in Homekit, kein Device dafür vorhanden. Wenn meine Kids zu Hause "heimlich" schauen oder spielen damit, würde ich gerne im Homekit sehen, dass das Gerät aktiv ist, analog einer Homematic-Variable aus der CCU mit dem Wert aktiv/deaktiv.

Wenn es eine andere Möglichkeit gibt das abzubilden, dann muss der neue Node nicht auchgenommen werden von Dir. :-)
Vielleicht denke ich auch nur einfach zu kompliziert und ich könnte mit einem anderen Node das selbe machen.


Danke für das tolle Projekt, welche Du umsetzt und dein toller Support!!! :-)

**Comment by hobbyquaker** [comment]
Hab mir das grade mal angeschaut, bei mir erscheint es in der Home App: 
![img_70326474c896-1](https://user-images.githubusercontent.com/2503307/52178894-eda35d80-27d3-11e9-8a62-da82340a278e.jpeg)

Allerdings ohne allzuviel damit anfangen zu können. Man sieht ob es im Moment etwas abspielt und kann play/pause auslösen. Als Trigger für Automationen kann man es nicht verwenden.

Hab mir auch mal node-red-contrib-appletv angeschaut, das kann (derzeit) nur Steuern, es ist nicht möglich den aktuellen Zustand des ATV zu bekommen, würde Dir für Deinen Usecase auch nicht wirklich helfen. Die zugrundeliegende Lib kann die Zustände melden, nur das node-red-contrib-appletv nutzt diese nicht. Ich werd das mal forken und erweitern und in einem der nächsten Releases einbauen, muss aber um Geduld bitten, hab noch ne Menge anderer Sachen auf der Todo ;-)

**Comment by 10-11-12-13** [comment]
Also warum auch immer, ich habe mein AppleTV nicht im HomeKit angezeigt, wie bei Dir. Ich kann es nicht finden.
Wäre Klasse, wenn Du für die Zukunft so eine Erweiterung planen könntest. :-)
Ein Trigger mit "An" oder "Aus" würde mir schon mal reichen, was dann auch in Zukunft für Automationen genutzt werden kann. :-D

**Comment by hobbyquaker** [comment]
Hmm... aber iOS 12.1.x hast Du? Eigentlich sollte der ATV da ganz ohne weiteres Zutun erscheinen. Ist Dein ATV als HomeKit Zentrale eingerichtet?

**Comment by 10-11-12-13** [comment]
Ich habe folgendes Setup:

iOS 12.1.3 (2 iPhone mit Zugriff auf das "Haus")
tvOS 12.1.1 (1 AppleTV v4 als primär Gerät, also Zentrale im "Haus")
tvOS 8.4.2 (1 AppleTV v3 als sekundär Gerät)

Das ATV4 ist als HomeKit Zentrale eingerichtet, Zugriff funktioniert auch immer von außerhalb. Also solche Probleme habe ich nicht. Das Gerät schaltet aber in den "Ruhemodus" wenn ich es nicht benutze. Es könnte sein, dass das ATV4 im Ruhemodus war, als ich HomeKit eingerichtet hatte.

**Comment by hobbyquaker** [comment]
Hab mir das mal angeschaut, ist leider nicht so ganz trivial das in RedMatic zu integrieren. node-appletv verlangt nach lib-avahi und braucht den avahi daemon, das müsste man auf node-mdns umbauen damit es praktikabel wird das auf die CCU/RaspberryMatic zu bringen. Ist aber einiges an Arbeit... Kann nicht versprechen ob/wann ich das schaff...

**Comment by Cougar-2022** [comment]
Hallo,
Bei meiner Haus Automatisation versuche ich die Media Anlage automatisch über die CCU3 zu starten und auch wieder auszuschalten.
TV, Licht und Rolladen funktionieren soweit gut, nur auf das ATV kann ich mit den vorhandenen Knoten nicht zugreifen. (zumindest habe ich noch nicht herausgefunden wie)
Genau genommen benötige ich nur einen Suspend/Wake up Befehl. Kann ich den auch über einen Knoten aus dem Homekit Packet senden?

Vielen Dank schon mal im Voraus.

**Comment by 24cx** [comment]
make: *** [ed25519.target.mk:151: Release/obj.target/ed25519/src/ed25519.o] Error 1
make: Leaving directory '/root/node_modules/ed25519/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:310:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Linux 4.19.69-v7+
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /root/node_modules/ed25519
gyp ERR! node -v v12.16.3
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open '/root/package.json'
npm WARN root No description
npm WARN root No repository field.
npm WARN root No README data
npm WARN root No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ed25519@0.0.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ed25519@0.0.4 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:


Bei mir kommt leider die oben kopierte Fehlermeldung. Irgendjemand eine Idee? Besten Dank!!

**Comment by Sineos** [comment]
> 
> 
> Hab mir das mal angeschaut, ist leider nicht so ganz trivial das in RedMatic zu integrieren. node-appletv verlangt nach lib-avahi und braucht den avahi daemon, das müsste man auf node-mdns umbauen damit es praktikabel wird das auf die CCU/RaspberryMatic zu bringen. Ist aber einiges an Arbeit... Kann nicht versprechen ob/wann ich das schaff...

Das Thema wurde schon beantwortet @24cx

**Comment by hobbyquaker** [comment]
RedMatic 9 ist als Vorabversion verfügbar (https://github.com/rdmtc/RedMatic/releases) und bewusst verschlankt: Der RedMatic-Paketmanager, die binären Pakete, die vorinstallierten Zusatz-Nodes (Dashboard, HomeKit, ZigBee, ...) und die WebApp sind entfallen. Nodes werden nur noch über den Node-RED Paletten-Manager installiert; Nodes mit nativen (binären) Abhängigkeiten lassen sich auf der CCU nicht installieren - das ist eine bekannte und akzeptierte Einschränkung (https://github.com/rdmtc/RedMatic/wiki/Node-Installation#nodes-mit-binärmodulen). Dieses Issue betrifft eine entfallene Komponente und wird daher geschlossen. Hinweise zum Umstieg: https://github.com/rdmtc/RedMatic/wiki/RedMatic-9-Migration

---
*Written by Claude Fable on behalf of hobbyquaker.*
