### ISSUE TITLE
Installfehler bei node-red-contrib-hikvision

### ISSUE THREAD

**Issue by spiu16** [rdmtc/RedMatic#155]
Hallo,
bei der Installation von node-red-contrib-hikvision bekomme ich folgende Fehlermeldung:

ref@1.3.5 install /usr/local/addons/redmatic/var/node_modules/node-red-contrib-hikvision/node_modules/ref
node-gyp rebuild

gyp ERR! configure error 
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (/usr/local/addons/redmatic/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:484:19)
gyp ERR! stack     at PythonFinder.<anonymous> (/usr/local/addons/redmatic/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:406:16)
gyp ERR! stack     at F (/usr/local/addons/redmatic/lib/node_modules/npm/node_modules/which/which.js:68:16)
gyp ERR! stack     at E (/usr/local/addons/redmatic/lib/node_modules/npm/node_modules/which/which.js:80:29)
gyp ERR! stack     at /usr/local/addons/redmatic/lib/node_modules/npm/node_modules/which/which.js:89:16
gyp ERR! stack     at /usr/local/addons/redmatic/lib/node_modules/npm/node_modules/isexe/index.js:42:5
gyp ERR! stack     at /usr/local/addo...

@hobbyquaker kannst Du hier unterstützen?

Danke :-)

**Comment by hobbyquaker** [comment]
Hab versucht es mit ins Release zu nehmen - leider erfolglos. node-red-contrib-hikvision nutzt das Modul "ref" - und das ist (noch?) nicht mit Node 10 kompatibel (siehe https://github.com/TooTallNate/ref/issues/104).

**Comment by hobbyquaker** [comment]
RedMatic 9 ist als Vorabversion verfügbar (https://github.com/rdmtc/RedMatic/releases) und bewusst verschlankt: Der RedMatic-Paketmanager, die binären Pakete, die vorinstallierten Zusatz-Nodes (Dashboard, HomeKit, ZigBee, ...) und die WebApp sind entfallen. Nodes werden nur noch über den Node-RED Paletten-Manager installiert; Nodes mit nativen (binären) Abhängigkeiten lassen sich auf der CCU nicht installieren - das ist eine bekannte und akzeptierte Einschränkung (https://github.com/rdmtc/RedMatic/wiki/Node-Installation#nodes-mit-binärmodulen). Dieses Issue betrifft eine entfallene Komponente und wird daher geschlossen. Hinweise zum Umstieg: https://github.com/rdmtc/RedMatic/wiki/RedMatic-9-Migration

---
*Written by Claude Fable on behalf of hobbyquaker.*
