### ISSUE TITLE
node-red-contrib-zigbee 0.7.2 

### ISSUE THREAD

**Issue by 18akallfass87** [rdmtc/RedMatic#222]
Ich bin seit kurzem stolzer Besitzer einer CCU3. 

Das einrichten hat bisher ganz gut funktioniert. 

Nun möchte ich noch zusätzlich meine Ikea Komponenten (trädfri) über einen zigbee usb Stick mc22531 direkt und ohne gateway mit der ccu3 ansprechen können. 

Nur leider habe ich beim installieren von 

node-red-contrib-zigbee 0.7.2 

Probleme, vielleicht können Sie mir da weiterhelfen. 

Vielen Dank vorab... 

```
2019-06-05T22:03:32.053Z installieren : node-red-contrib-zigbee 0.7.2
2019-06-05T22:03:25.701Z npm install --no-package-lock --global-style --no-audit --no-update-notifier --save --save-prefix="~" --production node-red-contrib-zigbee@0.7.2
2019-06-05T22:03:51.459Z [out] 
2019-06-05T22:03:51.459Z [out] > @serialport/bindings@2.0.8 install /usr/local/addons/redmatic/var/node_modules/node-red-contrib-zigbee/node_modules/@serialport/bindings
2019-06-05T22:03:51.459Z [out] > prebuild-install --tag-prefix @serialport/bindings@ || node-gyp rebuild
2019-06-05T22:03:51.459Z [out] 
2019-06-05T22:03:53.100Z [err] prebuild-install
2019-06-05T22:03:53.100Z [err]  WARN 
2019-06-05T22:03:53.100Z [err] install
2019-06-05T22:03:53.100Z [err]  No prebuilt binaries found (target=10.15.3 runtime=node arch=arm libc= platform=linux)
2019-06-05T22:03:53.836Z [err] gyp
2019-06-05T22:03:53.837Z [err]  
2019-06-05T22:03:53.837Z [err] ERR! configure error
2019-06-05T22:03:53.838Z [err]  
2019-06-05T22:03:53.839Z [err] gyp
2019-06-05T22:03:53.839Z [err]  ERR! stack
2019-06-05T22:03:53.839Z [err]  Error: Can't find Python executable "python", you can set the PYTHON env variable.
2019-06-05T22:03:53.839Z [err] gyp
2019-06-05T22:03:53.839Z [err]  ERR!
2019-06-05T22:03:53.839Z [err]  stack
2019-06-05T22:03:53.839Z [err]      at PythonFinder.failNoPython (/usr/local/addons/redmatic/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:484:19)
2019-06-05T22:03:53.840Z [err] gyp 
2019-06-05T22:03:53.840Z [err] ERR! 
2019-06-05T22:03:53.840Z [err] stack
2019-06-05T22:03:53.840Z [err]      at PythonFinder.<anonymous> (/usr/local/addons/redmatic/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:406:16)
2019-06-05T22:03:53.840Z [err] gyp
2019-06-05T22:03:53.840Z [err]  ERR!
2019-06-05T22:03:53.840Z [err]  stack
2019-06-05T22:03:53.840Z [err]      at F (/usr/local/addons/redmatic/lib/node_modules/npm/node_modules/which/which.js:68:16)
2019-06-05T22:03:53.840Z [err] gyp 
2019-06-05T22:03:53.840Z [err] ERR! 
2019-06-05T22:03:53.840Z [err] stack
2019-06-05T22:03:53.841Z [err]      at E (/usr/local/addons/redmatic/lib/node_modules/npm/node_modules/which/which.js:80:29)
2019-06-05T22:03:53.841Z [err] gyp
2019-06-05T22:03:53.841Z [err]  ERR!
2019-06-05T22:03:53.841Z [err]  stack
2019-06-05T22:03:53.841Z [err]      at /usr/local/addons/redmatic/lib/node_modules/npm/node_modules/which/which.js:89:16
2019-06-05T22:03:53.841Z [err] gyp
2019-06-05T22:03:53.841Z [err]  ERR!
2019-06-05T22:03:53.841Z [err]  
2019-06-05T22:03:53.841Z [err] stack     at /usr/local/addons/redmatic/lib/node_modules/npm/node_modules/isexe/index.js:42:5
2019-06-05T22:03:53.841Z [err] gyp 
2019-06-05T22:03:53.841Z [err] ERR!
2019-06-05T22:03:53.842Z [err]  stack
2019-06-05T22:03:53.842Z [err]      at /usr/local/addons/redmatic/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
2019-06-05T22:03:53.842Z [err] gyp
2019-06-05T22:03:53.842Z [err]  ERR!
2019-06-05T22:03:53.842Z [err]  stack
2019-06-05T22:03:53.842Z [err]      at FSReqWrap.oncomplete (fs.js:153:21)
2019-06-05T22:03:53.843Z [err] gyp
2019-06-05T22:03:53.843Z [err]  ERR! System
2019-06-05T22:03:53.843Z [err]  Linux 4.14.34
2019-06-05T22:03:53.844Z [err] gyp
2019-06-05T22:03:53.844Z [err]  ERR! 
2019-06-05T22:03:53.844Z [err] command
2019-06-05T22:03:53.844Z [err]  "/usr/local/addons/redmatic/bin/node" "/usr/local/addons/redmatic/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
2019-06-05T22:03:53.844Z [err] gyp
2019-06-05T22:03:53.844Z [err]  ERR!
2019-06-05T22:03:53.844Z [err]  
2019-06-05T22:03:53.844Z [err] cwd /usr/local/addons/redmatic/var/node_modules/node-red-contrib-zigbee/node_modules/@serialport/bindings
2019-06-05T22:03:53.845Z [err] gyp
2019-06-05T22:03:53.845Z [err]  
2019-06-05T22:03:53.845Z [err] ERR! 
2019-06-05T22:03:53.845Z [err] node -v v10.15.3
2019-06-05T22:03:53.845Z [err] gyp
2019-06-05T22:03:53.845Z [err]  ERR!
2019-06-05T22:03:53.845Z [err]  node-gyp -v
2019-06-05T22:03:53.845Z [err]  v3.8.0
2019-06-05T22:03:53.845Z [err] gyp
2019-06-05T22:03:53.845Z [err]  ERR!
2019-06-05T22:03:53.846Z [err]  not ok
2019-06-05T22:03:53.846Z [err]  
2019-06-05T22:03:55.803Z [err] npm
2019-06-05T22:03:55.803Z [err]  
2019-06-05T22:03:55.804Z [err] WARN
2019-06-05T22:03:55.804Z [err]  bl@0.7.0 requires a peer of stream-browserify@* but none is installed. You must install peer dependencies yourself.
2019-06-05T22:03:55.805Z [err] npm
2019-06-05T22:03:55.805Z [err]  
2019-06-05T22:03:55.805Z [err] WARN
2019-06-05T22:03:55.805Z [err]  node-red-project@0.0.1 No repository field.
2019-06-05T22:03:55.806Z [err] npm
2019-06-05T22:03:55.806Z [err]  
2019-06-05T22:03:55.806Z [err] WARN
2019-06-05T22:03:55.806Z [err]  node-red-project@0.0.1 No license field.
2019-06-05T22:03:55.807Z [err] 
2019-06-05T22:03:55.814Z [err] npm
2019-06-05T22:03:55.814Z [err]  
2019-06-05T22:03:55.814Z [err] ERR!
2019-06-05T22:03:55.815Z [err]  
2019-06-05T22:03:55.815Z [err] code
2019-06-05T22:03:55.815Z [err]  ELIFECYCLE
2019-06-05T22:03:55.816Z [err] npm
2019-06-05T22:03:55.816Z [err]  
2019-06-05T22:03:55.816Z [err] ERR!
2019-06-05T22:03:55.817Z [err]  
2019-06-05T22:03:55.817Z [err] errno
2019-06-05T22:03:55.817Z [err]  1
2019-06-05T22:03:55.818Z [err] npm
2019-06-05T22:03:55.818Z [err]  
2019-06-05T22:03:55.819Z [err] ERR!
2019-06-05T22:03:55.819Z [err]  @serialport/bindings@2.0.8 install: `prebuild-install --tag-prefix @serialport/bindings@ || node-gyp rebuild`
2019-06-05T22:03:55.819Z [err] npm
2019-06-05T22:03:55.819Z [err]  
2019-06-05T22:03:55.819Z [err] ERR!
2019-06-05T22:03:55.820Z [err]  Exit status 1
2019-06-05T22:03:55.820Z [err] npm
2019-06-05T22:03:55.821Z [err]  
2019-06-05T22:03:55.821Z [err] ERR!
2019-06-05T22:03:55.821Z [err]  
2019-06-05T22:03:55.821Z [err] npm
2019-06-05T22:03:55.822Z [err]  
2019-06-05T22:03:55.822Z [err] ERR!
2019-06-05T22:03:55.822Z [err]  Failed at the @serialport/bindings@2.0.8 install script.
2019-06-05T22:03:55.822Z [err] npm
2019-06-05T22:03:55.822Z [err]  
2019-06-05T22:03:55.823Z [err] ERR!
2019-06-05T22:03:55.823Z [err]  This is probably not a problem with npm. There is likely additional logging output above.
2019-06-05T22:03:56.294Z [err] 
2019-06-05T22:03:56.295Z [err] npm ERR! A complete log of this run can be found in:
2019-06-05T22:03:56.295Z [err] npm 
2019-06-05T22:03:56.295Z [err] ERR!     /usr/local/addons/redmatic/npm-cache/_logs/2019-06-05T22_03_55_877Z-debug.log
2019-06-05T22:03:56.336Z rc=1
```

**Comment by hobbyquaker** [comment]
@18akallfass87 Du musst das über das RedMatic eigene Paketmanagement installieren, siehe https://github.com/rdmtc/RedMatic/wiki/Node-Installation#nodes-mit-bin%C3%A4rmodulen

**Comment by Boarder** [comment]
Hi
Hast Du es hinbekommen?
Würde meine Zigbee Lampen auch gerne direkt anbinden.
Gib es dazu vielleicht auch eine Anleitung?
Vielen Dank

**Comment by 18akallfass87** [comment]
Hey komme zur Zeit leider nicht dazu... Melde mich dann. GrüsseVon meinem Huawei-Mobiltelefon gesendet-------- Originalnachricht --------Betreff: Re: [rdmtc/RedMatic] node-red-contrib-zigbee 0.7.2  (#222)Von: Boarder An: rdmtc/RedMatic Cc: 18akallfass87 ,Mention Hi

Hast Du es hinbekommen?

Würde meine Zigbee Lampen auch gerne direkt anbinden.

Gib es dazu vielleicht auch eine Anleitung?

Vielen Dank



—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.

[

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/rdmtc/RedMatic/issues/222?email_source=notifications\u0026email_token=AMIKB445T4U65QIRL47VUCTP2SVH7A5CNFSM4HYFU4R2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODXYTUOQ#issuecomment-502348346",

"url": "https://github.com/rdmtc/RedMatic/issues/222?email_source=notifications\u0026email_token=AMIKB445T4U65QIRL47VUCTP2SVH7A5CNFSM4HYFU4R2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODXYTUOQ#issuecomment-502348346",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]
