### ISSUE TITLE
Probleme beim installieren der node: node-red-contrib-doorbird

### ISSUE THREAD

**Issue by ThomasLoeffel** [rdmtc/RedMatic#239]
Hallo hobbyquaker,

ich versuche diese node zu installieren aber meine Redmatic steigt immer mit einem Fehler aus. Im ioboker geht es völlig problemlos. Vielleicht mache ich auch was falsch....

Danke Dir.
Gruß Thomas

Der Fehler im Log sag: 
`2019-07-20T00:19:37.091Z installieren : node-red-contrib-doorbird 0.2.6

2019-07-20T00:19:37.110Z npm install --no-package-lock --global-style --no-audit --no-update-notifier --save --save-prefix="~" --production node-red-contrib-doorbird@0.2.6
2019-07-20T00:19:43.706Z [out] 
2019-07-20T00:19:43.706Z [out] > argon2@0.24.0 install /usr/local/addons/redmatic/var/node_modules/node-red-contrib-doorbird/node_modules/argon2
2019-07-20T00:19:43.706Z [out] > node-gyp-build
2019-07-20T00:19:43.706Z [out] 
2019-07-20T00:19:44.508Z [err] gyp
2019-07-20T00:19:44.509Z [err]  
2019-07-20T00:19:44.509Z [err] ERR!
2019-07-20T00:19:44.509Z [err]  configure error
2019-07-20T00:19:44.509Z [err]  
2019-07-20T00:19:44.510Z [err] gyp
2019-07-20T00:19:44.510Z [err]  ERR!
2019-07-20T00:19:44.510Z [err]  stack
2019-07-20T00:19:44.510Z [err]  Error: Can't find Python executable "python", you can set the PYTHON env variable.
2019-07-20T00:19:44.510Z [err] gyp
2019-07-20T00:19:44.510Z [err]  
2019-07-20T00:19:44.510Z [err] ERR! 
2019-07-20T00:19:44.510Z [err] stack     at PythonFinder.failNoPython (/usr/local/addons/redmatic/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:484:19)
2019-07-20T00:19:44.510Z [err] gyp
2019-07-20T00:19:44.510Z [err]  ERR!
2019-07-20T00:19:44.510Z [err]  stack
2019-07-20T00:19:44.510Z [err]      at PythonFinder.<anonymous> (/usr/local/addons/redmatic/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:406:16)
2019-07-20T00:19:44.510Z [err] gyp
2019-07-20T00:19:44.510Z [err]  
2019-07-20T00:19:44.510Z [err] ERR! 
2019-07-20T00:19:44.510Z [err] stack     at F (/usr/local/addons/redmatic/lib/node_modules/npm/node_modules/which/which.js:68:16)
2019-07-20T00:19:44.511Z [err] gyp 
2019-07-20T00:19:44.511Z [err] ERR! 
2019-07-20T00:19:44.511Z [err] stack
2019-07-20T00:19:44.511Z [err]      at E (/usr/local/addons/redmatic/lib/node_modules/npm/node_modules/which/which.js:80:29)
2019-07-20T00:19:44.511Z [err] gyp
2019-07-20T00:19:44.511Z [err]  ERR!
2019-07-20T00:19:44.511Z [err]  stack
2019-07-20T00:19:44.511Z [err]      at /usr/local/addons/redmatic/lib/node_modules/npm/node_modules/which/which.js:89:16
2019-07-20T00:19:44.511Z [err] gyp 
2019-07-20T00:19:44.511Z [err] ERR! 
2019-07-20T00:19:44.511Z [err] stack
2019-07-20T00:19:44.511Z [err]      at /usr/local/addons/redmatic/lib/node_modules/npm/node_modules/isexe/index.js:42:5
2019-07-20T00:19:44.511Z [err] gyp
2019-07-20T00:19:44.511Z [err]  ERR!
2019-07-20T00:19:44.511Z [err]  stack
2019-07-20T00:19:44.511Z [err]      at /usr/local/addons/redmatic/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
2019-07-20T00:19:44.511Z [err] gyp 
2019-07-20T00:19:44.511Z [err] ERR! 
2019-07-20T00:19:44.511Z [err] stack
2019-07-20T00:19:44.511Z [err]      at FSReqWrap.oncomplete (fs.js:153:21)
2019-07-20T00:19:44.512Z [err] gyp
2019-07-20T00:19:44.512Z [err]  ERR!
2019-07-20T00:19:44.512Z [err]  System
2019-07-20T00:19:44.512Z [err]  Linux 4.19.58
2019-07-20T00:19:44.512Z [err] gyp
2019-07-20T00:19:44.512Z [err]  ERR!
2019-07-20T00:19:44.512Z [err]  command
2019-07-20T00:19:44.512Z [err]  "/usr/local/addons/redmatic/bin/node" "/usr/local/addons/redmatic/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
2019-07-20T00:19:44.513Z [err] gyp
2019-07-20T00:19:44.513Z [err]  ERR!
2019-07-20T00:19:44.513Z [err]  cwd
2019-07-20T00:19:44.513Z [err]  /usr/local/addons/redmatic/var/node_modules/node-red-contrib-doorbird/node_modules/argon2
2019-07-20T00:19:44.513Z [err] gyp
2019-07-20T00:19:44.513Z [err]  ERR!
2019-07-20T00:19:44.513Z [err]  
2019-07-20T00:19:44.513Z [err] node -v v10.15.3
2019-07-20T00:19:44.513Z [err] gyp
2019-07-20T00:19:44.513Z [err]  ERR!
2019-07-20T00:19:44.513Z [err]  
2019-07-20T00:19:44.513Z [err] node-gyp -v v3.8.0
2019-07-20T00:19:44.513Z [err] gyp
2019-07-20T00:19:44.513Z [err]  
2019-07-20T00:19:44.513Z [err] ERR! 
2019-07-20T00:19:44.513Z [err] not ok 
2019-07-20T00:19:44.942Z [err] npm
2019-07-20T00:19:44.943Z [err]  
2019-07-20T00:19:44.943Z [err] WARN
2019-07-20T00:19:44.943Z [err]  node-red-project@0.0.1 No repository field.
2019-07-20T00:19:44.943Z [err] npm
2019-07-20T00:19:44.944Z [err]  
2019-07-20T00:19:44.944Z [err] WARN
2019-07-20T00:19:44.944Z [err]  node-red-project@0.0.1 No license field.
2019-07-20T00:19:44.944Z [err] 
2019-07-20T00:19:44.948Z [err] npm
2019-07-20T00:19:44.948Z [err]  
2019-07-20T00:19:44.948Z [err] ERR!
2019-07-20T00:19:44.948Z [err]  
2019-07-20T00:19:44.949Z [err] code
2019-07-20T00:19:44.949Z [err]  ELIFECYCLE
2019-07-20T00:19:44.949Z [err] npm
2019-07-20T00:19:44.949Z [err]  
2019-07-20T00:19:44.949Z [err] ERR!
2019-07-20T00:19:44.950Z [err]  
2019-07-20T00:19:44.950Z [err] errno
2019-07-20T00:19:44.950Z [err]  1
2019-07-20T00:19:44.950Z [err] npm
2019-07-20T00:19:44.951Z [err]  
2019-07-20T00:19:44.951Z [err] ERR!
2019-07-20T00:19:44.951Z [err]  argon2@0.24.0 install: `node-gyp-build`
2019-07-20T00:19:44.951Z [err] npm
2019-07-20T00:19:44.951Z [err]  
2019-07-20T00:19:44.951Z [err] ERR!
2019-07-20T00:19:44.951Z [err]  Exit status 1
2019-07-20T00:19:44.952Z [err] npm
2019-07-20T00:19:44.952Z [err]  
2019-07-20T00:19:44.952Z [err] ERR!
2019-07-20T00:19:44.952Z [err]  
2019-07-20T00:19:44.952Z [err] npm
2019-07-20T00:19:44.953Z [err]  
2019-07-20T00:19:44.953Z [err] ERR!
2019-07-20T00:19:44.953Z [err]  Failed at the argon2@0.24.0 install script.
2019-07-20T00:19:44.953Z [err] npm
2019-07-20T00:19:44.953Z [err]  
2019-07-20T00:19:44.953Z [err] ERR!
2019-07-20T00:19:44.954Z [err]  This is probably not a problem with npm. There is likely additional logging output above.
2019-07-20T00:19:45.056Z [err] 
2019-07-20T00:19:45.057Z [err] npm
2019-07-20T00:19:45.057Z [err]  
2019-07-20T00:19:45.057Z [err] ERR!
2019-07-20T00:19:45.057Z [err]  A complete log of this run can be found in:
2019-07-20T00:19:45.057Z [err] npm
2019-07-20T00:19:45.057Z [err]  
2019-07-20T00:19:45.058Z [err] ERR!
2019-07-20T00:19:45.058Z [err]      /usr/local/addons/redmatic/npm-cache/_logs/2019-07-20T00_19_44_960Z-debug.log
2019-07-20T00:19:45.074Z rc=1`

**Comment by Sineos** [comment]
Diese node hat Abhängigkeiten welche kompiliert werden müssen. Das funktioniert auf einer CCU / RaspberryMatic nicht.

@hobbyquaker müsste diese als "extra node" Paket bereitstellen.

**Comment by ThomasLoeffel** [comment]
Hallo hobbyquaker,

verstehe. Danke für Deine Mühen! Hast Du noch eine alternative Idee zur Verwendung des "Doorbird-Systems"?

Gruß Thomas

**Comment by hobbyquaker** [comment]
Ich nehm node-red-contrib-doorbird mit dem nächsten Release mit auf, muss allerdings um Geduld bitten, im Juli wird das voraussichtlich nichts mehr, eher August/September.

**Comment by Diddlik** [comment]
Hallo, gibt es hier mittlerweile ein Update? 
Danke

**Comment by Sineos** [comment]
Ist doch schon implementiert. Siehe https://github.com/rdmtc/RedMatic/releases
In der RedMatic "Systemsteuerung", das Doorbird installieren und fertig. Siehe auch https://github.com/rdmtc/RedMatic/wiki/Node-Installation#installation-via-redmatic-package-manager

**Comment by Diddlik** [comment]
> 
> 
> Ist doch schon implementiert. Siehe https://github.com/rdmtc/RedMatic/releases
> In der RedMatic "Systemsteuerung", das Doorbird installieren und fertig. Siehe auch https://github.com/rdmtc/RedMatic/wiki/Node-Installation#installation-via-redmatic-package-manager

Super! Danke Dir, war erst nicht klar, dass es etwas anders installiert werden soll!
