### ISSUE TITLE
Node-RED exited with non-zero exit status 1

### ISSUE THREAD

**Issue by DamianosS** [rdmtc/RedMatic#274]
Hi, der Node-Red Prozess stoppt immer wieder in unbestimmten Zeitabständen.
Ich habe den email-node (node-red-node-email v 1.7.1) im Verdacht, allerdings funktioniert dieser (wenn der Prozess läuft) einwandfrei. 

Hier der Auszug aus dem Logfile [redmatic.2019-11-07T05_41_21.948Z.log](https://github.com/rdmtc/RedMatic/files/3818033/redmatic.2019-11-07T05_41_21.948Z.log) :
```
Nov  7 01:31:10 ccu3-webui daemon.err node-red: 7 Nov 01:31:10 - [red] Uncaught Exception:
Nov  7 01:31:10 ccu3-webui daemon.err node-red: 7 Nov 01:31:10 - AssertionError [ERR_ASSERTION]: Input A expected to strictly equal input B:
Nov  7 01:31:10 ccu3-webui daemon.err node-red: + expected - actual ... Lines skipped
Nov  7 01:31:10 ccu3-webui daemon.err node-red: - ShutdownWrap {
Nov  7 01:31:10 ccu3-webui daemon.err node-red: -   callback: [Function],
Nov  7 01:31:10 ccu3-webui daemon.err node-red: -   handle: TLSWrap {
Nov  7 01:31:10 ccu3-webui daemon.err node-red: -     [Symbol(owner)]: TLSSocket {
Nov  7 01:31:10 ccu3-webui daemon.err node-red: -       [Symbol(asyncId)]: 7129973,
Nov  7 01:31:10 ccu3-webui daemon.err node-red: -       [Symbol(connect-options)]: {
Nov  7 01:31:10 ccu3-webui daemon.err node-red: -         checkServerIdentity: [Function: checkServerIdentity],
Nov  7 01:31:10 ccu3-webui daemon.err node-red: -         ciphers: 'ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA256:ECDHE-RSA-AES256-SHA384:DHE-RSA-AES256-SHA384:ECDHE-RSA-AES256-SHA256:DHE-RSA-AES256-SHA256:HIGH:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!MD5:!PSK:!SRP:!CAMELLIA',
Nov  7 01:31:10 ccu3-webui daemon.err node-red: -         host: 'outlook.office365.com',
Nov  7 01:31:10 ccu3-webui daemon.err node-red: -         minDHSize: 1024,
Nov  7 01:31:10 ccu3-webui daemon.err node-red: -         rejectUnauthorized: false,
Nov  7 01:31:10 ccu3-webui daemon.err node-red: -         singleUse: true,
Nov  7 01:31:10 ccu3-webui daemon.err node-red: -         socket: Socket {
Nov  7 01:31:10 ccu3-webui daemon.err node-red: -           [Symbol(asyncId)]: 7129978,
Nov  7 01:31:10 ccu3-webui daemon.err node-red: -           [Symbol(kBytesRead)]: 0,
Nov  7 01:31:10 ccu3-webui daemon.err node-red: -           [Symbol(kBytesWritten)]: 0,
Nov  7 01:31:10 ccu3-webui daemon.err node-red: -           [Symbol(lastWriteQueueSize)]: 0,
Nov  7 01:31:10 ccu3-webui daemon.err node-red: -           [Symbol(timeout)]: null,
Nov  7 01:31:10 ccu3-webui daemon.err node-red: -           _events: [Object: null prototype] {
Nov  7 01:31:10 ccu3-webui daemon.err node-red: -             close: [
Nov  7 01:31:10 ccu3-webui daemon.err node-red: ...
Nov  7 01:31:10 ccu3-webui daemon.err node-red: + null
Nov  7 01:31:10 ccu3-webui daemon.err node-red: ...
Nov  7 01:31:10 ccu3-webui daemon.err node-red:     at JSStreamWrap.doWrite (internal/wrap_js_stream.js:151:12)
Nov  7 01:31:10 ccu3-webui daemon.err node-red:     at JSStream.onwrite (internal/wrap_js_stream.js:20:57)
Nov  7 01:31:10 ccu3-webui daemon.err node-red:     at Socket.ondata (internal/wrap_js_stream.js:64:22)
Nov  7 01:31:10 ccu3-webui daemon.err node-red:     at Socket.emit (events.js:198:13)
Nov  7 01:31:10 ccu3-webui daemon.err node-red:     at addChunk (_stream_readable.js:287:12)
Nov  7 01:31:10 ccu3-webui daemon.err node-red:     at readableAddChunk (_stream_readable.js:268:11)
Nov  7 01:31:10 ccu3-webui daemon.err node-red:     at Socket.Readable.push (_stream_readable.js:223:10)
Nov  7 01:31:10 ccu3-webui daemon.err node-red:     at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
Nov  7 01:31:10 ccu3-webui daemon.err node-red: Node-RED exited with non-zero exit status 1
```
Hier auch der Flow in dem der email-node verwendet wird [Email Flow.txt](https://github.com/rdmtc/RedMatic/files/3818056/Email.Flow.txt)

**Comment by DamianosS** [comment]
Gebt Bescheid, falls ich irgendwie beitragen kann, oder Infos fehlen!

**Comment by hobbyquaker** [comment]
Bin ich leider ratlos. Ich würde empfehlen mal hier ein Issue aufzumachen: https://github.com/node-red/node-red-nodes/issues

**Comment by DamianosS** [comment]
Danke, Sebastian. Mach ich!

**Comment by hobbyquaker** [comment]
https://github.com/node-red/node-red-nodes/issues/600

**Comment by DamianosS** [comment]
Hallo Stefan, eine Frage: 
Beim Eröffnen des Issues im node-red-nodes in Github sollte man ja folgende Informationen angeben:
•	 Node-RED version
•	 node.js version
•	 npm version
•	 Platform/OS

Da Redmatic ja ein „gekapseltes“ Node-RED ist, stehen  die aktuellen Versionsinformationen zu node.js und npm nicht zur Verfügung. Wo finde ich diese Infos? 
Bei Platform/OS ist die Angabe „Homematic“ für die internationale Node-RED Gemeinde wohl auch nicht so aussagekräftig, oder? Reicht da „Raspberry Pi“?

**Comment by Sineos** [comment]
Steht aller hier: https://github.com/rdmtc/RedMatic/releases

Bis auf die OS Version, das ist ein bisschen speziell da es ein "customized" Linux ist. Würd ich mal großzügig unterschlagen, bzw `Buildroot  2019.08.1` mit `Kernel 4.19.79` auf Raspberry Pi (Vorausgesetzt du hast das letzte RaspberryMatik System)

**Comment by PatrickM2201** [comment]
Hallo, 
heute ist bei meinem System Fehler aufgetreten, nur vermutlich verursacht von node-red-contrib-alexa-remote2.
Ich habe alle vorliegenden Informationen [https://github.com/node-red/node-red-nodes/issues/600](url) angefügt.

Viele Grüße
Patrick

**Comment by DamianosS** [comment]
Wie auch [hier](node-red/node-red-nodes#600) beschrieben, behelfe ich mir mit dem "Node-RED im Falle eines Absturzes neu starten" Feature um Downtimes so kurz wie möglich zu halten.

**Comment by hobbyquaker** [comment]
RedMatic 9 (Node.js 24, Node-RED 5, npm 11) ist als Vorabversion verfügbar: https://github.com/rdmtc/RedMatic/releases - dieses Issue betrifft den alten Node.js-14-Stack und wird geschlossen. Falls das Problem mit RedMatic 9 weiterhin auftritt, bitte ein neues Issue mit Log eröffnen. Hinweise zum Umstieg: https://github.com/rdmtc/RedMatic/wiki/RedMatic-9-Migration

---
*Written by Claude Fable on behalf of hobbyquaker.*
