### ISSUE TITLE
Add prebuild node-red-contrib-comfoair

### ISSUE THREAD

**Issue by tomSmartHome** [rdmtc/RedMatic#290]
Hi,

I'm a Redmatic newbie, running on CCU3. I'm trying to install node-red-contrib-comfoair and it fails with:

```
# source /usr/local/addons/redmatic/home/.profile
# cd /usr/local/addons/redmatic/var
# npm install --save --no-package-lock --global-style --save-prefix="~" --production node-red-contrib-comfoair

@serialport/bindings@2.0.8 install /usr/local/addons/redmatic/var/node_modules/node-red-contrib-comfoair/node_modules/@serialport/bindings
prebuild-install --tag-prefix @serialport/bindings@ || node-gyp rebuild

prebuild-install WARN install No prebuilt binaries found (target=10.17.0 runtime=node arch=arm libc= platform=linux)
gyp ERR! find Python
gyp ERR! find Python Python is not set from command line or npm configuration
gyp ERR! find Python Python is not set from environment variable PYTHON
gyp ERR! find Python checking if "python" can be used
gyp ERR! find Python - "python" is not in PATH or produced an error
gyp ERR! find Python checking if "python2" can be used
gyp ERR! find Python - "python2" is not in PATH or produced an error
gyp ERR! find Python checking if "python3" can be used
gyp ERR! find Python - "python3" is not in PATH or produced an error
gyp ERR! find Python
gyp ERR! find Python **********************************************************
gyp ERR! find Python You need to install the latest version of Python.
gyp ERR! find Python Node-gyp should be able to find and use Python. If not,
gyp ERR! find Python you can try one of the following options:
gyp ERR! find Python - Use the switch --python="/path/to/pythonexecutable"
gyp ERR! find Python   (accepted by both node-gyp and npm)
gyp ERR! find Python - Set the environment variable PYTHON
gyp ERR! find Python - Set the npm configuration variable python:
gyp ERR! find Python   npm config set python "/path/to/pythonexecutable"
gyp ERR! find Python For more information consult the documentation at:
gyp ERR! find Python https://github.com/nodejs/node-gyp#installation
gyp ERR! find Python **********************************************************
gyp ERR! find Python
gyp ERR! configure error
gyp ERR! stack Error: Could not find any Python installation to use
gyp ERR! stack     at PythonFinder.fail (/usr/local/addons/redmatic/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:307:47)
gyp ERR! stack     at PythonFinder.runChecks (/usr/local/addons/redmatic/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:136:21)
gyp ERR! stack     at PythonFinder.<anonymous> (/usr/local/addons/redmatic/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:179:16)
gyp ERR! stack     at PythonFinder.execFileCallback (/usr/local/addons/redmatic/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:271:16)
gyp ERR! stack     at exithandler (child_process.js:301:5)
gyp ERR! stack     at ChildProcess.errorhandler (child_process.js:313:5)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:246:12)
gyp ERR! stack     at onErrorNT (internal/child_process.js:415:16)
gyp ERR! stack     at process._tickCallback (internal/process/next_tick.js:63:19)
gyp ERR! System Linux 4.14.34
gyp ERR! command "/usr/local/addons/redmatic/bin/node" "/usr/local/addons/redmatic/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/addons/redmatic/var/node_modules/node-red-contrib-comfoair/node_modules/@serialport/bindings
gyp ERR! node -v v10.17.0
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok
npm WARN node-red-project@0.0.1 No repository field.
npm WARN node-red-project@0.0.1 No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @serialport/bindings@2.0.8 install: prebuild-install --tag-prefix @serialport/bindings@ || node-gyp rebuild
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @serialport/bindings@2.0.8 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /usr/local/addons/redmatic/npm-cache/_logs/2019-12-11T20_52_29_445Z-debug.log
```

**Comment by hobbyquaker** [comment]
See https://github.com/rdmtc/RedMatic/wiki/Node-Installation#nodes-mit-bin%C3%A4rmodulen
Will include these Nodes in the next release.

**Comment by tomSmartHome** [comment]
Thanks a lot for a quick response. I realized that it’s probably required, but wasn’t sure if you just add “anything people come across”. 

Isn’t there some work around worth documenting to save you all that extra work?

**Comment by hobbyquaker** [comment]
With RedMatic 5.2.5 you should be able to install node-red-contrib-comfoair via the RedMatic Package Manager (https://github.com/rdmtc/RedMatic/wiki/Node-Installation#installation-via-redmatic-package-manager)

**Comment by tomSmartHome** [comment]
Worked great - thanks! 
And if I need to upgrade the version? e.g. https://github.com/coolchip/node-red-contrib-comfoair/releases/tag/v0.0.4

**Comment by hobbyquaker** [comment]
I will always include the current version in RedMatic when building a new release, so 0.0.4 (or higher) will for sure be included in the next RedMatic release.
