### ISSUE TITLE
UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by Matten-Matten** [rdmtc/RedMatic#293]
Habe folgendes im Log:

```
Dec 20 19:03:03 ccu3-webui daemon.err node-red: ungÃ¼ltig
Dec 20 19:03:03 ccu3-webui daemon.err node-red: undefined
Dec 20 19:03:03 ccu3-webui daemon.err node-red: Leerlauf
Dec 20 19:03:03 ccu3-webui daemon.err node-red: Grundriss Ortsbestimmung fehlgeschlagen
Dec 20 19:04:02 ccu3-webui daemon.err node-red: ungÃ¼ltig
Dec 20 19:04:02 ccu3-webui daemon.err node-red: undefined
Dec 20 19:04:02 ccu3-webui daemon.err node-red: Leerlauf
Dec 20 19:04:02 ccu3-webui daemon.err node-red: Grundriss Ortsbestimmung fehlgeschlagen
Dec 20 19:04:31 ccu3-webui local0.err ReGaHss: ERROR: Content-Length or Postback Param size incorrect! contLen=111 postLen=1 PostParam=& [HandleTextPost():httpServer.cpp:1415]
Dec 20 19:05:01 ccu3-webui daemon.err node-red: ungÃ¼ltig
Dec 20 19:05:01 ccu3-webui daemon.err node-red: undefined
Dec 20 19:05:01 ccu3-webui daemon.err node-red: Leerlauf
Dec 20 19:05:01 ccu3-webui daemon.err node-red: Grundriss Ortsbestimmung fehlgeschlagen
Dec 20 19:06:01 ccu3-webui daemon.err node-red: ungÃ¼ltig
Dec 20 19:06:01 ccu3-webui daemon.err node-red: undefined
Dec 20 19:06:01 ccu3-webui daemon.err node-red: Leerlauf
Dec 20 19:06:01 ccu3-webui daemon.err node-red: Grundriss Ortsbestimmung fehlgeschlagen
Dec 20 19:06:34 ccu3-webui local0.err ReGaHss: ERROR: Content-Length or Postback Param size incorrect! contLen=111 postLen=1 PostParam=& [HandleTextPost():httpServer.cpp:1415]
Dec 20 19:07:01 ccu3-webui daemon.err node-red: ungÃ¼ltig
Dec 20 19:07:01 ccu3-webui daemon.err node-red: undefined
Dec 20 19:07:01 ccu3-webui daemon.err node-red: Leerlauf
Dec 20 19:07:01 ccu3-webui daemon.err node-red: Grundriss Ortsbestimmung fehlgeschlagen
Dec 20 19:07:01 ccu3-webui local0.err ReGaHss: ERROR: Content-Length or Postback Param size incorrect! contLen=111 postLen=1 PostParam=& [HandleTextPost():httpServer.cpp:1415]
```

Ist das ignorierbar?

Gruß Matten Matten

**Comment by hobbyquaker** [comment]
welche Nodes das hier verursachen 
```
Dec 20 19:07:01 ccu3-webui daemon.err node-red: ungÃ¼ltig
Dec 20 19:07:01 ccu3-webui daemon.err node-red: undefined
Dec 20 19:07:01 ccu3-webui daemon.err node-red: Leerlauf
Dec 20 19:07:01 ccu3-webui daemon.err node-red: Grundriss Ortsbestimmung fehlgeschlagen
```
weiss ich nicht, sie nutzen für Ihre Debug Ausgabe wohl ein `console.log()` statt dem Node-RED Logging Mechanismus (der uns sagen würde welche Nodes die Meldung generiert haben). Ob die Meldung "safe to ignore" ist weiss ich nicht.


Das hier:
```
Dec 20 19:07:01 ccu3-webui local0.err ReGaHss: ERROR: Content-Length or Postback Param size incorrect! contLen=111 postLen=1 PostParam=& [HandleTextPost():httpServer.cpp:1415]
```
ist auf jeden Fall ein Bug. Hier geht irgendwas bei der Kommunikation mit der CCU (genauer: mit der Rega) schief. Allerdings weiss ich nicht ob das von RedMatic versursacht wird, dazu müsstest mal das Logging auf Debug Level setzen (https://github.com/rdmtc/RedMatic/wiki/Loglevel) damit man ein paar Zeilen vor und nach der Fehlermeldung sieht und wir rausfinden ob es durch RedMatic verursacht wird.

**Comment by Matten-Matten** [comment]
```
Dec 21 10:26:20 ccu3-webui daemon.debug node-red[2742]: [ccu-connection:192.168.27.42] rpcCheckInit CUxD 13 60
Dec 21 10:26:21 ccu3-webui local0.err ReGaHss: ERROR: Content-Length or Postback Param size incorrect! contLen=111 postLen=1 PostParam=& [HandleTextPost():httpServer.cpp:1415]
Dec 21 10:26:22 ccu3-webui daemon.debug node-red[2742]: [ccu-connection:192.168.27.42] rpc < binrpc system.multicall [[{"methodName":"event","params":["nr_AKHydZ_BidCos-RF","CENTRAL","PONG","hm-rpc.0"]}]]
Dec 21 10:26:22 ccu3-webui daemon.debug node-red[2742]: [ccu-connection:192.168.27.42]     < BidCos-RF PONG hm-rpc.0
```

**Comment by Matten-Matten** [comment]
auch das Kommt am anfang wenn ich Redmatic starte:

```
Dec 21 10:35:50 ccu3-webui daemon.err node-red: 2019-12-21T09:35:50.109Z zigbee-herdsman:adapter:zStack:startZnp Item 'hasConfigured' is valid
Dec 21 10:35:55 ccu3-webui daemon.err node-red[7383]: [ccu-connection:192.168.27.42]     < BidCos-RF init Error: response timeout
Dec 21 10:35:55 ccu3-webui daemon.err node-red[7383]: [ccu-connection:192.168.27.42] init BidCos-RF Error: response timeout
Dec 21 10:35:55 ccu3-webui daemon.err node-red: 2019-12-21T09:35:55.872Z zigbee-herdsman:adapter:zStack:startZnp Item 'hasConfigured' is valid
Dec 21 10:35:56 ccu3-webui daemon.err node-red: 2019-12-21T09:35:56.074Z zigbee-herdsman:adapter:zStack:startZnp Item 'channelList' is valid
Dec 21 10:35:56 ccu3-webui daemon.err node-red: 2019-12-21T09:35:56.363Z zigbee-herdsman:adapter:zStack:startZnp Item 'networkKeyDistribute' is valid
Dec 21 10:35:56 ccu3-webui daemon.err node-red: 2019-12-21T09:35:56.433Z zigbee-herdsman:adapter:zStack:startZnp Item 'networkKey' is valid
Dec 21 10:35:56 ccu3-webui daemon.err node-red: 2019-12-21T09:35:56.456Z zigbee-herdsman:adapter:zStack:startZnp Item 'panID' is valid
Dec 21 10:35:56 ccu3-webui daemon.err node-red: 2019-12-21T09:35:56.472Z zigbee-herdsman:adapter:zStack:startZnp Item 'extendedPanID' is valid
Dec 21 10:35:56 ccu3-webui daemon.err node-red: 2019-12-21T09:35:56.483Z zigbee-herdsman:adapter:zStack:startZnp ZNP is already started as coordinator
Dec 21 10:35:56 ccu3-webui daemon.err node-red: 2019-12-21T09:35:56.498Z zigbee-herdsman:adapter:zStack:startZnp Endpoint '1' already registered
Dec 21 10:35:56 ccu3-webui daemon.err node-red: 2019-12-21T09:35:56.498Z zigbee-herdsman:adapter:zStack:startZnp Endpoint '2' already registered
Dec 21 10:35:56 ccu3-webui daemon.err node-red: 2019-12-21T09:35:56.499Z zigbee-herdsman:adapter:zStack:startZnp Endpoint '3' already registered
Dec 21 10:35:56 ccu3-webui daemon.err node-red: 2019-12-21T09:35:56.499Z zigbee-herdsman:adapter:zStack:startZnp Endpoint '4' already registered
Dec 21 10:35:56 ccu3-webui daemon.err node-red: 2019-12-21T09:35:56.500Z zigbee-herdsman:adapter:zStack:startZnp Endpoint '5' already registered
Dec 21 10:35:56 ccu3-webui daemon.err node-red: 2019-12-21T09:35:56.500Z zigbee-herdsman:adapter:zStack:startZnp Endpoint '6' already registered
Dec 21 10:35:56 ccu3-webui daemon.err node-red: 2019-12-21T09:35:56.500Z zigbee-herdsman:adapter:zStack:startZnp Endpoint '8' already registered
Dec 21 10:35:56 ccu3-webui daemon.err node-red: 2019-12-21T09:35:56.501Z zigbee-herdsman:adapter:zStack:startZnp Endpoint '11' already registered
Dec 21 10:35:56 ccu3-webui daemon.err node-red: 2019-12-21T09:35:56.501Z zigbee-herdsman:adapter:zStack:startZnp Endpoint '110' already registered
Dec 21 10:35:56 ccu3-webui daemon.err node-red: 2019-12-21T09:35:56.501Z zigbee-herdsman:adapter:zStack:startZnp Endpoint '12' already registered
```

**Comment by hobbyquaker** [comment]
Ich bin relativ sicher dass das `Dec 21 10:29:00 ccu3-webui local0.err ReGaHss: ERROR: Content-Length or Postback Param size incorrect! contLen=111 postLen=1 PostParam=& [HandleTextPost():httpServer.cpp:1415]` nicht von RedMatic verursacht wird. Scheint irgendetwas zu sein was ein GET Request auf der Rega Schnittstelle macht, das tut node-red-contrib-ccu nicht. Vielleicht eine App wie Pocket Control oder Home24 oder so? Falls Du sowas benutzt könntest es mal zum eingrenzen des Fehlers deaktivieren und schauen ob der Fehler dann weg ist.

Die Zigbee Meldungen kannst ignorieren.

**Comment by Matten-Matten** [comment]
Ok vielen dank für Die Fehleranalyse. Ich vermute ja auch ioBroker. Ich teste das mal. Willst du trotzden Rückmeldung haben wenn ich es gefunden habe?

**Comment by Matten-Matten** [comment]
leider hatte ich heute morgen auch noch folgendes im Log:

```
Dec 22 08:41:31 ccu3-webui daemon.err node-red: (node:7383) UnhandledPromiseRejectionWarning: Error: overwritten
Dec 22 08:41:31 ccu3-webui daemon.err node-red:     at Promise (/usr/local/addons/redmatic/var/node_modules/node-red-contrib-ccu/nodes/ccu-connection.js:2766:55)
Dec 22 08:41:31 ccu3-webui daemon.err node-red:     at new Promise (<anonymous>)
Dec 22 08:41:31 ccu3-webui daemon.err node-red:     at CcuConnectionNode.setValue (/usr/local/addons/redmatic/var/node_modules/node-red-contrib-ccu/nodes/ccu-connection.js:2756:20)
Dec 22 08:41:31 ccu3-webui daemon.err node-red:     at CcuValue.on [as _inputCallback] (/usr/local/addons/redmatic/var/node_modules/node-red-contrib-ccu/nodes/ccu-value.js:98:73)
Dec 22 08:41:31 ccu3-webui daemon.err node-red:     at CcuValue.Node._emitInput (/usr/local/addons/redmatic/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/nodes/Node.js:199:18)
Dec 22 08:41:31 ccu3-webui daemon.err node-red:     at Immediate.<anonymous> (/usr/local/addons/redmatic/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/nodes/Node.js:179:33)
Dec 22 08:41:31 ccu3-webui daemon.err node-red:     at runCallback (timers.js:705:18)
Dec 22 08:41:31 ccu3-webui daemon.err node-red:     at tryOnImmediate (timers.js:676:5)
Dec 22 08:41:31 ccu3-webui daemon.err node-red:     at processImmediate (timers.js:658:5)
Dec 22 08:41:31 ccu3-webui daemon.err node-red: (node:7383) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 6)
```

**Comment by Matten-Matten** [comment]
und das kommt offt:

`Dec 22 10:18:40 ccu3-webui daemon.warn node-red[1882]: [ccu-connection:192.168.27.42] ping timeout HmIP-RF 745`

**Comment by Matten-Matten** [comment]
ich hab jegliche anbindung (Tablets & Smartphones) ausgeschaltet und trotzdem der Logeintrag...

`Dec 22 10:58:12 ccu3-webui local0.err ReGaHss: ERROR: Content-Length or Postback Param size incorrect! contLen=111 postLen=1 PostParam=& [HandleTextPost():httpServer.cpp:1415]`. 
Ich werde Jens Maus mal im Forum anschreiben. Vielleicht hat der eine Idee wo das herkommt...

**Comment by hobbyquaker** [comment]
Ich mach hier nochmal auf, das
`Dec 22 08:41:31 ccu3-webui daemon.err node-red: (node:7383) UnhandledPromiseRejectionWarning: Error: overwritten` scheint ein Bug in node-red-contrib-ccu zu sein den ich noch untersuchen muss.

**Comment by Matten-Matten** [comment]
OK, kann ich dir da irgendwie behilflich sein?

Gruß
Matten Matten

**Comment by hobbyquaker** [comment]
Ist doch kein Bug... :-)
Diese Fehlermeldung tritt dann auf wenn Du sehr schnell sehr viele Nachrichten schickst und ein Datenpunkt setzt von dem noch ein anderer Wert in der Queue wartet, dann wird der vorherige Wert überschrieben. Muss das mal abfangen und darauf eine Warning statt einen Error machen. Würde dennoch mal schauen welcher Flow da so schnell hintereinander Werte setzt, vll. kannst das noch wegoptimieren, wenn nicht sollte es aber auch kein Problem sein.

**Comment by Matten-Matten** [comment]
OK ich schaue ob ich ein limiter irgendwo vergessen hab. Eigentlich schaue ich immer das nicht alt so viel Nachrichten hintereinander an meine Systemvariablen übergebe.
