### ISSUE TITLE
Installations-Fehler: node-red-contrib-chatbot

### ISSUE THREAD

**Issue by DenisMtfl** [rdmtc/RedMatic#308]
Can't install **node-red-contrib-chatbot** (RedMatic 1.03 on RaspiMatic 3.49.17.20191225)

**Log:**
npm WARN deprecated @types/form-data@2.5.0: This is a stub types definition. form-data provides its own type definitions, so you do not need this installed.
npm WARN deprecated @types/p-retry@3.0.1: This is a stub types definition. p-retry provides its own type definitions, so you do not need this installed.
npm WARN deprecated @types/p-cancelable@1.0.1: This is a stub types definition. p-cancelable provides its own type definitions, so you do not need this installed.
npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
npm WARN deprecated superagent@2.3.0: Please note that v5.0.1+ of superagent removes User-Agent header by default, therefore you may need to add it yourself (e.g. GitHub blocks requests without a User-Agent header).  This notice will go away with v5.0.2+ once it is released.
npm WARN deprecated socks@1.1.10: If using 2.x bran...

**Comment by Sineos** [comment]
Your log only shows warnings, which usually are harmless. If the installation has failed the log would show ERROR.

The node uses fsevent which typically would need gyp for compilation. In this case the node would have to be provided precompiled by @hobbyquaker. 

Is this the entire log?

**Comment by wernersv** [comment]
It looks as I have the same problem installing node-red-contrib-chatbot v0.18.13

Here is my log output of the installation.
`
-----------------------------------------------------------
2020-03-02T18:06:14.008Z installieren : node-red-contrib-chatbot 0.18.13

2020-03-02T18:06:14.246Z npm install --no-package-lock --global-style --no-audit --no-update-notifier --save --save-prefix="~" --production node-red-contrib-chatbot@0.18.13
2020-03-02T18:06:33.735Z [err] npm
2020-03-02T18:06:33.736Z [err]  WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
2020-03-02T18:06:34.490Z [err] npm
2020-03-02T18:06:34.491Z [err]  WARN deprecated @types/form-data@2.5.0: This is a stub types definition. form-data provides its own type definitions, so you do not need this installed.
2020-03-02T18:06:34.515Z [err] npm
2020-03-02T18:06:34.515Z [err]  WARN deprecated @types/p-retry@3.0.1: This is a stub types definition. p-retry provides its own type definitions, so you do not need this installed.
2020-03-02T18:06:34.526Z [err] npm
2020-03-02T18:06:34.527Z [err]  WARN deprecated @types/p-cancelable@1.0.1: This is a stub types definition. p-cancelable provides its own type definitions, so you do not need this installed.
2020-03-02T18:08:01.064Z [err] npm
2020-03-02T18:08:01.065Z [err]  WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
2020-03-02T18:08:15.634Z [err] npm
2020-03-02T18:08:15.635Z [err]  WARN deprecated socks@1.1.10: If using 2.x branch, please upgrade to at least 2.1.6 to avoid a serious bug with socket data flow and an import issue introduced in 2.1.0

-----------------------------------------------------------
2020-03-02T18:08:19.907Z installieren : node-red-contrib-chatbot 0.18.13

2020-03-02T18:10:32.110Z [out] 
2020-03-02T18:10:32.110Z [out] > grpc@1.24.2 install /usr/local/addons/redmatic/var/node_modules/node-red-contrib-chatbot/node_modules/grpc
2020-03-02T18:10:32.110Z [out] > node-pre-gyp install --fallback-to-build --library=static_library
2020-03-02T18:10:32.110Z [out] 
2020-03-02T18:10:33.857Z [err] node-pre-gyp
2020-03-02T18:10:33.859Z [err]  
2020-03-02T18:10:33.859Z [err] WARN Using request for node-pre-gyp https download
2020-03-02T18:10:33.860Z [err]  
2020-03-02T18:10:34.447Z [err] node-pre-gyp
2020-03-02T18:10:34.448Z [err]  WARN Tried to download(404): https://node-precompiled-binaries.grpc.io/grpc/v1.24.2/node-v64-linux-arm-unknown.tar.gz 
2020-03-02T18:10:34.448Z [err] node-pre-gyp
2020-03-02T18:10:34.448Z [err]  WARN Pre-built binaries not found for grpc@1.24.2 and node@10.19.0 (node-v64 ABI, unknown) (falling back to source compile with node-gyp) 
2020-03-02T18:10:37.677Z [err] gyp
2020-03-02T18:10:37.679Z [err]  
2020-03-02T18:10:37.679Z [err] ERR! find Python 
2020-03-02T18:10:37.679Z [err] gyp ERR!
2020-03-02T18:10:37.679Z [err]  find Python
2020-03-02T18:10:37.680Z [err]  Python is not set from command line or npm configuration
2020-03-02T18:10:37.680Z [err] gyp
2020-03-02T18:10:37.680Z [err]  ERR!
2020-03-02T18:10:37.680Z [err]  find Python Python is not set from environment variable PYTHON
2020-03-02T18:10:37.680Z [err] gyp 
2020-03-02T18:10:37.680Z [err] ERR! find Python
2020-03-02T18:10:37.680Z [err]  checking if "python" can be used
2020-03-02T18:10:37.680Z [err] gyp
2020-03-02T18:10:37.681Z [err]  ERR!
2020-03-02T18:10:37.681Z [err]  find Python - "python" is not in PATH or produced an error
2020-03-02T18:10:37.681Z [err] gyp 
2020-03-02T18:10:37.681Z [err] ERR! 
2020-03-02T18:10:37.681Z [err] find Python checking if "python2" can be used
2020-03-02T18:10:37.681Z [err] gyp 
2020-03-02T18:10:37.681Z [err] ERR! find Python
2020-03-02T18:10:37.681Z [err]  - "python2" is not in PATH or produced an error
2020-03-02T18:10:37.681Z [err] gyp
2020-03-02T18:10:37.682Z [err]  ERR! 
2020-03-02T18:10:37.682Z [err] find Python checking if "python3" can be used
2020-03-02T18:10:37.682Z [err] gyp 
2020-03-02T18:10:37.682Z [err] ERR! 
2020-03-02T18:10:37.682Z [err] find Python - "python3" is not in PATH or produced an error
2020-03-02T18:10:37.682Z [err] gyp ERR!
2020-03-02T18:10:37.682Z [err]  find Python
2020-03-02T18:10:37.683Z [err]  
2020-03-02T18:10:37.683Z [err] gyp
2020-03-02T18:10:37.683Z [err]  ERR! 
2020-03-02T18:10:37.683Z [err] find Python **********************************************************
2020-03-02T18:10:37.683Z [err] gyp 
2020-03-02T18:10:37.683Z [err] ERR! find Python
2020-03-02T18:10:37.683Z [err]  You need to install the latest version of Python.
2020-03-02T18:10:37.683Z [err] gyp
2020-03-02T18:10:37.683Z [err]  ERR! 
2020-03-02T18:10:37.684Z [err] find Python Node-gyp should be able to find and use Python. If not,
2020-03-02T18:10:37.684Z [err] gyp 
2020-03-02T18:10:37.684Z [err] ERR! 
2020-03-02T18:10:37.684Z [err] find Python you can try one of the following options:
2020-03-02T18:10:37.684Z [err] gyp 
2020-03-02T18:10:37.684Z [err] ERR! find Python
2020-03-02T18:10:37.685Z [err]  - Use the switch --python="/path/to/pythonexecutable"
2020-03-02T18:10:37.685Z [err] gyp 
2020-03-02T18:10:37.685Z [err] ERR! 
2020-03-02T18:10:37.685Z [err] find Python   (accepted by both node-gyp and npm)
2020-03-02T18:10:37.685Z [err] gyp
2020-03-02T18:10:37.685Z [err]  ERR!
2020-03-02T18:10:37.685Z [err]  find Python - Set the environment variable PYTHON
2020-03-02T18:10:37.685Z [err] gyp 
2020-03-02T18:10:37.685Z [err] ERR! 
2020-03-02T18:10:37.686Z [err] find Python - Set the npm configuration variable python:
2020-03-02T18:10:37.686Z [err] gyp 
2020-03-02T18:10:37.686Z [err] ERR! 
2020-03-02T18:10:37.686Z [err] find Python   npm config set python "/path/to/pythonexecutable"
2020-03-02T18:10:37.686Z [err] gyp ERR!
2020-03-02T18:10:37.686Z [err]  find Python
2020-03-02T18:10:37.686Z [err]  For more information consult the documentation at:
2020-03-02T18:10:37.686Z [err] gyp
2020-03-02T18:10:37.686Z [err]  ERR!
2020-03-02T18:10:37.687Z [err]  find Python https://github.com/nodejs/node-gyp#installation
2020-03-02T18:10:37.687Z [err] gyp 
2020-03-02T18:10:37.687Z [err] ERR! 
2020-03-02T18:10:37.687Z [err] find Python **********************************************************
2020-03-02T18:10:37.687Z [err] gyp ERR!
2020-03-02T18:10:37.687Z [err]  find Python
2020-03-02T18:10:37.687Z [err]  
2020-03-02T18:10:37.693Z [err] gyp
2020-03-02T18:10:37.693Z [err]  ERR! configure error 
2020-03-02T18:10:37.695Z [err] gyp
2020-03-02T18:10:37.695Z [err]  ERR! stack Error: Could not find any Python installation to use
2020-03-02T18:10:37.695Z [err] gyp
2020-03-02T18:10:37.695Z [err]  ERR! 
2020-03-02T18:10:37.695Z [err] stack     at PythonFinder.fail (/usr/local/addons/redmatic/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:307:47)
2020-03-02T18:10:37.695Z [err] gyp
2020-03-02T18:10:37.695Z [err]  ERR!
2020-03-02T18:10:37.695Z [err]  stack
2020-03-02T18:10:37.696Z [err]      at PythonFinder.runChecks (/usr/local/addons/redmatic/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:136:21)
2020-03-02T18:10:37.696Z [err] gyp 
2020-03-02T18:10:37.696Z [err] ERR! 
2020-03-02T18:10:37.696Z [err] stack     at PythonFinder.<anonymous> (/usr/local/addons/redmatic/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:179:16)
2020-03-02T18:10:37.696Z [err] gyp
2020-03-02T18:10:37.696Z [err]  ERR!
2020-03-02T18:10:37.696Z [err]  stack
2020-03-02T18:10:37.696Z [err]      at PythonFinder.execFileCallback (/usr/local/addons/redmatic/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:271:16)
2020-03-02T18:10:37.696Z [err] gyp 
2020-03-02T18:10:37.697Z [err] ERR! 
2020-03-02T18:10:37.697Z [err] stack     at exithandler (child_process.js:301:5)
2020-03-02T18:10:37.697Z [err] gyp
2020-03-02T18:10:37.697Z [err]  ERR!
2020-03-02T18:10:37.697Z [err]  stack     at ChildProcess.errorhandler (child_process.js:313:5)
2020-03-02T18:10:37.697Z [err] gyp 
2020-03-02T18:10:37.697Z [err] ERR! 
2020-03-02T18:10:37.697Z [err] stack     at ChildProcess.emit (events.js:198:13)
2020-03-02T18:10:37.697Z [err] gyp
2020-03-02T18:10:37.698Z [err]  ERR!
2020-03-02T18:10:37.698Z [err]  stack
2020-03-02T18:10:37.698Z [err]      at Process.ChildProcess._handle.onexit (internal/child_process.js:246:12)
2020-03-02T18:10:37.698Z [err] gyp
2020-03-02T18:10:37.698Z [err]  ERR! 
2020-03-02T18:10:37.698Z [err] stack     at onErrorNT (internal/child_process.js:415:16)
2020-03-02T18:10:37.698Z [err] gyp ERR!
2020-03-02T18:10:37.698Z [err]  stack
2020-03-02T18:10:37.699Z [err]      at process._tickCallback (internal/process/next_tick.js:63:19)
2020-03-02T18:10:37.699Z [err] gyp
2020-03-02T18:10:37.700Z [err]  ERR! System
2020-03-02T18:10:37.700Z [err]  Linux 4.19.85
2020-03-02T18:10:37.700Z [err] gyp 
2020-03-02T18:10:37.700Z [err] ERR! command
2020-03-02T18:10:37.700Z [err]  "/usr/local/addons/redmatic/bin/node" "/usr/local/addons/redmatic/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--library=static_library" "--module=/usr/local/addons/redmatic/var/node_modules/node-red-contrib-chatbot/node_modules/grpc/src/node/extension_binary/node-v64-linux-arm-unknown/grpc_node.node" "--module_name=grpc_node" "--module_path=/usr/local/addons/redmatic/var/node_modules/node-red-contrib-chatbot/node_modules/grpc/src/node/extension_binary/node-v64-linux-arm-unknown" "--napi_version=5" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v64"
2020-03-02T18:10:37.701Z [err] gyp
2020-03-02T18:10:37.701Z [err]  ERR!
2020-03-02T18:10:37.701Z [err]  cwd
2020-03-02T18:10:37.701Z [err]  /usr/local/addons/redmatic/var/node_modules/node-red-contrib-chatbot/node_modules/grpc
2020-03-02T18:10:37.701Z [err] gyp
2020-03-02T18:10:37.701Z [err]  ERR!
2020-03-02T18:10:37.701Z [err]  node -v v10.19.0
2020-03-02T18:10:37.701Z [err] gyp
2020-03-02T18:10:37.702Z [err]  ERR!
2020-03-02T18:10:37.702Z [err]  node-gyp -v
2020-03-02T18:10:37.702Z [err]  v5.0.7
2020-03-02T18:10:37.702Z [err] gyp 
2020-03-02T18:10:37.702Z [err] ERR! 
2020-03-02T18:10:37.702Z [err] not ok 
2020-03-02T18:10:37.714Z [err] node-pre-gyp
2020-03-02T18:10:37.714Z [err]  ERR! build error 
2020-03-02T18:10:37.716Z [err] node-pre-gyp 
2020-03-02T18:10:37.716Z [err] ERR! stack Error: Failed to execute '/usr/local/addons/redmatic/bin/node /usr/local/addons/redmatic/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --library=static_library --module=/usr/local/addons/redmatic/var/node_modules/node-red-contrib-chatbot/node_modules/grpc/src/node/extension_binary/node-v64-linux-arm-unknown/grpc_node.node --module_name=grpc_node --module_path=/usr/local/addons/redmatic/var/node_modules/node-red-contrib-chatbot/node_modules/grpc/src/node/extension_binary/node-v64-linux-arm-unknown --napi_version=5 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v64' (1)
2020-03-02T18:10:37.716Z [err] node-pre-gyp
2020-03-02T18:10:37.716Z [err]  ERR! stack
2020-03-02T18:10:37.716Z [err]      at ChildProcess.<anonymous> (/usr/local/addons/redmatic/var/node_modules/node-red-contrib-chatbot/node_modules/grpc/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
2020-03-02T18:10:37.716Z [err] node-pre-gyp 
2020-03-02T18:10:37.717Z [err] ERR! 
2020-03-02T18:10:37.717Z [err] stack     at ChildProcess.emit (events.js:198:13)
2020-03-02T18:10:37.717Z [err] node-pre-gyp
2020-03-02T18:10:37.717Z [err]  ERR!
2020-03-02T18:10:37.717Z [err]  stack
2020-03-02T18:10:37.717Z [err]      at maybeClose (internal/child_process.js:982:16)
2020-03-02T18:10:37.717Z [err] node-pre-gyp 
2020-03-02T18:10:37.717Z [err] ERR! 
2020-03-02T18:10:37.717Z [err] stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
2020-03-02T18:10:37.719Z [err] node-pre-gyp
2020-03-02T18:10:37.719Z [err]  ERR! System Linux 4.19.85
2020-03-02T18:10:37.719Z [err] node-pre-gyp
2020-03-02T18:10:37.719Z [err]  ERR!
2020-03-02T18:10:37.720Z [err]  command
2020-03-02T18:10:37.720Z [err]  "/usr/local/addons/redmatic/bin/node" "/usr/local/addons/redmatic/var/node_modules/node-red-contrib-chatbot/node_modules/grpc/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build" "--library=static_library"
2020-03-02T18:10:37.720Z [err] node-pre-gyp 
2020-03-02T18:10:37.720Z [err] ERR! cwd /usr/local/addons/redmatic/var/node_modules/node-red-contrib-chatbot/node_modules/grpc
2020-03-02T18:10:37.720Z [err] node-pre-gyp 
2020-03-02T18:10:37.720Z [err] ERR! node -v
2020-03-02T18:10:37.721Z [err]  v10.19.0
2020-03-02T18:10:37.721Z [err] node-pre-gyp
2020-03-02T18:10:37.721Z [err]  ERR!
2020-03-02T18:10:37.721Z [err]  node-pre-gyp -v v0.14.0
2020-03-02T18:10:37.721Z [err] node-pre-gyp
2020-03-02T18:10:37.721Z [err]  ERR!
2020-03-02T18:10:37.721Z [err]  not ok
2020-03-02T18:10:37.722Z [err]  
2020-03-02T18:10:37.725Z [out] Failed to execute '/usr/local/addons/redmatic/bin/node /usr/local/addons/redmatic/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --library=static_library --module=/usr/local/addons/redmatic/var/node_modules/node-red-contrib-chatbot/node_modules/grpc/src/node/extension_binary/node-v64-linux-arm-unknown/grpc_node.node --module_name=grpc_node --module_path=/usr/local/addons/redmatic/var/node_modules/node-red-contrib-chatbot/node_modules/grpc/src/node/extension_binary/node-v64-linux-arm-unknown --napi_version=5 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v64' (1)
2020-03-02T18:10:53.586Z [err] npm 
2020-03-02T18:10:53.587Z [err] WARN babel-loader@7.1.5 requires a peer of babel-core@6 but none is installed. You must install peer dependencies yourself.
2020-03-02T18:10:53.587Z [err] npm WARN babel-loader@7.1.5 requires a peer of webpack@2 || 3 || 4 but none is installed. You must install peer dependencies yourself.
2020-03-02T18:10:53.587Z [err] npm WARN node-red-project@0.0.1 No repository field.
2020-03-02T18:10:53.587Z [err] npm WARN
2020-03-02T18:10:53.587Z [err]  node-red-project@0.0.1 No license field.
2020-03-02T18:10:53.588Z [err] 
2020-03-02T18:10:53.619Z [err] npm ERR! 
2020-03-02T18:10:53.619Z [err] code
2020-03-02T18:10:53.620Z [err]  ELIFECYCLE
2020-03-02T18:10:53.621Z [err] npm
2020-03-02T18:10:53.621Z [err]  ERR! errno 1
2020-03-02T18:10:53.622Z [err] npm
2020-03-02T18:10:53.623Z [err]  ERR! grpc@1.24.2 install: `node-pre-gyp install --fallback-to-build --library=static_library`
2020-03-02T18:10:53.623Z [err] npm
2020-03-02T18:10:53.623Z [err]  ERR! Exit status 1
2020-03-02T18:10:53.624Z [err] npm
2020-03-02T18:10:53.624Z [err]  ERR! 
2020-03-02T18:10:53.624Z [err] npm ERR! Failed at the grpc@1.24.2 install script.
2020-03-02T18:10:53.625Z [err] npm ERR!
2020-03-02T18:10:53.625Z [err]  This is probably not a problem with npm. There is likely additional logging output above.
2020-03-02T18:10:53.819Z [err] 
2020-03-02T18:10:53.820Z [err] npm ERR! A complete log of this run can be found in:
2020-03-02T18:10:53.820Z [err] npm ERR!     /usr/local/addons/redmatic/npm-cache/_logs/2020-03-02T18_10_53_736Z-debug.log
2020-03-02T18:10:53.929Z rc=1`

Node-red installation: Redmatic 5.4.1 on Raspimatic 3.47.22.20191130
