### ISSUE TITLE
node-red-node-discovery lässt sich nicht installieren,-- python Fehler, gibt es da eine Möglichkeit ? benötige es für meine Bose Soundtouch integration

### ISSUE THREAD

**Issue by Lenardo1** [rdmtc/RedMatic#343]
ich würde gerne diesen Flow  https://flows.nodered.org/flow/c269451c61ad7f5ffdd7574a669e48a6 
 ausprobieren, dieser verwendet aber den node-red-node-discovery und der lässt sich auf meiner RedMatic nicht installieren, kenne mich zuwendig im Detail aus das ich die Fhlermeldung richtig deuten könnte,-- alle Fehlermeldungen durchgegangen soweit möglich, keine änderung

**Comment by Tscherno** [comment]
Naja den Standardtext könntest schon lesen und beachten. Genaue Ausgabe des Problems wäre sicher auch hilfreich.

**Comment by Lenardo1** [comment]
sorry, dachte das ist verständlich und so kurz wie möglich. Ich versuche in RedMatic das node red node discovery zu installieren  https://flows.nodered.org/node/node-red-node-discovery, was weder in RedMatic noch auf windows (testweise) funktioniert,- im log steht das keine python version da ist, wobei das installiert ist, das kein mdns verzeichniss angelegt werden kann usw.,-- bin schon alle anleitungen durch,-- hab python manuell installiert, node gyp und alles was so in den fehlermeldungen steht, aber die fehlermeldungen ändern sich nicht

**Comment by Tscherno** [comment]
Wie konntest Du python manuell auf der CCU installieren?!? Lad vielleicht mal das Logfile hoch.

**Comment by Lenardo1** [comment]
python -->  npm install python

logfile

-----------------------------------------------------------
2020-04-24T13:37:50.299Z installieren : node-red-node-discovery 0.0.22

2020-04-24T13:38:45.042Z npm install --no-package-lock --global-style --no-audit --no-update-notifier --save --save-prefix="~" --production node-red-node-discovery@0.0.22
2020-04-24T13:38:59.464Z [out] 
2020-04-24T13:38:59.464Z [out] > mdns@2.5.1 install /usr/local/addons/redmatic/var/node_modules/node-red-node-discovery/node_modules/mdns
2020-04-24T13:38:59.464Z [out] > node-gyp rebuild
2020-04-24T13:38:59.464Z [out] 
2020-04-24T13:39:00.343Z [err] gyp
2020-04-24T13:39:00.345Z [err]  
2020-04-24T13:39:00.346Z [err] ERR!
2020-04-24T13:39:00.346Z [err]  
2020-04-24T13:39:00.346Z [err] find Python
2020-04-24T13:39:00.346Z [err]  
2020-04-24T13:39:00.347Z [err] gyp
2020-04-24T13:39:00.347Z [err]  
2020-04-24T13:39:00.347Z [err] ERR!
2020-04-24T13:39:00.347Z [err]  
2020-04-24T13:39:00.348Z [err] find Python
2020-04-24T13:39:00.348Z [err]  Python is not set from command line or npm configuration
2020-04-24T13:39:00.348Z [err] gyp
2020-04-24T13:39:00.348Z [err]  
2020-04-24T13:39:00.349Z [err] ERR!
2020-04-24T13:39:00.349Z [err]  
2020-04-24T13:39:00.349Z [err] find Python
2020-04-24T13:39:00.349Z [err]  Python is not set from environment variable PYTHON
2020-04-24T13:39:00.350Z [err] gyp
2020-04-24T13:39:00.350Z [err]  
2020-04-24T13:39:00.350Z [err] ERR!
2020-04-24T13:39:00.350Z [err]  
2020-04-24T13:39:00.351Z [err] find Python
2020-04-24T13:39:00.351Z [err]  checking if "python" can be used
2020-04-24T13:39:00.351Z [err] gyp
2020-04-24T13:39:00.351Z [err]  
2020-04-24T13:39:00.351Z [err] ERR!
2020-04-24T13:39:00.352Z [err]  
2020-04-24T13:39:00.352Z [err] find Python
2020-04-24T13:39:00.352Z [err]  - "python" is not in PATH or produced an error
2020-04-24T13:39:00.352Z [err] gyp
2020-04-24T13:39:00.353Z [err]  
2020-04-24T13:39:00.353Z [err] ERR!
2020-04-24T13:39:00.353Z [err]  
2020-04-24T13:39:00.353Z [err] find Python
2020-04-24T13:39:00.354Z [err]  checking if "python2" can be used
2020-04-24T13:39:00.354Z [err] gyp
2020-04-24T13:39:00.354Z [err]  
2020-04-24T13:39:00.354Z [err] ERR!
2020-04-24T13:39:00.354Z [err]  
2020-04-24T13:39:00.355Z [err] find Python
2020-04-24T13:39:00.355Z [err]  - "python2" is not in PATH or produced an error
2020-04-24T13:39:00.355Z [err] gyp
2020-04-24T13:39:00.355Z [err]  
2020-04-24T13:39:00.356Z [err] ERR!
2020-04-24T13:39:00.356Z [err]  
2020-04-24T13:39:00.356Z [err] find Python
2020-04-24T13:39:00.356Z [err]  checking if "python3" can be used
2020-04-24T13:39:00.356Z [err] gyp
2020-04-24T13:39:00.357Z [err]  
2020-04-24T13:39:00.357Z [err] ERR!
2020-04-24T13:39:00.357Z [err]  
2020-04-24T13:39:00.357Z [err] find Python
2020-04-24T13:39:00.358Z [err]  - "python3" is not in PATH or produced an error
2020-04-24T13:39:00.358Z [err] gyp
2020-04-24T13:39:00.358Z [err]  
2020-04-24T13:39:00.358Z [err] ERR!
2020-04-24T13:39:00.359Z [err]  
2020-04-24T13:39:00.359Z [err] find Python
2020-04-24T13:39:00.359Z [err]  
2020-04-24T13:39:00.359Z [err] gyp
2020-04-24T13:39:00.359Z [err]  
2020-04-24T13:39:00.360Z [err] ERR!
2020-04-24T13:39:00.360Z [err]  
2020-04-24T13:39:00.360Z [err] find Python
2020-04-24T13:39:00.360Z [err]  **********************************************************
2020-04-24T13:39:00.361Z [err] gyp
2020-04-24T13:39:00.361Z [err]  
2020-04-24T13:39:00.361Z [err] ERR!
2020-04-24T13:39:00.361Z [err]  
2020-04-24T13:39:00.361Z [err] find Python
2020-04-24T13:39:00.362Z [err]  You need to install the latest version of Python.
2020-04-24T13:39:00.362Z [err] gyp 
2020-04-24T13:39:00.362Z [err] ERR! 
2020-04-24T13:39:00.362Z [err] find Python Node-gyp should be able to find and use Python. If not,
2020-04-24T13:39:00.362Z [err] gyp
2020-04-24T13:39:00.362Z [err]  
2020-04-24T13:39:00.362Z [err] ERR! 
2020-04-24T13:39:00.362Z [err] find Python you can try one of the following options:
2020-04-24T13:39:00.362Z [err] gyp
2020-04-24T13:39:00.363Z [err]  
2020-04-24T13:39:00.363Z [err] ERR! 
2020-04-24T13:39:00.363Z [err] find Python
2020-04-24T13:39:00.363Z [err]  - Use the switch --python="/path/to/pythonexecutable"
2020-04-24T13:39:00.363Z [err] gyp
2020-04-24T13:39:00.363Z [err]  ERR!
2020-04-24T13:39:00.363Z [err]  
2020-04-24T13:39:00.363Z [err] find Python   (accepted by both node-gyp and npm)
2020-04-24T13:39:00.363Z [err] gyp
2020-04-24T13:39:00.363Z [err]  ERR!
2020-04-24T13:39:00.363Z [err]  
2020-04-24T13:39:00.363Z [err] find Python - Set the environment variable PYTHON
2020-04-24T13:39:00.364Z [err] gyp
2020-04-24T13:39:00.364Z [err]  ERR!
2020-04-24T13:39:00.364Z [err]  
2020-04-24T13:39:00.364Z [err] find Python - Set the npm configuration variable python:
2020-04-24T13:39:00.364Z [err] gyp
2020-04-24T13:39:00.364Z [err]  ERR!
2020-04-24T13:39:00.364Z [err]  
2020-04-24T13:39:00.364Z [err] find Python   npm config set python "/path/to/pythonexecutable"
2020-04-24T13:39:00.364Z [err] gyp
2020-04-24T13:39:00.364Z [err]  ERR!
2020-04-24T13:39:00.364Z [err]  
2020-04-24T13:39:00.364Z [err] find Python For more information consult the documentation at:
2020-04-24T13:39:00.365Z [err] gyp
2020-04-24T13:39:00.365Z [err]  ERR!
2020-04-24T13:39:00.365Z [err]  
2020-04-24T13:39:00.365Z [err] find Python https://github.com/nodejs/node-gyp#installation
2020-04-24T13:39:00.365Z [err] gyp 
2020-04-24T13:39:00.365Z [err] ERR!
2020-04-24T13:39:00.365Z [err]  find Python
2020-04-24T13:39:00.365Z [err]  **********************************************************
2020-04-24T13:39:00.366Z [err] gyp ERR!
2020-04-24T13:39:00.366Z [err]  
2020-04-24T13:39:00.366Z [err] find Python 
2020-04-24T13:39:00.371Z [err] gyp
2020-04-24T13:39:00.371Z [err]  ERR! configure error 
2020-04-24T13:39:00.372Z [err] gyp
2020-04-24T13:39:00.372Z [err]  ERR! 
2020-04-24T13:39:00.373Z [err] stack Error: Could not find any Python installation to use
2020-04-24T13:39:00.373Z [err] gyp 
2020-04-24T13:39:00.373Z [err] ERR!
2020-04-24T13:39:00.373Z [err]  
2020-04-24T13:39:00.373Z [err] stack     at PythonFinder.fail (/usr/local/addons/redmatic/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:307:47)
2020-04-24T13:39:00.373Z [err] gyp
2020-04-24T13:39:00.373Z [err]  ERR!
2020-04-24T13:39:00.373Z [err]  
2020-04-24T13:39:00.373Z [err] stack     at PythonFinder.runChecks (/usr/local/addons/redmatic/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:136:21)
2020-04-24T13:39:00.373Z [err] gyp
2020-04-24T13:39:00.373Z [err]  ERR!
2020-04-24T13:39:00.374Z [err]  stack
2020-04-24T13:39:00.374Z [err]      at PythonFinder.<anonymous> (/usr/local/addons/redmatic/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:179:16)
2020-04-24T13:39:00.374Z [err] gyp
2020-04-24T13:39:00.374Z [err]  ERR!
2020-04-24T13:39:00.374Z [err]  
2020-04-24T13:39:00.374Z [err] stack     at PythonFinder.execFileCallback (/usr/local/addons/redmatic/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:271:16)
2020-04-24T13:39:00.374Z [err] gyp 
2020-04-24T13:39:00.374Z [err] ERR!
2020-04-24T13:39:00.374Z [err]  stack
2020-04-24T13:39:00.374Z [err]      at exithandler (child_process.js:301:5)
2020-04-24T13:39:00.374Z [err] gyp
2020-04-24T13:39:00.375Z [err]  ERR!
2020-04-24T13:39:00.375Z [err]  stack
2020-04-24T13:39:00.375Z [err]      at ChildProcess.errorhandler (child_process.js:313:5)
2020-04-24T13:39:00.375Z [err] gyp
2020-04-24T13:39:00.375Z [err]  ERR!
2020-04-24T13:39:00.375Z [err]  stack
2020-04-24T13:39:00.375Z [err]      at ChildProcess.emit (events.js:198:13)
2020-04-24T13:39:00.375Z [err] gyp 
2020-04-24T13:39:00.375Z [err] ERR!
2020-04-24T13:39:00.375Z [err]  
2020-04-24T13:39:00.375Z [err] stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:246:12)
2020-04-24T13:39:00.376Z [err] gyp
2020-04-24T13:39:00.376Z [err]  ERR! stack     at onErrorNT (internal/child_process.js:415:16)
2020-04-24T13:39:00.376Z [err] gyp ERR! 
2020-04-24T13:39:00.376Z [err] stack     at process._tickCallback (internal/process/next_tick.js:63:19)
2020-04-24T13:39:00.377Z [err] gyp
2020-04-24T13:39:00.377Z [err]  ERR! System
2020-04-24T13:39:00.378Z [err]  Linux 4.19.105
2020-04-24T13:39:00.378Z [err] gyp
2020-04-24T13:39:00.378Z [err]  ERR!
2020-04-24T13:39:00.378Z [err]  
2020-04-24T13:39:00.378Z [err] command "/usr/local/addons/redmatic/bin/node" "/usr/local/addons/redmatic/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
2020-04-24T13:39:00.378Z [err] gyp
2020-04-24T13:39:00.378Z [err]  
2020-04-24T13:39:00.378Z [err] ERR! 
2020-04-24T13:39:00.379Z [err] cwd
2020-04-24T13:39:00.379Z [err]  /usr/local/addons/redmatic/var/node_modules/node-red-node-discovery/node_modules/mdns
2020-04-24T13:39:00.379Z [err] gyp
2020-04-24T13:39:00.379Z [err]  ERR!
2020-04-24T13:39:00.379Z [err]  
2020-04-24T13:39:00.379Z [err] node -v v10.20.0
2020-04-24T13:39:00.379Z [err] gyp
2020-04-24T13:39:00.379Z [err]  ERR!
2020-04-24T13:39:00.379Z [err]  
2020-04-24T13:39:00.379Z [err] node-gyp -v v5.1.0
2020-04-24T13:39:00.380Z [err] gyp
2020-04-24T13:39:00.380Z [err]  ERR!
2020-04-24T13:39:00.380Z [err]  
2020-04-24T13:39:00.380Z [err] not ok 
2020-04-24T13:39:01.509Z [err] npm
2020-04-24T13:39:01.509Z [err]  WARN node-red-project@0.0.1 No repository field.
2020-04-24T13:39:01.510Z [err] npm 
2020-04-24T13:39:01.510Z [err] WARN node-red-project@0.0.1 No license field.
2020-04-24T13:39:01.511Z [err] 
2020-04-24T13:39:01.553Z [err] npm
2020-04-24T13:39:01.553Z [err]  ERR! code
2020-04-24T13:39:01.553Z [err]  ELIFECYCLE
2020-04-24T13:39:01.554Z [err] npm
2020-04-24T13:39:01.555Z [err]  ERR!
2020-04-24T13:39:01.555Z [err]  errno
2020-04-24T13:39:01.555Z [err]  1
2020-04-24T13:39:01.556Z [err] npm
2020-04-24T13:39:01.556Z [err]  ERR!
2020-04-24T13:39:01.557Z [err]  mdns@2.5.1 install: `node-gyp rebuild`
2020-04-24T13:39:01.557Z [err] npm 
2020-04-24T13:39:01.557Z [err] ERR!
2020-04-24T13:39:01.557Z [err]  Exit status 1
2020-04-24T13:39:01.558Z [err] npm
2020-04-24T13:39:01.560Z [err]  ERR! 
2020-04-24T13:39:01.560Z [err] npm ERR! Failed at the mdns@2.5.1 install script.
2020-04-24T13:39:01.560Z [err] npm 
2020-04-24T13:39:01.561Z [err] ERR! This is probably not a problem with npm. There is likely additional logging output above.
2020-04-24T13:39:01.602Z [err] 
2020-04-24T13:39:01.603Z [err] npm 
2020-04-24T13:39:01.603Z [err] ERR! A complete log of this run can be found in:
2020-04-24T13:39:01.603Z [err] npm 
2020-04-24T13:39:01.603Z [err] ERR!
2020-04-24T13:39:01.603Z [err]      /usr/local/addons/redmatic/npm-cache/_logs/2020-04-24T13_39_01_574Z-debug.log
2020-04-24T13:39:01.632Z rc=1

**Comment by Tscherno** [comment]
Das wird so nicht funktionieren. Das ist nur ein Wrapper für Python, nicht python selbst. Es müsste jemand ein Binär-Paket für Python auf der CCU bauen. Die Frage ist, ob man das Modul node-red-node-discovery auch unabhängig davon zur Verfügung stellen könnte. Es gibt ja schon ein paar andere Module separat. Das wäre ein Request an @hobbyquaker

**Comment by Lenardo1** [comment]
das schreibe/frage ich dann unter pull request ?

**Comment by Tscherno** [comment]
Pull Request stellt man, wenn man zur Entwicklung/Sourcecode beitragen will. Das issue hier ist schon richtig.

**Comment by Tscherno** [comment]
Andere Frage: Ich habe mir das Node gerade mal angeschaut. Das ist ja nur für Autodiscovery. Das scheint unnötig zu sein, wenn man das/die Geräte manuell hinzufügt. Du beziehst dich vermutlich auf diesen Beispielflow? https://flows.nodered.org/flow/c269451c61ad7f5ffdd7574a669e48a6

Das lässt sich sicher anpassen, so dass es auf IP oder Hostname deiner Geräte geht.

**Comment by Lenardo1** [comment]
ja genau um diesen flow geht es, ich hab schon versucht den flow zu verstehen, aber ich eher kann max. dinge zusammenklicken, wie das im Hintergrund funktioniert ist mir zu hoch, wenn du mir da noch ein wenig auf die Sprünge helfen kannst was das discovery da drinnen macht und wie ich das ersetzen kann, wäre ich sehr dankbar.  die Geräte Ip/MAC usw. kenn ich natürlich aber das ist ein Multiroom system also mehrere Geräte ich denke danach wird gesucht. danke !

**Comment by cokefridge** [comment]
Hi @Lenardo1, wärst du so nett, deinen Flow mit dem configuration inject node zur Verfügung zu stellen? Ich blick's irgendwie nicht ganz :-) Wäre super!

**Comment by hobbyquaker** [comment]
RedMatic 9 ist als Vorabversion verfügbar (https://github.com/rdmtc/RedMatic/releases) und bewusst verschlankt: Der RedMatic-Paketmanager, die binären Pakete, die vorinstallierten Zusatz-Nodes (Dashboard, HomeKit, ZigBee, ...) und die WebApp sind entfallen. Nodes werden nur noch über den Node-RED Paletten-Manager installiert; Nodes mit nativen (binären) Abhängigkeiten lassen sich auf der CCU nicht installieren - das ist eine bekannte und akzeptierte Einschränkung (https://github.com/rdmtc/RedMatic/wiki/Node-Installation#nodes-mit-binärmodulen). Dieses Issue betrifft eine entfallene Komponente und wird daher geschlossen. Hinweise zum Umstieg: https://github.com/rdmtc/RedMatic/wiki/RedMatic-9-Migration

---
*Written by Claude Fable on behalf of hobbyquaker.*
