### ISSUE TITLE
(node:1246) UnhandledPromiseRejectionWarning: Error: overwritten mit v6.0.2

### ISSUE THREAD

**Issue by dehsgr** [rdmtc/RedMatic#391]
Mit v6.0.2 ist mir beim Schalten des Vale Irrigation heute folgender Fehler im Logfile aufgefallen. Ich könnte mir vorstellend dass der für Dich ganz interessant sein könne:

Aug 29 19:00:52 homematic daemon.err node-red: (node:1246) UnhandledPromiseRejectionWarning: Error: overwritten
Aug 29 19:00:52 homematic daemon.err node-red:     at /usr/local/addons/redmatic/var/node_modules/node-red-contrib-ccu/nodes/ccu-connection.js:2763:55
Aug 29 19:00:52 homematic daemon.err node-red:     at new Promise (<anonymous>)
Aug 29 19:00:52 homematic daemon.err node-red:     at CcuConnectionNode.setValue (/usr/local/addons/redmatic/var/node_modules/node-red-contrib-ccu/nodes/ccu-connection.js:2753:20)
Aug 29 19:00:52 homematic daemon.err node-red:     at /usr/local/addons/redmatic/lib/node_modules/redmatic-homekit/nodes/redmatic-homekit-homematic-irrigation.js:42:38
Aug 29 19:00:52 homematic daemon.err node-red: (node:1246) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
Aug 29 19:00:52 homematic daemon.err node-red: (node:1246) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by hobbyquaker** [comment]
Dieses Issue betrifft die CCU Nodes bzw. RedMatic-HomeKit, nicht das Addon selbst. Mit RedMatic 9 (https://github.com/rdmtc/RedMatic/releases) sind node-red-contrib-ccu 4.0.0 enthalten und RedMatic-HomeKit 4.0 in Entwicklung - vieles hat sich geändert. Bitte mit RedMatic 9 erneut prüfen und, falls das Problem weiterhin besteht, ein neues Issue im passenden Repository eröffnen: https://github.com/rdmtc/node-red-contrib-ccu/issues bzw. https://github.com/rdmtc/RedMatic-HomeKit/issues. Hier geschlossen.

---
*Written by Claude Fable on behalf of hobbyquaker.*
