### ISSUE TITLE
TypeError: Cannot read property 'UUID' of undefined

### ISSUE THREAD

**Issue by TIMSCHMITZ** [rdmtc/RedMatic#405]
after update to RedMatic 6.0.3 the demon isn't starting in normal mode. Only SafeMode is possible

```

Sep 30 18:59:42
Package redmatic-homekit update 3.2.0 to 3.2.2
Get https://github.com/rdmtc/RedMatic/releases/download/v6.0.3/redmatic-pkg-redmatic-homekit-3.2.2.tar.gz
Downloaded 20M in 15 seconds
File integrity check successful
Extracting redmatic-homekit.tar.gz
Done.

Sep 30 19:29:33 ccu3-webui daemon.debug node-red[8381]: [ccu-connection:localhost] cb mismatch misc 40 datapointName BidCos-RF.LEQ1175850:0.LOWBAT BidCos-RF.UNITEMP004:7.TEMPERATURE


Sep 30 19:29:33 ccu3-webui daemon.debug node-red[8381]: [redmatic-homekit-bridge:RedMatic Bridge] addAccessory Pooltemper HB-UNI-Sen-TEMP-DS18B20 Pooltemper
Sep 30 19:29:33 ccu3-webui daemon.debug node-red[8381]: [redmatic-homekit-bridge:RedMatic Bridge] publish waitForAccessories
Sep 30 19:29:33 ccu3-webui daemon.debug node-red[8381]: [redmatic-homekit-homematic-devices:542aa513.94e9ac] init accessory Pooltemper HB-UNI-Sen-TEMP-DS18B20 HB-UNI-Sen-TEMP-DS18B20 Pooltemper
Sep 30 19:29:33 ccu3-webui daemon.debug node-red[8381]: [redmatic-homekit-homematic-devices:542aa513.94e9ac] option Pooltemper:1 1 undefined true
Sep 30 19:29:33 ccu3-webui daemon.debug node-red[8381]: [redmatic-homekit-homematic-devices:542aa513.94e9ac] add service TEMPERATURE (0) to HB-UNI-Sen-TEMP-DS18B20 HB-UNI-Sen-TEMP-DS18B20 Pooltemper
Sep 30 19:29:33 ccu3-webui daemon.err node-red: 30 Sep 19:29:33 - [red] Uncaught Exception:
Sep 30 19:29:33 ccu3-webui daemon.err node-red: 30 Sep 19:29:33 - TypeError: Cannot read property 'UUID' of undefined
Sep 30 19:29:33 ccu3-webui daemon.err node-red:     at Accessory.addService (/usr/local/addons/redmatic/lib/node_modules/redmatic-homekit/node_modules/hap-nodejs/lib/Accessory.js:149:35)
Sep 30 19:29:33 ccu3-webui daemon.err node-red:     at HbUniSenTemp.addService (/usr/local/addons/redmatic/lib/node_modules/redmatic-homekit/homematic-devices/lib/accessory.js:110:22)
Sep 30 19:29:33 ccu3-webui daemon.err node-red:     at HbUniSenTemp.init (/usr/local/addons/redmatic/lib/node_modules/redmatic-homekit/homematic-devices/hb-uni-sen-temp-ds18b20.js:17:18)
Sep 30 19:29:33 ccu3-webui daemon.err node-red:     at Immediate.<anonymous> (/usr/local/addons/redmatic/lib/node_modules/redmatic-homekit/homematic-devices/lib/accessory.js:83:22)
Sep 30 19:29:33 ccu3-webui daemon.err node-red:     at processImmediate (internal/timers.js:461:21)
Sep 30 19:29:33 ccu3-webui daemon.err node-red: Node-RED exited with non-zero exit status 1
Sep 30 19:29:33 ccu3-webui daemon.err redmatic: Maximum Node-RED restarts exceeded


```

**Comment by hobbyquaker** [comment]
https://github.com/rdmtc/RedMatic-HomeKit/issues/295

**Comment by hobbyquaker** [comment]
Until https://github.com/rdmtc/RedMatic-HomeKit/issues/295 is fixed try to workaround by starting in safe mode (see https://github.com/rdmtc/RedMatic/wiki/Safe-Mode) and removing HB- devices from HomeKit.

**Comment by TIMSCHMITZ** [comment]
Does that mean until #295 isn’t fixed homebridge isn’t working?
