### ISSUE TITLE
Nach Update auf 6.0.3: NodeRed beendet sich nach dem Start wieder - ist aber trotzdem per Web erreichbar.

### ISSUE THREAD

**Issue by MehrCurry** [rdmtc/RedMatic#407]
Ich habe den Update auf 6.0.3 gemacht (drüber installieren). Jetzt behauptet die Oberfläche in der CCU3, dass NodeRed gestopped wäre. Nach dem Klick auf den Start Button kommt "Es ist ein Fehler aufgetreten" und es wird angezeigt, dass NodeRed gestoppt wäre.

Tatsächlich ist NodeRed aber die ganze Zeit per Web erreichbar und funktioniert so wie immer.

Im Log gibt es einen kleinen Fehler von einen Plugin:

```
Oct  2 08:19:03 ccu3-webui daemon.err node-red: (node:1103) UnhandledPromiseRejectionWarning: Error: Huejay: timeout of 15000ms exceeded
Oct  2 08:19:03 ccu3-webui daemon.err node-red:     at /usr/local/addons/redmatic/var/node_modules/node-red-contrib-huemagic/node_modules/huejay/lib/Transport.js:106:15
Oct  2 08:19:03 ccu3-webui daemon.err node-red:     at runMicrotasks (<anonymous>)
Oct  2 08:19:03 ccu3-webui daemon.err node-red:     at processTicksAndRejections (internal/process/task_queues.js:93:5)
Oct  2 08:19:03 ccu3-webui daemon.err node-red: (node:1103) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
Oct  2 08:19:03 ccu3-webui daemon.err node-red: (node:1103) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by djiwondee** [comment]
@MehrCurry vielleicht das selbe "Problem" wie [hier](https://github.com/rdmtc/RedMatic/issues/383).

I. d. R. sollte es reichen den Cache des Browser zu leeren, bevor die Redmatic-UI erneut benutzt wird.

**Comment by MehrCurry** [comment]
Ok, das Problem sitzt vor dem Rechner. Danke
