### ISSUE TITLE
Redmatic stoppt und startet nicht wieder neu

### ISSUE THREAD

**Issue by Matten-Matten** [rdmtc/RedMatic#421]
Bei mir steigt redmatic sporadisch aus und startet nicht selbstständig neu.

Log:

```
Oct 18 06:07:48 ccu3-webui daemon.err node-red: 18 Oct 06:07:48 - [red] Uncaught Exception:
Oct 18 06:07:48 ccu3-webui daemon.err node-red: 18 Oct 06:07:48 - Error: read ENOTCONN
Oct 18 06:07:48 ccu3-webui daemon.err node-red:     at tryReadStart (net.js:573:20)
Oct 18 06:07:48 ccu3-webui daemon.err node-red:     at Socket._read (net.js:584:5)
Oct 18 06:07:48 ccu3-webui daemon.err node-red:     at Socket.Readable.read (_stream_readable.js:479:10)
Oct 18 06:07:48 ccu3-webui daemon.err node-red:     at Socket.read (net.js:624:39)
Oct 18 06:07:48 ccu3-webui daemon.err node-red:     at new Socket (net.js:376:12)
Oct 18 06:07:48 ccu3-webui daemon.err node-red:     at Object.Socket (net.js:268:41)
Oct 18 06:07:48 ccu3-webui daemon.err node-red:     at createSocket (internal/child_process.js:313:14)
Oct 18 06:07:48 ccu3-webui daemon.err node-red:     at ChildProcess.spawn (internal/child_process.js:432:23)
Oct 18 06:07:48 ccu3-webui daemon.err node-red:     at spawn (child_process.js:553:9)
Oct 18 06:07:48 ccu3-webui daemon.err node-red:     at Object.execFile (child_process.js:237:17)
Oct 18 06:07:48 ccu3-webui daemon.err node-red:     at exec (child_process.js:158:25)
Oct 18 06:07:48 ccu3-webui daemon.err node-red:     at ExecNode._inputCallback (/usr/local/addons/redmatic/lib/node_modules/node-red/node_modules/@node-red/nodes/core/function/90-exec.js:134:29)
Oct 18 06:07:48 ccu3-webui daemon.err node-red:     at ExecNode.Node._emitInput (/usr/local/addons/redmatic/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/nodes/Node.js:200:18)
Oct 18 06:07:48 ccu3-webui daemon.err node-red:     at Immediate._onImmediate (/usr/local/addons/redmatic/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/nodes/Node.js:179:33)
Oct 18 06:07:48 ccu3-webui daemon.err node-red:     at processImmediate (internal/timers.js:461:21)
Oct 18 06:08:04 ccu3-webui user.err monit[1324]: 'redmatic-nodered' process is not running
Oct 18 06:08:21 ccu3-webui user.err monit[1324]: 'redmatic-nodered' process is not running
Oct 18 06:08:38 ccu3-webui user.err monit[1324]: 'redmatic-nodered' process is not running
Oct 18 06:08:54 ccu3-webui user.err monit[1324]: 'redmatic-nodered' process is not running
Oct 18 06:09:11 ccu3-webui user.err monit[1324]: 'redmatic-nodered' process is not running
Oct 18 06:09:28 ccu3-webui user.err monit[1324]: 'redmatic-nodered' process is not running


```
bin jetzt nicht wirklich schlau aus dem log geworden, aber wenn ich das richtig verstehe,
gibt es probleme mit dem ExecNode oder? 

Kann mir da jemand helfen?

**Comment by Matten-Matten** [comment]
mein System:

```
"redmatic": "6.0.4",
   "nodejs": "14.13.1",
   "@node-red-contrib-themes/midnight-red": "1.4.4",
   "ain2": "3.0.0",
   "node-red": "1.1.3",
   "node-red-contrib-zigbee": "0.20.0",
   "npm": "6.14.8",
   "lodash.get": "4.4.2",
   "node-red-contrib-alexa-remote2": "3.10.4",
   "node-red-contrib-amazon-echo": "0.1.9",
   "node-red-contrib-broadlink-control": "2.1.1",
   "node-red-contrib-ccu": "3.2.1",
   "node-red-contrib-color-convert": "0.0.5",
   "node-red-contrib-combine": "1.8.1",
   "node-red-contrib-fritz": "1.3.9",
   "node-red-contrib-hyperion": "0.1.3",
   "node-red-contrib-ical-events": "0.10.2",
   "node-red-contrib-md5": "1.0.4",
   "node-red-contrib-milight-2": "1.0.8",
   "node-red-contrib-moment": "3.0.3",
   "node-red-contrib-neato-botvac": "0.2.2",
   "node-red-contrib-onvif-nodes": "0.0.1-beta.7",
   "node-red-contrib-pushover": "0.2.0",
   "node-red-contrib-samsung-tv": "0.2.0",
   "node-red-contrib-simple-gate": "0.3.1",
   "node-red-contrib-sun-position": "1.1.7",
   "node-red-contrib-unifi": "0.1.15",
   "node-red-dashboard": "2.23.4",
   "node-red-node-base64": "0.2.1",
   "node-red-node-email": "1.7.11",
   "node-red-node-openweathermap": "0.3.1",
   "node-red-node-rbe": "0.2.9",
   "node-red-node-sentiment": "0.1.4",
   "node-red-node-tail": "0.0.3",
   "onvif": "0.6.2",
   "redmatic-led": "1.1.0",
   "redmatic-webapp": "0.3.1",
   "sax": "1.2.4",
   "xml2js": "0.4.23",
   "xmlbuilder": "11.0.1"
```

**Comment by hklages** [comment]
Ja, der Fehler tritt in der build in exec node auf. Die Zeile ist: 
`child = exec(cl, node.execOpt, function (error, stdout, stderr) {`
was uns aber auch nicht richtig weiterhilft.

Für was nimmst du EXEC nodes. Wieviele? Tritt der Fehler auf, wenn du sie "disables"?

**Comment by hobbyquaker** [comment]
RedMatic 9 (Node.js 24, Node-RED 5, npm 11) ist als Vorabversion verfügbar: https://github.com/rdmtc/RedMatic/releases - dieses Issue betrifft den alten Node.js-14-Stack und wird geschlossen. Falls das Problem mit RedMatic 9 weiterhin auftritt, bitte ein neues Issue mit Log eröffnen. Hinweise zum Umstieg: https://github.com/rdmtc/RedMatic/wiki/RedMatic-9-Migration

---
*Written by Claude Fable on behalf of hobbyquaker.*
