### ISSUE TITLE
"node-red-contrib-lgtv" in Paketverwaltung

### ISSUE THREAD

**Issue by deBob5600** [rdmtc/RedMatic#423]
Hallo,
ist es möglich das node-red-contrib-lgtv Node mit in die Paketverwaltung auf zu nehmen? 
Dies lässt sich dies über die Palette nicht installieren.

Vielen Dank
Benedikt

**Comment by hobbyquaker** [comment]
Hmm, das sollte eigentlich über den Palette Manager funktionieren. Bekommst Du eine Fehlermeldung angezeigt?

**Comment by deBob5600** [comment]
Hallo,
hier das log, nach dem Versuch, über den Palette Manager zu installieren:

-----------------------------------------------------------
2020-11-01T11:08:06.121Z installieren : node-red-contrib-lgtv 1.1.0

2020-11-01T11:08:06.382Z npm install --no-package-lock --global-style --no-audit --no-update-notifier --no-fund --save --save-prefix="~" --production node-red-contrib-lgtv@1.1.0
2020-11-01T11:08:26.088Z [out] 
2020-11-01T11:08:26.088Z [out] > bufferutil@4.0.2 install /usr/local/addons/redmatic/var/node_modules/node-red-contrib-lgtv/node_modules/bufferutil
2020-11-01T11:08:26.088Z [out] > node-gyp-build
2020-11-01T11:08:26.088Z [out] 
2020-11-01T11:08:27.759Z [err] gyp
2020-11-01T11:08:27.759Z [err]  ERR!
2020-11-01T11:08:27.760Z [err]  find Python 
2020-11-01T11:08:27.760Z [err] gyp ERR!
2020-11-01T11:08:27.760Z [err]  find Python Python is not set from command line or npm configuration
2020-11-01T11:08:27.760Z [err] gyp ERR! find Python
2020-11-01T11:08:27.760Z [err]  Python is not set from environment variable PYTHON
2020-11-01T11:08:27.760Z [err] gyp ERR! 
2020-11-01T11:08:27.761Z [err] find Python checking if "python" can be used
2020-11-01T11:08:27.761Z [err] gyp
2020-11-01T11:08:27.765Z [err]  ERR!
2020-11-01T11:08:27.766Z [err]  find Python - "python" is not in PATH or produced an error
2020-11-01T11:08:27.766Z [err] gyp ERR! find Python checking if "python2" can be used
2020-11-01T11:08:27.766Z [err] gyp ERR! find Python
2020-11-01T11:08:27.766Z [err]  - "python2" is not in PATH or produced an error
2020-11-01T11:08:27.766Z [err] gyp ERR! find Python checking if "python3" can be used
2020-11-01T11:08:27.766Z [err] gyp 
2020-11-01T11:08:27.766Z [err] ERR! find Python - "python3" is not in PATH or produced an error
2020-11-01T11:08:27.766Z [err] gyp ERR! find Python
2020-11-01T11:08:27.767Z [err]  
2020-11-01T11:08:27.767Z [err] gyp ERR! find Python **********************************************************
2020-11-01T11:08:27.767Z [err] gyp ERR! find Python You need to install the latest version of Python.
2020-11-01T11:08:27.767Z [err] gyp ERR!
2020-11-01T11:08:27.767Z [err]  find Python Node-gyp should be able to find and use Python. If not,
2020-11-01T11:08:27.767Z [err] gyp ERR! 
2020-11-01T11:08:27.767Z [err] find Python you can try one of the following options:
2020-11-01T11:08:27.767Z [err] gyp ERR! find Python
2020-11-01T11:08:27.768Z [err]  - Use the switch --python="/path/to/pythonexecutable"
2020-11-01T11:08:27.768Z [err] gyp ERR! find Python
2020-11-01T11:08:27.768Z [err]    (accepted by both node-gyp and npm)
2020-11-01T11:08:27.768Z [err] gyp ERR! find Python
2020-11-01T11:08:27.768Z [err]  - Set the environment variable PYTHON
2020-11-01T11:08:27.768Z [err] gyp ERR! 
2020-11-01T11:08:27.768Z [err] find Python - Set the npm configuration variable python:
2020-11-01T11:08:27.768Z [err] gyp ERR!
2020-11-01T11:08:27.768Z [err]  find Python   npm config set python "/path/to/pythonexecutable"
2020-11-01T11:08:27.768Z [err] gyp
2020-11-01T11:08:27.769Z [err]  ERR! find Python
2020-11-01T11:08:27.769Z [err]  For more information consult the documentation at:
2020-11-01T11:08:27.769Z [err] gyp 
2020-11-01T11:08:27.769Z [err] ERR! find Python https://github.com/nodejs/node-gyp#installation
2020-11-01T11:08:27.769Z [err] gyp
2020-11-01T11:08:27.769Z [err]  ERR! find Python **********************************************************
2020-11-01T11:08:27.769Z [err] gyp ERR! find Python
2020-11-01T11:08:27.769Z [err]  
2020-11-01T11:08:27.772Z [err] gyp
2020-11-01T11:08:27.772Z [err]  ERR! configure error 
2020-11-01T11:08:27.773Z [err] gyp 
2020-11-01T11:08:27.774Z [err] ERR! stack Error: Could not find any Python installation to use
2020-11-01T11:08:27.774Z [err] gyp ERR! stack     at PythonFinder.fail (/usr/local/addons/redmatic/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:307:47)
2020-11-01T11:08:27.774Z [err] gyp ERR! stack     at PythonFinder.runChecks (/usr/local/addons/redmatic/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:136:21)
2020-11-01T11:08:27.774Z [err] gyp ERR! stack
2020-11-01T11:08:27.774Z [err]      at PythonFinder.<anonymous> (/usr/local/addons/redmatic/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:179:16)
2020-11-01T11:08:27.774Z [err] gyp ERR!
2020-11-01T11:08:27.774Z [err]  stack     at PythonFinder.execFileCallback (/usr/local/addons/redmatic/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:271:16)
2020-11-01T11:08:27.774Z [err] gyp 
2020-11-01T11:08:27.775Z [err] ERR! stack     at exithandler (child_process.js:315:5)
2020-11-01T11:08:27.775Z [err] gyp
2020-11-01T11:08:27.775Z [err]  ERR! stack     at ChildProcess.errorhandler (child_process.js:327:5)
2020-11-01T11:08:27.775Z [err] gyp ERR! stack
2020-11-01T11:08:27.775Z [err]      at ChildProcess.emit (events.js:314:20)
2020-11-01T11:08:27.775Z [err] gyp ERR! 
2020-11-01T11:08:27.775Z [err] stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:274:12)
2020-11-01T11:08:27.775Z [err] gyp 
2020-11-01T11:08:27.775Z [err] ERR! stack     at onErrorNT (internal/child_process.js:464:16)
2020-11-01T11:08:27.775Z [err] gyp
2020-11-01T11:08:27.776Z [err]  ERR! stack     at processTicksAndRejections (internal/process/task_queues.js:80:21)
2020-11-01T11:08:27.777Z [err] gyp 
2020-11-01T11:08:27.777Z [err] ERR! System Linux 5.4.51
2020-11-01T11:08:27.777Z [err] gyp 
2020-11-01T11:08:27.777Z [err] ERR! command "/usr/local/addons/redmatic/bin/node" "/usr/local/addons/redmatic/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
2020-11-01T11:08:27.777Z [err] gyp
2020-11-01T11:08:27.777Z [err]  ERR! cwd /usr/local/addons/redmatic/var/node_modules/node-red-contrib-lgtv/node_modules/bufferutil
2020-11-01T11:08:27.778Z [err] gyp ERR! node -v
2020-11-01T11:08:27.778Z [err]  v14.13.1
2020-11-01T11:08:27.778Z [err] gyp ERR!
2020-11-01T11:08:27.778Z [err]  node-gyp -v v5.1.0
2020-11-01T11:08:27.778Z [err] gyp ERR! not ok
2020-11-01T11:08:27.778Z [err]  
2020-11-01T11:08:29.615Z [err] npm 
2020-11-01T11:08:29.616Z [err] WARN node-red-project@0.0.1 No repository field.
2020-11-01T11:08:29.658Z [err] npm WARN
2020-11-01T11:08:29.659Z [err]  node-red-project@0.0.1 No license field.
2020-11-01T11:08:29.659Z [err] 
2020-11-01T11:08:30.318Z [err] npm ERR! code ELIFECYCLE
2020-11-01T11:08:30.318Z [err] npm ERR! errno 1
2020-11-01T11:08:30.337Z [err] npm 
2020-11-01T11:08:30.337Z [err] ERR! bufferutil@4.0.2 install: `node-gyp-build`
2020-11-01T11:08:30.337Z [err] npm ERR! Exit status 1
2020-11-01T11:08:30.337Z [err] npm
2020-11-01T11:08:30.338Z [err]  ERR! 
2020-11-01T11:08:30.338Z [err] npm ERR!
2020-11-01T11:08:30.338Z [err]  Failed at the bufferutil@4.0.2 install script.
2020-11-01T11:08:30.338Z [err] npm ERR!
2020-11-01T11:08:30.338Z [err]  This is probably not a problem with npm. There is likely additional logging output above.
2020-11-01T11:08:30.379Z [err] 
2020-11-01T11:08:30.380Z [err] npm ERR! A complete log of this run can be found in:
2020-11-01T11:08:30.380Z [err] npm 
2020-11-01T11:08:30.380Z [err] ERR!     /usr/local/addons/redmatic/var/npm-cache/_logs/2020-11-01T11_08_30_352Z-debug.log
2020-11-01T11:08:30.411Z rc=1

**Comment by hobbyquaker** [comment]
Oh, da hab ich mich wohl getäuscht und node-red-contrib-lgtv will doch ein Binärmodul bauen. Ich nehms mit auf ins nächste Release.
