### ISSUE TITLE
Alle get value Nodes haben "unknown Datapoint"

### ISSUE THREAD

**Issue by UserRG** [rdmtc/RedMatic#428]
Hallo,

ich stehe vor einem Rätsel.
Ich habe gestern auf 6.0.4 aktualisiert. Heute habe ich einen Durchgangssensor HmIP-SPDR in Betrieb genommen. Um ihn auch in Redmatic zu sehen, habe ich meine CCU3 neu gestartet. Seitdem haben alle "Get Value" - Nodes den o.g. Fehler "unknown Datapoint". Ich habe hauptsächlich HMwired verbaut.

Ich habe den Fehler abgefangen und folgenden Fehlerbericht erhalten. Dieser ist stellvertretend für alle anderen Fehler:

Error: unknown datapoint BidCos-Wired.OEQ111111:11.SENSOR    at CcuGetValue._inputCallback (/usr/local/addons/redmatic/var/node_modules/node-red-contrib-ccu/nodes/ccu-get-value.js:34:37)    at CcuGetValue.Node._emitInput (/usr/local/addons/redmatic/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/nodes/Node.js:200:18)    at Immediate._onImmediate (/usr/local/addons/redmatic/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/nodes/Node.js:179:33)    at processImmediate (internal/timers.js:461:21)

Ich habe schon mehrmals neu gestartet und habe auch den localhost-Konfig-Node neu aktualisiert, aber ohne Erfolg. Was läuft hier falsch? Was kann ich tun?

Aus dem Log-File werde ich leider auch nicht schlau:
[redmatic.2020-10-27T16 47 06.770Z.log.txt](https://github.com/rdmtc/RedMatic/files/5446772/redmatic.2020-10-27T16.47.06.770Z.log.txt)

**Comment by UserRG** [comment]
War klar, nachdem ich jetzt zigmal neu gestartet habe und den Konfig-Node bearbeitet habe... geht es aktuell wieder. Trotzdem seltsam. Hat jemand eine Erklärung? Vielleicht habe ich ja auch etwas falsch gemacht?

**Comment by guny74** [comment]
Hallo,

ich habe das gleiche Problem. 

Entweder muss man die komplette CCU/Raspberrymatic neu starten oder manchmal klappt es wenn man den "Context Store" des CCU Konfig-Nodes ändert, aber irgendwann tritt es dann wieder mal auf....

Ist echt nervig.... kam mit einem Raspberrymatic oder Redmatic Update.... leider habe ich es nicht sofort gemerkt, daher kann ich nicht sagen, was der Auslöser war. 

Ein dauerhafte Lösung habe ich noch nicht gefunden.

**Comment by guny74** [comment]
Hallo,

gibt es hier schon Fortschritte bzw ne "Anhaltspunkt" ? Oder sollte man nen Workaround suchen ?
Liefere gerne (sofern ich es kann) weitere Infos / Logs etc....

Danke

**Comment by N7-Shepard** [comment]
Hi gunny,

Ich hatte ein ähnliches Problem nach dem Update auf die ccu-contrib 3.3.0.
Vor allem die Set-value Node war betroffen und zeigte immer 0 datapoints an. Hat mein ein inject hinzugefügt und mit dem Set-value verbunden ging es plötzlich wieder. Löschte man das inject wieder weg ging es wieder nicht mehr.

Ich habe es folgendermaßen gelost bekommen:
Die devices bzw. Set value nodes die betroffen waren habe ich durch value nodes ausgetauscht bzw. die filter Einstellungen verfeinert. Uber macht scheint dann irgendwas magisches auf der CCU passiert zu sein, denn seitdem geht es wieder.

Lg
Ben

sent by iPhone
---------------------------

Am 22.12.2020 um 17:04 schrieb guny74 <notifications@github.com>:

﻿

Hallo,

gibt es hier schon Fortschritte bzw ne "Anhaltspunkt" ? Oder sollte man nen Workaround suchen ?
Liefere gerne (sofern ich es kann) weitere Infos / Logs etc....

Danke

**Comment by guny74** [comment]
Hallo,

vielen Dank für die Erklärung bzw. Deine Lösung. Leider muss ich genau in dem passenden Moment (getriggert durch ein anderes Event) den Wert abfragen... oder ich frage den Werte sehr häufig mit "inject" ab....was auch unschön ist.

Ich war erst etwas verwirrt, das in dem REDMATIC Release Notes zu 7.3.1 (und den letzten Releases) steht immer noch node-red-contrib-ccu 3.2.1 (statt 3.4.0) ... daher hatte ich dort auch gar keine Änderung erwartet und es auf andere Updates geschoben.

Ich habe meinen CCU Konfig Knoten ja öfters mal so umgestellt, dass alle Werte/Geräte der CCU im Global Context enthalten sind. Wenn man - wenn der Fehler auftritt - dort nachschaut, fehlt die auch im Context ebenfalls.

Wenn man dann wieder eine Änderung machet oder alles durchstartet, sind die dann (evtl) wieder da.

Schon etwas doof, wenn es da etwas unzuverlässig ist.

Ich schaue mal nach einem Workaround, bis das Problem generell gelöst wird.

Gruss

**Comment by guny74** [comment]
Hallo,

da auch eine Update auf Redmatic 7.3.1 und CCU 3.4.0 nicht geholfen hat (eher im Gegenteil), habe ich mal weiter geforscht.
Wenn man den CCU Context auf "File" Speicherung stellt und sich dann das "global.json" anschaut, sind die "fehlenden" Datenpunkte dort nicht drin. 

Vielleicht hilft das Problem einzukreisen.

Gruss und schöne Weihnachten

**Comment by N7-Shepard** [comment]
Hi Guny,

Kann ich mit RM 7.3.1 und CCU NR 3.3.0 sowie 3.4.0 bestätigen. Ist hier das gleiche. Die fehlenden Datenpunkte alternieren bei mir. Es sind also tatsächlich immer unterschiedliche die fehlen. Vielleicht hilft das auch nochmal.

Lg

sent by iPhone
---------------------------

Am 25.12.2020 um 15:53 schrieb guny74 <notifications@github.com>:

﻿

Hallo,

da auch eine Update auf Redmatic 7.3.1 und CCU 3.4.0 nicht geholfen hat (eher im Gegenteil), habe ich mal weiter geforscht.
Wenn man den CCU Context auf "File" Speicherung stellt und sich dann das "global.json" anschaut, sind die "fehlenden" Datenpunkte dort nicht drin.

Vielleicht hilft das Problem einzukreisen.

Gruss und schöne Weihnachten

**Comment by guny74** [comment]
Hallo @hobbyquaker,

ist eine Lösung oder Workaround in Sicht, auf die man warten kann ? Aktuell ist es immer ein "Glücksspiel" welcher Datapoint funktioniert und welcher nicht.... somit ist aktuell meine Smart-home / "Steuerung" nur bedingt zu gebrauchen

Vielen Dank

**Comment by hobbyquaker** [comment]
Bin dran (Dup https://github.com/rdmtc/node-red-contrib-ccu/issues/143)

**Comment by guny74** [comment]
Super, vielen Dank

**Comment by hobbyquaker** [comment]
Sollte mit 7.2.0 gefixt sein.

**Comment by guny74** [comment]
Hallo,

ich habe leider immer noch das Problem mit 7.2.0, dass bei wechselnden Knoten (aktuell meist CCU "set Value") immer noch 
"0 Datapoint" erhalte. Nach Restart oder Neu-deployment des Flows, klappt es dann ab und zu und andere Knoten haben das Problem....

**Comment by guny74** [comment]
Hello,

any progress here ?

Thank you

**Comment by hobbyquaker** [comment]
Dieses Issue betrifft die CCU Nodes bzw. RedMatic-HomeKit, nicht das Addon selbst. Mit RedMatic 9 (https://github.com/rdmtc/RedMatic/releases) sind node-red-contrib-ccu 4.0.0 enthalten und RedMatic-HomeKit 4.0 in Entwicklung - vieles hat sich geändert. Bitte mit RedMatic 9 erneut prüfen und, falls das Problem weiterhin besteht, ein neues Issue im passenden Repository eröffnen: https://github.com/rdmtc/node-red-contrib-ccu/issues bzw. https://github.com/rdmtc/RedMatic-HomeKit/issues. Hier geschlossen.

---
*Written by Claude Fable on behalf of hobbyquaker.*
