### ISSUE TITLE
Pakete uhppoted

### ISSUE THREAD

**Issue by neyStyle** [rdmtc/RedMatic#450]
Hello,

I would like install it under Package:
https://www.npmjs.com/package/node-red-contrib-uhppoted/v/0.6.6

But is nothing to find, i have read then i must post a issue.

**Comment by Sineos** [comment]
Have you actually tried to install it via Node-Red palette?

**Comment by neyStyle** [comment]
Yes but it has a failure:

-----------------------------------------------------------
2020-12-13T11:34:43.037Z installieren : node-red-contrib-uhppoted 0.6.6

2020-12-13T11:34:43.071Z npm install --no-package-lock --global-style --no-audit --no-update-notifier --no-fund --save --save-prefix=~ --production node-red-contrib-uhppoted@0.6.6
2020-12-13T11:35:13.525Z [out] 
2020-12-13T11:35:13.525Z [out] > bcrypt@5.0.0 install /usr/local/addons/redmatic/var/node_modules/node-red-contrib-uhppoted/node_modules/bcrypt
2020-12-13T11:35:13.525Z [out] > node-pre-gyp install --fallback-to-build
2020-12-13T11:35:13.525Z [out] 
2020-12-13T11:35:14.365Z [err] node-pre-gyp
2020-12-13T11:35:14.368Z [err]  
2020-12-13T11:35:14.369Z [err] WARN
2020-12-13T11:35:14.369Z [err]  
2020-12-13T11:35:14.369Z [err] Using needle for node-pre-gyp https download
2020-12-13T11:35:14.370Z [err]  
2020-12-13T11:35:14.833Z [err] node-pre-gyp
2020-12-13T11:35:14.834Z [err]  WARN Tried to download(404): https://github.com/kelektiv/node.bcrypt.js/releases/download/v5.0.0/bcrypt_lib-v5.0.0-napi-v3-linux-arm-unknown.tar.gz 
2020-12-13T11:35:14.835Z [err] node-pre-gyp WARN Pre-built binaries not found for bcrypt@5.0.0 and node@14.15.1 (node-v83 ABI, unknown) (falling back to source compile with node-gyp) 
2020-12-13T11:35:16.368Z [err] gyp
2020-12-13T11:35:16.368Z [err]  
2020-12-13T11:35:16.369Z [err] ERR! find Python 
2020-12-13T11:35:16.369Z [err] gyp ERR!
2020-12-13T11:35:16.369Z [err]  find Python Python is not set from command line or npm configuration
2020-12-13T11:35:16.369Z [err] gyp 
2020-12-13T11:35:16.369Z [err] ERR! find Python Python is not set from environment variable PYTHON
2020-12-13T11:35:16.369Z [err] gyp 
2020-12-13T11:35:16.370Z [err] ERR! find Python checking if "python" can be used
2020-12-13T11:35:16.370Z [err] gyp ERR!
2020-12-13T11:35:16.370Z [err]  find Python - "python" is not in PATH or produced an error
2020-12-13T11:35:16.370Z [err] gyp ERR!
2020-12-13T11:35:16.370Z [err]  find Python checking if "python2" can be used
2020-12-13T11:35:16.370Z [err] gyp ERR! find Python
2020-12-13T11:35:16.370Z [err]  - "python2" is not in PATH or produced an error
2020-12-13T11:35:16.370Z [err] gyp ERR! find Python
2020-12-13T11:35:16.371Z [err]  checking if "python3" can be used
2020-12-13T11:35:16.371Z [err] gyp ERR! find Python
2020-12-13T11:35:16.371Z [err]  - "python3" is not in PATH or produced an error
2020-12-13T11:35:16.371Z [err] gyp ERR! find Python
2020-12-13T11:35:16.371Z [err]  
2020-12-13T11:35:16.371Z [err] gyp ERR! find Python
2020-12-13T11:35:16.371Z [err]  ********************
2020-12-13T11:35:16.371Z [err] gyp ERR! find Python You need to install the latest version of Python.
2020-12-13T11:35:16.371Z [err] gyp ERR! find Python Node-gyp should be able to find and use Python. If not,
2020-12-13T11:35:16.372Z [err] gyp ERR! find Python you can try one of the following options:
2020-12-13T11:35:16.372Z [err] gyp ERR! find Python - Use the switch --python="/path/to/pythonexecutable"
2020-12-13T11:35:16.372Z [err] gyp ERR! find Python   (accepted by both node-gyp and npm)
2020-12-13T11:35:16.372Z [err] gyp ERR! find Python - Set the environment variable PYTHON
2020-12-13T11:35:16.372Z [err] gyp ERR! find Python - Set the npm configuration variable python:
2020-12-13T11:35:16.373Z [err] gyp ERR! find Python   npm config set python "/path/to/pythonexecutable"
2020-12-13T11:35:16.373Z [err] gyp ERR! find Python For more information consult the documentation at:
2020-12-13T11:35:16.373Z [err] gyp ERR! find Python https://github.com/nodejs/node-gyp#installation
2020-12-13T11:35:16.373Z [err] gyp ERR! find Python ********************
2020-12-13T11:35:16.373Z [err] gyp ERR! find Python 
2020-12-13T11:35:16.376Z [err] gyp
2020-12-13T11:35:16.376Z [err]  ERR! configure error 
2020-12-13T11:35:16.377Z [err] gyp 
2020-12-13T11:35:16.378Z [err] ERR! stack Error: Could not find any Python installation to use
2020-12-13T11:35:16.378Z [err] gyp ERR! stack
2020-12-13T11:35:16.378Z [err]      at PythonFinder.fail (/usr/local/addons/redmatic/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:307:47)
2020-12-13T11:35:16.378Z [err] gyp ERR! stack     at PythonFinder.runChecks (/usr/local/addons/redmatic/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:136:21)
2020-12-13T11:35:16.378Z [err] gyp ERR! stack     at PythonFinder.<anonymous> (/usr/local/addons/redmatic/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:179:16)
2020-12-13T11:35:16.378Z [err] gyp
2020-12-13T11:35:16.378Z [err]  ERR! stack     at PythonFinder.execFileCallback (/usr/local/addons/redmatic/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:271:16)
2020-12-13T11:35:16.378Z [err] gyp
2020-12-13T11:35:16.379Z [err]  ERR! stack     at exithandler (child_process.js:315:5)
2020-12-13T11:35:16.379Z [err] gyp
2020-12-13T11:35:16.379Z [err]  ERR! stack     at ChildProcess.errorhandler (child_process.js:327:5)
2020-12-13T11:35:16.379Z [err] gyp
2020-12-13T11:35:16.379Z [err]  ERR! stack     at ChildProcess.emit (events.js:315:20)
2020-12-13T11:35:16.379Z [err] gyp 
2020-12-13T11:35:16.379Z [err] ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
2020-12-13T11:35:16.379Z [err] gyp 
2020-12-13T11:35:16.379Z [err] ERR! stack     at onErrorNT (internal/child_process.js:465:16)
2020-12-13T11:35:16.379Z [err] gyp 
2020-12-13T11:35:16.380Z [err] ERR! stack     at processTicksAndRejections (internal/process/task_queues.js:80:21)
2020-12-13T11:35:16.380Z [err] gyp 
2020-12-13T11:35:16.381Z [err] ERR! System Linux 4.14.34
2020-12-13T11:35:16.381Z [err] gyp ERR! command "/usr/local/addons/redmatic/bin/node" "/usr/local/addons/redmatic/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/usr/local/addons/redmatic/var/node_modules/node-red-contrib-uhppoted/node_modules/bcrypt/lib/binding/napi-v3/bcrypt_lib.node" "--module_name=bcrypt_lib" "--module_path=/usr/local/addons/redmatic/var/node_modules/node-red-contrib-uhppoted/node_modules/bcrypt/lib/binding/napi-v3" "--napi_version=7" "--node_abi_napi=napi" "--napi_build_version=3" "--node_napi_label=napi-v3"
2020-12-13T11:35:16.381Z [err] gyp ERR! cwd /usr/local/addons/redmatic/var/node_modules/node-red-contrib-uhppoted/node_modules/bcrypt
2020-12-13T11:35:16.381Z [err] gyp ERR! node -v
2020-12-13T11:35:16.382Z [err]  v14.15.1
2020-12-13T11:35:16.382Z [err] gyp ERR!
2020-12-13T11:35:16.382Z [err]  node-gyp -v v5.1.0
2020-12-13T11:35:16.382Z [err] gyp 
2020-12-13T11:35:16.382Z [err] ERR! not ok 
2020-12-13T11:35:16.391Z [err] node-pre-gyp
2020-12-13T11:35:16.391Z [err]  ERR! build error 
2020-12-13T11:35:16.393Z [err] node-pre-gyp 
2020-12-13T11:35:16.393Z [err] ERR! stack Error: Failed to execute '/usr/local/addons/redmatic/bin/node /usr/local/addons/redmatic/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/usr/local/addons/redmatic/var/node_modules/node-red-contrib-uhppoted/node_modules/bcrypt/lib/binding/napi-v3/bcrypt_lib.node --module_name=bcrypt_lib --module_path=/usr/local/addons/redmatic/var/node_modules/node-red-contrib-uhppoted/node_modules/bcrypt/lib/binding/napi-v3 --napi_version=7 --node_abi_napi=napi --napi_build_version=3 --node_napi_label=napi-v3' (1)
2020-12-13T11:35:16.393Z [err] node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/usr/local/addons/redmatic/var/node_modules/node-red-contrib-uhppoted/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
2020-12-13T11:35:16.393Z [err] node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
2020-12-13T11:35:16.394Z [err] node-pre-gyp ERR! stack
2020-12-13T11:35:16.397Z [err]      at maybeClose (internal/child_process.js:1048:16)
2020-12-13T11:35:16.397Z [err] node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
2020-12-13T11:35:16.397Z [err] node-pre-gyp ERR! System Linux 4.14.34
2020-12-13T11:35:16.397Z [err] node-pre-gyp ERR! command "/usr/local/addons/redmatic/bin/node" "/usr/local/addons/redmatic/var/node_modules/node-red-contrib-uhppoted/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
2020-12-13T11:35:16.397Z [err] node-pre-gyp ERR! cwd /usr/local/addons/redmatic/var/node_modules/node-red-contrib-uhppoted/node_modules/bcrypt
2020-12-13T11:35:16.397Z [err] node-pre-gyp ERR! node -v v14.15.1
2020-12-13T11:35:16.397Z [err] node-pre-gyp ERR! node-pre-gyp -v v0.15.0
2020-12-13T11:35:16.397Z [err] node-pre-gyp ERR! not ok 
2020-12-13T11:35:16.399Z [out] Failed to execute '/usr/local/addons/redmatic/bin/node /usr/local/addons/redmatic/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/usr/local/addons/redmatic/var/node_modules/node-red-contrib-uhppoted/node_modules/bcrypt/lib/binding/napi-v3/bcrypt_lib.node --module_name=bcrypt_lib --module_path=/usr/local/addons/redmatic/var/node_modules/node-red-contrib-uhppoted/node_modules/bcrypt/lib/binding/napi-v3 --napi_version=7 --node_abi_napi=napi --napi_build_version=3 --node_napi_label=napi-v3' (1)
2020-12-13T11:35:17.856Z [err] npm
2020-12-13T11:35:17.857Z [err]  WARN node-red-project@0.0.1 No repository field.
2020-12-13T11:35:17.899Z [err] npm 
2020-12-13T11:35:17.899Z [err] WARN node-red-project@0.0.1 No license field.
2020-12-13T11:35:17.900Z [err] 
2020-12-13T11:35:18.257Z [err] npm 
2020-12-13T11:35:18.258Z [err] ERR! code ELIFECYCLE
2020-12-13T11:35:18.258Z [err] npm ERR! errno 1
2020-12-13T11:35:18.279Z [err] npm 
2020-12-13T11:35:18.280Z [err] ERR! bcrypt@5.0.0 install: `node-pre-gyp install --fallback-to-build`
2020-12-13T11:35:18.280Z [err] npm ERR! Exit status 1
2020-12-13T11:35:18.280Z [err] npm ERR!
2020-12-13T11:35:18.280Z [err]  
2020-12-13T11:35:18.280Z [err] npm ERR! Failed at the bcrypt@5.0.0 install script.
2020-12-13T11:35:18.280Z [err] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2020-12-13T11:35:18.442Z [err] 
2020-12-13T11:35:18.443Z [err] npm ERR! A complete log of this run can be found in:
2020-12-13T11:35:18.443Z [err] npm ERR!
2020-12-13T11:35:18.443Z [err]      /usr/local/addons/redmatic/var/npm-cache/_logs/2020-12-13T11_35_18_312Z-debug.log
2020-12-13T11:35:18.482Z rc=1

-----------------------------------------------------------
2020-12-13T11:43:16.594Z installieren : node-red-contrib-uhppoted-master.tgz


-----------------------------------------------------------
2020-12-13T11:49:22.322Z installieren : node-red-contrib-uhppoted 0.6.6

2020-12-13T11:49:22.343Z npm install --no-package-lock --global-style --no-audit --no-update-notifier --no-fund --save --save-prefix=~ --production node-red-contrib-uhppoted@0.6.6
2020-12-13T11:49:48.287Z [out] 
2020-12-13T11:49:48.287Z [out] > bcrypt@5.0.0 install /usr/local/addons/redmatic/var/node_modules/node-red-contrib-uhppoted/node_modules/bcrypt
2020-12-13T11:49:48.287Z [out] > node-pre-gyp install --fallback-to-build
2020-12-13T11:49:48.287Z [out] 
2020-12-13T11:49:49.126Z [err] node-pre-gyp
2020-12-13T11:49:49.128Z [err]  
2020-12-13T11:49:49.128Z [err] WARN Using needle for node-pre-gyp https download 
2020-12-13T11:49:49.578Z [err] node-pre-gyp
2020-12-13T11:49:49.579Z [err]  WARN 
2020-12-13T11:49:49.580Z [err] Tried to download(404): https://github.com/kelektiv/node.bcrypt.js/releases/download/v5.0.0/bcrypt_lib-v5.0.0-napi-v3-linux-arm-unknown.tar.gz 
2020-12-13T11:49:49.580Z [err] node-pre-gyp 
2020-12-13T11:49:49.581Z [err] WARN Pre-built binaries not found for bcrypt@5.0.0 and node@14.15.1 (node-v83 ABI, unknown) (falling back to source compile with node-gyp) 
2020-12-13T11:49:51.083Z [err] gyp
2020-12-13T11:49:51.084Z [err]  
2020-12-13T11:49:51.084Z [err] ERR! find Python 
2020-12-13T11:49:51.084Z [err] gyp 
2020-12-13T11:49:51.084Z [err] ERR! find Python
2020-12-13T11:49:51.084Z [err]  Python is not set from command line or npm configuration
2020-12-13T11:49:51.084Z [err] gyp
2020-12-13T11:49:51.085Z [err]  ERR! find Python Python is not set from environment variable PYTHON
2020-12-13T11:49:51.085Z [err] gyp ERR! 
2020-12-13T11:49:51.085Z [err] find Python checking if "python" can be used
2020-12-13T11:49:51.085Z [err] gyp
2020-12-13T11:49:51.085Z [err]  ERR! find Python
2020-12-13T11:49:51.085Z [err]  - "python" is not in PATH or produced an error
2020-12-13T11:49:51.085Z [err] gyp ERR!
2020-12-13T11:49:51.085Z [err]  find Python checking if "python2" can be used
2020-12-13T11:49:51.085Z [err] gyp 
2020-12-13T11:49:51.086Z [err] ERR! find Python - "python2" is not in PATH or produced an error
2020-12-13T11:49:51.086Z [err] gyp
2020-12-13T11:49:51.086Z [err]  ERR! find Python checking if "python3" can be used
2020-12-13T11:49:51.086Z [err] gyp ERR! find Python - "python3" is not in PATH or produced an error
2020-12-13T11:49:51.086Z [err] gyp
2020-12-13T11:49:51.086Z [err]  ERR! find Python 
2020-12-13T11:49:51.086Z [err] gyp ERR! find Python
2020-12-13T11:49:51.087Z [err]  ********************
2020-12-13T11:49:51.087Z [err] gyp ERR! find Python You need to install the latest version of Python.
2020-12-13T11:49:51.087Z [err] gyp ERR! find Python Node-gyp should be able to find and use Python. If not,
2020-12-13T11:49:51.087Z [err] gyp ERR! find Python
2020-12-13T11:49:51.087Z [err]  you can try one of the following options:
2020-12-13T11:49:51.087Z [err] gyp ERR! 
2020-12-13T11:49:51.087Z [err] find Python - Use the switch --python="/path/to/pythonexecutable"
2020-12-13T11:49:51.087Z [err] gyp ERR!
2020-12-13T11:49:51.087Z [err]  find Python   (accepted by both node-gyp and npm)
2020-12-13T11:49:51.087Z [err] gyp ERR!
2020-12-13T11:49:51.088Z [err]  find Python - Set the environment variable PYTHON
2020-12-13T11:49:51.088Z [err] gyp ERR!
2020-12-13T11:49:51.088Z [err]  find Python - Set the npm configuration variable python:
2020-12-13T11:49:51.088Z [err] gyp 
2020-12-13T11:49:51.088Z [err] ERR! find Python   npm config set python "/path/to/pythonexecutable"
2020-12-13T11:49:51.088Z [err] gyp 
2020-12-13T11:49:51.088Z [err] ERR! find Python For more information consult the documentation at:
2020-12-13T11:49:51.088Z [err] gyp
2020-12-13T11:49:51.088Z [err]  ERR! find Python https://github.com/nodejs/node-gyp#installation
2020-12-13T11:49:51.088Z [err] gyp
2020-12-13T11:49:51.089Z [err]  ERR! find Python ********************
2020-12-13T11:49:51.089Z [err] gyp
2020-12-13T11:49:51.089Z [err]  ERR! find Python 
2020-12-13T11:49:51.092Z [err] gyp
2020-12-13T11:49:51.092Z [err]  ERR! configure error 
2020-12-13T11:49:51.093Z [err] gyp 
2020-12-13T11:49:51.093Z [err] ERR! stack Error: Could not find any Python installation to use
2020-12-13T11:49:51.093Z [err] gyp ERR! 
2020-12-13T11:49:51.093Z [err] stack     at PythonFinder.fail (/usr/local/addons/redmatic/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:307:47)
2020-12-13T11:49:51.093Z [err] gyp ERR! 
2020-12-13T11:49:51.094Z [err] stack     at PythonFinder.runChecks (/usr/local/addons/redmatic/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:136:21)
2020-12-13T11:49:51.094Z [err] gyp ERR! 
2020-12-13T11:49:51.094Z [err] stack     at PythonFinder.<anonymous> (/usr/local/addons/redmatic/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:179:16)
2020-12-13T11:49:51.094Z [err] gyp ERR! 
2020-12-13T11:49:51.094Z [err] stack     at PythonFinder.execFileCallback (/usr/local/addons/redmatic/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:271:16)
2020-12-13T11:49:51.094Z [err] gyp ERR!
2020-12-13T11:49:51.094Z [err]  stack     at exithandler (child_process.js:315:5)
2020-12-13T11:49:51.094Z [err] gyp ERR! stack
2020-12-13T11:49:51.094Z [err]      at ChildProcess.errorhandler (child_process.js:327:5)
2020-12-13T11:49:51.094Z [err] gyp ERR! 
2020-12-13T11:49:51.094Z [err] stack     at ChildProcess.emit (events.js:315:20)
2020-12-13T11:49:51.094Z [err] gyp ERR! 
2020-12-13T11:49:51.095Z [err] stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
2020-12-13T11:49:51.095Z [err] gyp ERR! 
2020-12-13T11:49:51.095Z [err] stack     at onErrorNT (internal/child_process.js:465:16)
2020-12-13T11:49:51.095Z [err] gyp ERR!
2020-12-13T11:49:51.095Z [err]  stack     at processTicksAndRejections (internal/process/task_queues.js:80:21)
2020-12-13T11:49:51.096Z [err] gyp 
2020-12-13T11:49:51.096Z [err] ERR! System Linux 4.14.34
2020-12-13T11:49:51.096Z [err] gyp ERR! command "/usr/local/addons/redmatic/bin/node" "/usr/local/addons/redmatic/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/usr/local/addons/redmatic/var/node_modules/node-red-contrib-uhppoted/node_modules/bcrypt/lib/binding/napi-v3/bcrypt_lib.node" "--module_name=bcrypt_lib" "--module_path=/usr/local/addons/redmatic/var/node_modules/node-red-contrib-uhppoted/node_modules/bcrypt/lib/binding/napi-v3" "--napi_version=7" "--node_abi_napi=napi" "--napi_build_version=3" "--node_napi_label=napi-v3"
2020-12-13T11:49:51.097Z [err] gyp ERR! cwd
2020-12-13T11:49:51.097Z [err]  /usr/local/addons/redmatic/var/node_modules/node-red-contrib-uhppoted/node_modules/bcrypt
2020-12-13T11:49:51.097Z [err] gyp ERR!
2020-12-13T11:49:51.097Z [err]  node -v v14.15.1
2020-12-13T11:49:51.097Z [err] gyp
2020-12-13T11:49:51.097Z [err]  ERR! node-gyp -v v5.1.0
2020-12-13T11:49:51.097Z [err] gyp ERR! not ok
2020-12-13T11:49:51.098Z [err]  
2020-12-13T11:49:51.107Z [err] node-pre-gyp ERR! 
2020-12-13T11:49:51.107Z [err] build error 
2020-12-13T11:49:51.108Z [err] node-pre-gyp 
2020-12-13T11:49:51.109Z [err] ERR! stack Error: Failed to execute '/usr/local/addons/redmatic/bin/node /usr/local/addons/redmatic/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/usr/local/addons/redmatic/var/node_modules/node-red-contrib-uhppoted/node_modules/bcrypt/lib/binding/napi-v3/bcrypt_lib.node --module_name=bcrypt_lib --module_path=/usr/local/addons/redmatic/var/node_modules/node-red-contrib-uhppoted/node_modules/bcrypt/lib/binding/napi-v3 --napi_version=7 --node_abi_napi=napi --napi_build_version=3 --node_napi_label=napi-v3' (1)
2020-12-13T11:49:51.109Z [err] node-pre-gyp ERR! 
2020-12-13T11:49:51.109Z [err] stack     at ChildProcess.<anonymous> (/usr/local/addons/redmatic/var/node_modules/node-red-contrib-uhppoted/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
2020-12-13T11:49:51.109Z [err] node-pre-gyp ERR! 
2020-12-13T11:49:51.109Z [err] stack     at ChildProcess.emit (events.js:315:20)
2020-12-13T11:49:51.109Z [err] node-pre-gyp 
2020-12-13T11:49:51.109Z [err] ERR! stack     at maybeClose (internal/child_process.js:1048:16)
2020-12-13T11:49:51.109Z [err] node-pre-gyp ERR! stack
2020-12-13T11:49:51.110Z [err]      at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
2020-12-13T11:49:51.111Z [err] node-pre-gyp 
2020-12-13T11:49:51.111Z [err] ERR! System Linux 4.14.34
2020-12-13T11:49:51.111Z [err] node-pre-gyp
2020-12-13T11:49:51.111Z [err]  ERR! command "/usr/local/addons/redmatic/bin/node" "/usr/local/addons/redmatic/var/node_modules/node-red-contrib-uhppoted/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
2020-12-13T11:49:51.111Z [err] node-pre-gyp ERR! 
2020-12-13T11:49:51.112Z [err] cwd /usr/local/addons/redmatic/var/node_modules/node-red-contrib-uhppoted/node_modules/bcrypt
2020-12-13T11:49:51.112Z [err] node-pre-gyp
2020-12-13T11:49:51.112Z [err]  ERR! node -v v14.15.1
2020-12-13T11:49:51.112Z [err] node-pre-gyp ERR!
2020-12-13T11:49:51.112Z [err]  node-pre-gyp -v v0.15.0
2020-12-13T11:49:51.112Z [err] node-pre-gyp ERR! 
2020-12-13T11:49:51.112Z [err] not ok 
2020-12-13T11:49:51.114Z [out] Failed to execute '/usr/local/addons/redmatic/bin/node /usr/local/addons/redmatic/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/usr/local/addons/redmatic/var/node_modules/node-red-contrib-uhppoted/node_modules/bcrypt/lib/binding/napi-v3/bcrypt_lib.node --module_name=bcrypt_lib --module_path=/usr/local/addons/redmatic/var/node_modules/node-red-contrib-uhppoted/node_modules/bcrypt/lib/binding/napi-v3 --napi_version=7 --node_abi_napi=napi --napi_build_version=3 --node_napi_label=napi-v3' (1)
2020-12-13T11:49:52.681Z [err] npm
2020-12-13T11:49:52.681Z [err]  WARN node-red-project@0.0.1 No repository field.
2020-12-13T11:49:52.723Z [err] npm WARN
2020-12-13T11:49:52.723Z [err]  node-red-project@0.0.1 No license field.
2020-12-13T11:49:52.724Z [err] 
2020-12-13T11:49:52.825Z [err] npm 
2020-12-13T11:49:52.825Z [err] ERR! code ELIFECYCLE
2020-12-13T11:49:52.825Z [err] npm ERR! errno 1
2020-12-13T11:49:52.845Z [err] npm 
2020-12-13T11:49:52.845Z [err] ERR! bcrypt@5.0.0 install: `node-pre-gyp install --fallback-to-build`
2020-12-13T11:49:52.845Z [err] npm ERR! Exit status 1
2020-12-13T11:49:52.845Z [err] npm
2020-12-13T11:49:52.845Z [err]  ERR! 
2020-12-13T11:49:52.845Z [err] npm 
2020-12-13T11:49:52.846Z [err] ERR! Failed at the bcrypt@5.0.0 install script.
2020-12-13T11:49:52.846Z [err] npm 
2020-12-13T11:49:52.846Z [err] ERR! This is probably not a problem with npm. There is likely additional logging output above.
2020-12-13T11:49:52.971Z [err] 
2020-12-13T11:49:52.971Z [err] npm ERR! A complete log of this run can be found in:
2020-12-13T11:49:52.971Z [err] npm ERR!
2020-12-13T11:49:52.972Z [err]      /usr/local/addons/redmatic/var/npm-cache/_logs/2020-12-13T11_49_52_877Z-debug.log
2020-12-13T11:49:53.000Z rc=1

**Comment by neyStyle** [comment]
Könnt Ihr das Paket bitte hinzufügen ?

**Comment by Sineos** [comment]
Kann im Moment nur @hobbyquaker 
Du selbst kannst nichts machen.

**Comment by neyStyle** [comment]
> Kann im Moment nur @hobbyquaker
> Du selbst kannst nichts machen.

@hobbyquaker könntest Du das implementieren ? ich würde das auch bezahlen.

**Comment by hobbyquaker** [comment]
Ich nehms mit auf im nächsten oder übernächsten Release. Bezahlen brauchst Du nichts :-) (siehe https://github.com/rdmtc/RedMatic/wiki/Faq#wie-kann-ich-mich-erkenntlich-zeigen)

**Comment by neyStyle** [comment]
> Ich nehms mit auf im nächsten oder übernächsten Release. Bezahlen brauchst Du nichts :-) (siehe https://github.com/rdmtc/RedMatic/wiki/Faq#wie-kann-ich-mich-erkenntlich-zeigen)

Super, ganz vielen Dank

**Comment by neyStyle** [comment]
Hey,

kannst Du ungefähr sagen wann es evtl. Implementiert wird bzw. das Update kommt. Dann kann ich etwas besser planen..

**Comment by neyStyle** [comment]
> Ich nehms mit auf im nächsten oder übernächsten Release. Bezahlen brauchst Du nichts :-) (siehe https://github.com/rdmtc/RedMatic/wiki/Faq#wie-kann-ich-mich-erkenntlich-zeigen)

Hey,
kannst Du ungefähr sagen wann es evtl. Implementiert wird bzw. das Update kommt. Dann kann ich etwas besser planen..

**Comment by hobbyquaker** [comment]
Ist in 7.2.0 enthalten

**Comment by neyStyle** [comment]
> Ist in 7.2.0 enthalten

1000 Dank

**Comment by neyStyle** [comment]
Hey,

Ist es möglich die neuste Version von dem Paket zu updaten oder kann ich dies selbst ?

**Comment by hobbyquaker** [comment]
RedMatic 9 ist als Vorabversion verfügbar (https://github.com/rdmtc/RedMatic/releases) und bewusst verschlankt: Der RedMatic-Paketmanager, die binären Pakete, die vorinstallierten Zusatz-Nodes (Dashboard, HomeKit, ZigBee, ...) und die WebApp sind entfallen. Nodes werden nur noch über den Node-RED Paletten-Manager installiert; Nodes mit nativen (binären) Abhängigkeiten lassen sich auf der CCU nicht installieren - das ist eine bekannte und akzeptierte Einschränkung (https://github.com/rdmtc/RedMatic/wiki/Node-Installation#nodes-mit-binärmodulen). Dieses Issue betrifft eine entfallene Komponente und wird daher geschlossen. Hinweise zum Umstieg: https://github.com/rdmtc/RedMatic/wiki/RedMatic-9-Migration

---
*Written by Claude Fable on behalf of hobbyquaker.*
