### ISSUE TITLE
[Feature-Request] - node-contrib-signal-client

### ISSUE THREAD

**Issue by IT-VBFK** [rdmtc/RedMatic#472]
Hallo,

Durch gerade extremen Umschwung in der "Messenger-Szene" und das Abweichen zu WhatsApp-Alternativen (in diesem Falle Signal), wäre es super wenn sich die Signal-Nodes installieren und nutzen lassen könnten.

Das ist zurzeit leider (noch) nicht der Fall, die Installation scheitert mit folgendem Error-Log:

2021-01-17T11:19:55.086Z installieren : nodered-contrib-signal-client 2.1.0

2021-01-17T11:19:55.272Z npm install --no-package-lock --global-style --no-audit --no-update-notifier --no-fund --save --save-prefix=~ --production nodered-contrib-signal-client@2.1.0
2021-01-17T11:20:15.971Z [err] npm
2021-01-17T11:20:15.972Z [err]  WARN deprecated core-js@2.6.12: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
2021-01-17T11:20:55.976Z [out] 
2021-01-17T11:20:55.976Z [out] > bufferutil@4.0.3 install /usr/local/addons/redmatic/var/node_modules/nodered-contrib-signal-client/node_modules/bufferutil
2021-01-17T11:20:55.976Z [out] > node-gyp-build
2021-01-17T11:20:55.976Z [out] 
2021-01-17T11:20:56.750Z [out] 
2021-01-17T11:20:56.750Z [out] > utf-8-validate@5.0.4 install /usr/local/addons/redmatic/var/node_modules/nodered-contrib-signal-client/node_modules/utf-8-validate
2021-01-17T11:20:56.750Z [out] > node-gyp-build
2021-01-17T11:20:56.750Z [out] 
2021-01-17T11:20:57.478Z [out] 
2021-01-17T11:20:57.478Z [out] > node-webcrypto-ossl@1.0.49 install /usr/local/addons/redmatic/var/node_modules/nodered-contrib-signal-client/node_modules/node-webcrypto-ossl
2021-01-17T11:20:57.478Z [out] > node-gyp rebuild
2021-01-17T11:20:57.478Z [out] 
2021-01-17T11:20:58.276Z [err] gyp
2021-01-17T11:20:58.277Z [err]  
2021-01-17T11:20:58.277Z [err] ERR! find Python 
2021-01-17T11:20:58.277Z [err] gyp 
2021-01-17T11:20:58.278Z [err] ERR! find Python
2021-01-17T11:20:58.278Z [err]  Python is not set from command line or npm configuration
2021-01-17T11:20:58.278Z [err] gyp
2021-01-17T11:20:58.278Z [err]  ERR! 
2021-01-17T11:20:58.278Z [err] find Python Python is not set from environment variable PYTHON
2021-01-17T11:20:58.278Z [err] gyp ERR!
2021-01-17T11:20:58.278Z [err]  find Python
2021-01-17T11:20:58.278Z [err]  checking if "python" can be used
2021-01-17T11:20:58.278Z [err] gyp
2021-01-17T11:20:58.278Z [err]  ERR! 
2021-01-17T11:20:58.278Z [err] find Python - "python" is not in PATH or produced an error
2021-01-17T11:20:58.278Z [err] gyp
2021-01-17T11:20:58.279Z [err]  ERR! 
2021-01-17T11:20:58.279Z [err] find Python checking if "python2" can be used
2021-01-17T11:20:58.279Z [err] gyp
2021-01-17T11:20:58.279Z [err]  
2021-01-17T11:20:58.279Z [err] ERR!
2021-01-17T11:20:58.279Z [err]  find Python - "python2" is not in PATH or produced an error
2021-01-17T11:20:58.279Z [err] gyp 
2021-01-17T11:20:58.280Z [err] ERR! find Python
2021-01-17T11:20:58.280Z [err]  checking if "python3" can be used
2021-01-17T11:20:58.280Z [err] gyp 
2021-01-17T11:20:58.280Z [err] ERR! find Python - "python3" is not in PATH or produced an error
2021-01-17T11:20:58.280Z [err] gyp ERR! find Python 
2021-01-17T11:20:58.280Z [err] gyp ERR! 
2021-01-17T11:20:58.280Z [err] find Python **********************************************************
2021-01-17T11:20:58.280Z [err] gyp ERR!
2021-01-17T11:20:58.281Z [err]  find Python You need to install the latest version of Python.
2021-01-17T11:20:58.281Z [err] gyp 
2021-01-17T11:20:58.281Z [err] ERR! find Python
2021-01-17T11:20:58.281Z [err]  Node-gyp should be able to find and use Python. If not,
2021-01-17T11:20:58.281Z [err] gyp ERR!
2021-01-17T11:20:58.281Z [err]  find Python you can try one of the following options:
2021-01-17T11:20:58.281Z [err] gyp
2021-01-17T11:20:58.281Z [err]  ERR!
2021-01-17T11:20:58.281Z [err]  find Python - Use the switch --python="/path/to/pythonexecutable"
2021-01-17T11:20:58.281Z [err] gyp ERR! 
2021-01-17T11:20:58.281Z [err] find Python   (accepted by both node-gyp and npm)
2021-01-17T11:20:58.281Z [err] gyp
2021-01-17T11:20:58.282Z [err]  ERR! find Python
2021-01-17T11:20:58.282Z [err]  - Set the environment variable PYTHON
2021-01-17T11:20:58.282Z [err] gyp 
2021-01-17T11:20:58.282Z [err] ERR! find Python - Set the npm configuration variable python:
2021-01-17T11:20:58.282Z [err] gyp ERR! 
2021-01-17T11:20:58.282Z [err] find Python   npm config set python "/path/to/pythonexecutable"
2021-01-17T11:20:58.282Z [err] gyp
2021-01-17T11:20:58.282Z [err]  ERR! find Python
2021-01-17T11:20:58.282Z [err]  For more information consult the documentation at:
2021-01-17T11:20:58.282Z [err] gyp 
2021-01-17T11:20:58.282Z [err] ERR! find Python https://github.com/nodejs/node-gyp#installation
2021-01-17T11:20:58.282Z [err] gyp ERR!
2021-01-17T11:20:58.283Z [err]  find Python **********************************************************
2021-01-17T11:20:58.283Z [err] gyp
2021-01-17T11:20:58.283Z [err]  ERR! find Python
2021-01-17T11:20:58.283Z [err]  
2021-01-17T11:20:58.286Z [err] gyp
2021-01-17T11:20:58.286Z [err]  ERR! configure error 
2021-01-17T11:20:58.287Z [err] gyp 
2021-01-17T11:20:58.288Z [err] ERR! stack Error: Could not find any Python installation to use
2021-01-17T11:20:58.288Z [err] gyp ERR!
2021-01-17T11:20:58.288Z [err]  stack     at PythonFinder.fail (/usr/local/addons/redmatic/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:307:47)
2021-01-17T11:20:58.288Z [err] gyp 
2021-01-17T11:20:58.288Z [err] ERR! stack
2021-01-17T11:20:58.288Z [err]      at PythonFinder.runChecks (/usr/local/addons/redmatic/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:136:21)
2021-01-17T11:20:58.288Z [err] gyp ERR!
2021-01-17T11:20:58.288Z [err]  stack     at PythonFinder.<anonymous> (/usr/local/addons/redmatic/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:179:16)
2021-01-17T11:20:58.288Z [err] gyp
2021-01-17T11:20:58.288Z [err]  ERR! stack
2021-01-17T11:20:58.288Z [err]      at PythonFinder.execFileCallback (/usr/local/addons/redmatic/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:271:16)
2021-01-17T11:20:58.288Z [err] gyp 
2021-01-17T11:20:58.288Z [err] ERR! stack     at exithandler (child_process.js:315:5)
2021-01-17T11:20:58.289Z [err] gyp ERR! 
2021-01-17T11:20:58.289Z [err] stack     at ChildProcess.errorhandler (child_process.js:327:5)
2021-01-17T11:20:58.289Z [err] gyp 
2021-01-17T11:20:58.289Z [err] ERR! stack
2021-01-17T11:20:58.289Z [err]      at ChildProcess.emit (events.js:315:20)
2021-01-17T11:20:58.289Z [err] gyp 
2021-01-17T11:20:58.289Z [err] ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
2021-01-17T11:20:58.289Z [err] gyp ERR! 
2021-01-17T11:20:58.289Z [err] stack     at onErrorNT (internal/child_process.js:465:16)
2021-01-17T11:20:58.289Z [err] gyp
2021-01-17T11:20:58.289Z [err]  ERR! stack     at processTicksAndRejections (internal/process/task_queues.js:80:21)
2021-01-17T11:20:58.291Z [err] gyp 
2021-01-17T11:20:58.291Z [err] ERR! System Linux 5.4.83
2021-01-17T11:20:58.291Z [err] gyp
2021-01-17T11:20:58.291Z [err]  ERR! command "/usr/local/addons/redmatic/bin/node" "/usr/local/addons/redmatic/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
2021-01-17T11:20:58.291Z [err] gyp 
2021-01-17T11:20:58.291Z [err] ERR! cwd /usr/local/addons/redmatic/var/node_modules/nodered-contrib-signal-client/node_modules/node-webcrypto-ossl
2021-01-17T11:20:58.291Z [err] gyp 
2021-01-17T11:20:58.291Z [err] ERR! node -v
2021-01-17T11:20:58.291Z [err]  v14.15.1
2021-01-17T11:20:58.291Z [err] gyp
2021-01-17T11:20:58.292Z [err]  ERR! node-gyp -v
2021-01-17T11:20:58.292Z [err]  v5.1.0
2021-01-17T11:20:58.292Z [err] gyp
2021-01-17T11:20:58.292Z [err]  ERR! not ok
2021-01-17T11:20:58.292Z [err]  
2021-01-17T11:21:02.918Z [err] npm
2021-01-17T11:21:02.918Z [err]  
2021-01-17T11:21:02.919Z [err] WARN
2021-01-17T11:21:02.919Z [err]  node-red-project@0.0.1 No repository field.
2021-01-17T11:21:02.959Z [err] npm
2021-01-17T11:21:02.959Z [err]  
2021-01-17T11:21:02.959Z [err] WARN
2021-01-17T11:21:02.960Z [err]  node-red-project@0.0.1 No license field.
2021-01-17T11:21:02.961Z [err] 
2021-01-17T11:21:04.633Z [err] npm 
2021-01-17T11:21:04.634Z [err] ERR! code ELIFECYCLE
2021-01-17T11:21:04.634Z [err] npm 
2021-01-17T11:21:04.634Z [err] ERR! errno 1
2021-01-17T11:21:04.651Z [err] npm ERR!
2021-01-17T11:21:04.651Z [err]  node-webcrypto-ossl@1.0.49 install: `node-gyp rebuild`
2021-01-17T11:21:04.651Z [err] npm ERR! Exit status 1
2021-01-17T11:21:04.651Z [err] npm
2021-01-17T11:21:04.652Z [err]  ERR! 
2021-01-17T11:21:04.652Z [err] npm ERR!
2021-01-17T11:21:04.652Z [err]  Failed at the node-webcrypto-ossl@1.0.49 install script.
2021-01-17T11:21:04.652Z [err] npm 
2021-01-17T11:21:04.652Z [err] ERR! This is probably not a problem with npm. There is likely additional logging output above.
2021-01-17T11:21:04.780Z [err] 
2021-01-17T11:21:04.780Z [err] npm ERR! A complete log of this run can be found in:
2021-01-17T11:21:04.780Z [err] npm 
2021-01-17T11:21:04.781Z [err] ERR!     /usr/local/addons/redmatic/var/npm-cache/_logs/2021-01-17T11_21_04_731Z-debug.log
2021-01-17T11:21:04.835Z rc=1

**Comment by bubi1311** [comment]
Es wäre echt prima, wenn das mit RaspberryMatic bzw. RedMatic funktionieren würde. Ich bin von FHEM gewechselt und dort konnte ich eine Signal-Anbindung verwenden.
@hobbyquaker Danke für die tolle Entwicklung bisher!

**Comment by hobbyquaker** [comment]
Ist in 7.2.0 enthalten.

**Comment by IT-VBFK** [comment]
danke
das war ja fix 👍🏻

**Comment by IT-VBFK** [comment]
Leider muss ich revidieren... signal lässt sich immer noch nicht installieren.

Fehler wie oben

**Comment by hobbyquaker** [comment]
https://github.com/rdmtc/RedMatic/wiki/Node-Installation#nodes-mit-bin%C3%A4rmodulen beachtet?

**Comment by IT-VBFK** [comment]
Ahh jetzt versteh ich, warum man so ungerne eine Doku schreibt... es gibt immer Honks die diese nicht lesen 🤦🏻‍♂️

Danke nun funktionierts 👍🏻

**Comment by joachimmarder** [comment]
Hat den Signal Client jemand von euch zum Laufen bekommen? Ich scheitere leider an dem Captcha nach der Antwort "402 Payment Required". Die Seite https://signalcaptchas.org/registration/generate.html bleibt bei mir im Firefox wie im Edge Chromium leer.

**Comment by IT-VBFK** [comment]
Ich habs mit Opera gemacht, da hats funktioniert

**Comment by Sineos** [comment]
1. Eine `request-SMS` Node anlegen
2. In der `request-SMS` den Account anlegen
   * Telefonnummer eingeben
   * Name vergeben
   * Tolles Passwort vergeben
   * Live Server an-ticken
 3.  https://signalcaptchas.org/registration/generate.html aufrufen
     * Eine leere Seite erscheint
     * Developer tools aufrufen (Typischerweise F12)
     * Den "Captcha Code" kopieren
![grafik](https://user-images.githubusercontent.com/4459312/111133153-79bf0c00-857a-11eb-8cbe-d88941f6952d.png)
  4. "Captcha Code" in die `request-SMS` kopieren
  5. Registrierung auslösen
  6. Freuen

**Comment by joachimmarder** [comment]
> Eine leere Seite erscheint

Achso, die leere Seite ist der erwartete Zustand! Ich dachte, man müsste auf der Captcha-Seite zunächst ein Captcha lösen.  Vielen Dank für die Klarstellung.

**Comment by juppjuppsen** [comment]
Sehe ich es richtig, daß ich mir mit nur einer Telefonnummer nicht selber Nachrichten an mein Mobiltelefon senden kann?
Eine Registrierung des NodeRed Signal Clients führt zu einer De-Registrierung der Signal App meines Mobiltelefons und vice versa. Ich benötige also eine dedizierte Telefonnummer für den Client, korrekt?

**Comment by Sineos** [comment]
> Sehe ich es richtig, daß ich mir mit nur einer Telefonnummer nicht selber Nachrichten an mein Mobiltelefon senden kann?

Jup

**Comment by joachimmarder** [comment]
> Ich benötige also eine dedizierte Telefonnummer für den Client, korrekt?

Ich habe es mit "request-sms" und "request-voice" mit meiner Festnnetznummer ausprobiert (die Telekom ist so freundlich dorthin versendete SMS am Telefon vorzulesen, zuvor getestet). Leider kam kein Registrierungscode an, trotz einer positiven Bestätigung: "Signal client: registration code requested via sms."

Hat das jemand mit einer Festnetznummer zum Laufen gebracht?

**Comment by IT-VBFK** [comment]
Seit kurzen funktioniert das Captcha. Das Problem besteht nach dem Lösen: man wird mittels signalcaptchas://CODE weitergeleitet, ohne Möglichkeit, den Code zu kopieren.

Abhilfe: t1p.de/b7tv

**Comment by joachimmarder** [comment]
Bei mir unter Windows klappte das Captcha nicht im Firefox, wohl aber im Edge Chromium. Manchmal bleibt es dennoch bei der Fehlermeldung "402 Payment Required" beim Anfordern der SMS. Selbst bei einem Success kommt aber einfach keine SMS an.
