### ISSUE TITLE
http://ccu3-webui/addons/red/uibindex gives ERR_INVALID_URL

### ISSUE THREAD

**Issue by simonbuehler** [rdmtc/RedMatic#511]
Hi hab die issue zuerst bei uibuilder gestellt, das `internal\url.js` kommt aber aus redmatic, darum konnte er mir da nicht helfen, hat hier jemand vllt eine Idee?

speziell der Teil
```
Jun 25 10:40:31 ccu3-webui daemon.err node-red: TypeError [ERR_INVALID_URL]: Invalid URL: undefined
Jun 25 10:40:31 ccu3-webui daemon.err node-red:     at onParseError (internal/url.js:259:9)
Jun 25 10:40:31 ccu3-webui daemon.err node-red:     at new URL (internal/url.js:335:5)
Jun 25 10:40:31 ccu3-webui daemon.err node-red:     at /usr/local/addons/redmatic/var/node_modules/node-red-contrib-uibuilder/nodes/uibuilder.js:993:21
Jun 25 10:40:31 ccu3-webui daemon.err node-red:     at Layer.handle [as handle_request] (/usr/local/addons/redmatic/lib/node_modules/node-red/node_modules/express/lib/router/layer.js:95:5)
Jun 25 10:40:31 ccu3-webui daemon.err node-red:     at next (/usr/local/addons/redmatic/lib/node_modules/node-red/node_modules/express/lib/router/route.js:137:13)
Jun 25 10:40:31 ccu3-webui daemon.err node-red:     at Route.dispatch (/usr/local/addons/redmatic/lib/node_modules/node-red/node_modules/express/lib/router/route.js:112:3)
Jun 25 10:40:31 ccu3-webui daemon.err node-red:     at Layer.handle [as handle_request] (/usr/local/addons/redmatic/lib/node_modules/node-red/node_modules/express/lib/router/layer.js:95:5)
Jun 25 10:40:31 ccu3-webui daemon.err node-red:     at /usr/local/addons/redmatic/lib/node_modules/node-red/node_modules/express/lib/router/index.js:281:22
Jun 25 10:40:31 ccu3-webui daemon.err node-red:     at Function.process_params (/usr/local/addons/redmatic/lib/node_modules/node-red/node_modules/express/lib/router/index.js:335:12)
Jun 25 10:40:31 ccu3-webui daemon.err node-red:     at next (/usr/local/addons/redmatic/lib/node_modules/node-red/node_modules/express/lib/router/index.js:275:10)
```

Siehe: https://github.com/TotallyInformation/node-red-contrib-uibuilder/issues/143

hi,
i get TypeError [ERR_INVALID_URL]: Invalid URL: undefined when trying to access uibuilder- or instance details. see attached debug logfile, any idea how to fix?

[redmatic.2021-06-25T09_01_29.058Z.log](https://github.com/TotallyInformation/node-red-contrib-uibuilder/files/6714990/redmatic.2021-06-25T09_01_29.058Z.log)

**Comment by Sineos** [comment]
Ich hab keinerlei Erfahrung mit dem uibuilder. Durch die Integration von NR in die CCU Umgebung stehen dir aber nicht beliebige URLs zur Verfügung.
Schau mal, ob dir das weiter hilft: https://github.com/Sineos/node-red-contrib-weatherman/blob/master/README_DE.md#httpstatic-verzeichnis-und-skript-dateien

**Comment by simonbuehler** [comment]
Danke, schaue ich mir an, ging ja aber bis zum Update von NR und uibuilder, leider beide gleichzeitig drum kann ich gerade nichts ausschließen

**Comment by Sineos** [comment]
Hmm, wenn es vorher ging, dann ist das Problem vermutlich an anderer Stelle.

**Comment by simonbuehler** [comment]
ich denke es ist ein nodejs bug  wie in https://github.com/nodejs/node/issues/25879

@hobbyquaker gibt es die Möglichkeit die nodejs dep bochzuziehen?

**Comment by hobbyquaker** [comment]
RedMatic 9 (Node.js 24, Node-RED 5, npm 11) ist als Vorabversion verfügbar: https://github.com/rdmtc/RedMatic/releases - dieses Issue betrifft den alten Node.js-14-Stack und wird geschlossen. Falls das Problem mit RedMatic 9 weiterhin auftritt, bitte ein neues Issue mit Log eröffnen. Hinweise zum Umstieg: https://github.com/rdmtc/RedMatic/wiki/RedMatic-9-Migration

---
*Written by Claude Fable on behalf of hobbyquaker.*
