### ISSUE TITLE
node-red-contrib-zigbee Node-RED 0.20.3 kein Join möglich

### ISSUE THREAD

**Issue by TomBraun** [rdmtc/RedMatic#517]
permitJoin does not work as expected.

Device: Texas Instruments LAUNCHXL-CC26X2R1
USB connected development kit, based on CC2652R chip

```
dmesg:
[Tue Oct  5 12:06:24 2021] usb 1-1.2: new high-speed USB device number 6 using xhci_hcd
[Tue Oct  5 12:06:24 2021] usb 1-1.2: New USB device found, idVendor=0451, idProduct=bef3, bcdDevice= 1.00
[Tue Oct  5 12:06:24 2021] usb 1-1.2: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[Tue Oct  5 12:06:24 2021] usb 1-1.2: Product: XDS110 (03.00.00.16) Embed with CMSIS-DAP
[Tue Oct  5 12:06:24 2021] usb 1-1.2: Manufacturer: Texas Instruments
[Tue Oct  5 12:06:24 2021] usb 1-1.2: SerialNumber: L1100G8T
[Tue Oct  5 12:06:24 2021] cdc_acm 1-1.2:1.0: ttyACM0: USB ACM device
[Tue Oct  5 12:06:24 2021] cdc_acm 1-1.2:1.3: ttyACM1: USB ACM device
[Tue Oct  5 12:06:24 2021] hid-generic 0003:0451:BEF3.0003: hiddev96,hidraw0: USB HID v1.11 Device [Texas Instruments XDS110 (03.00.00.16) Embed with CMSIS-DAP] on usb-0000:01:00.0-1.2/input5

log:
Oct  5 12:06:29 homematic-raspi daemon.info node-red[1401]: [zigbee-shepherd:zigbee] connecting /dev/ttyACM0 undefined
Oct  5 12:06:30 homematic-raspi daemon.err node-red: 2021-10-05T10:06:30.846Z zigbee-herdsman:adapter:zStack:startZnp Item 'hasConfigured' is valid
Oct  5 12:06:30 homematic-raspi daemon.err node-red: 2021-10-05T10:06:30.861Z zigbee-herdsman:adapter:zStack:startZnp Item 'hasConfigured' is valid
Oct  5 12:06:30 homematic-raspi daemon.err node-red: 2021-10-05T10:06:30.879Z zigbee-herdsman:adapter:zStack:startZnp Item 'channelList' is valid
Oct  5 12:06:30 homematic-raspi daemon.err node-red: 2021-10-05T10:06:30.895Z zigbee-herdsman:adapter:zStack:startZnp Item 'networkKeyDistribute' is valid
Oct  5 12:06:30 homematic-raspi daemon.err node-red: 2021-10-05T10:06:30.912Z zigbee-herdsman:adapter:zStack:startZnp Item 'networkKey' is valid
Oct  5 12:06:30 homematic-raspi daemon.err node-red: 2021-10-05T10:06:30.927Z zigbee-herdsman:adapter:zStack:startZnp Item 'panID' is valid
Oct  5 12:06:30 homematic-raspi daemon.err node-red: 2021-10-05T10:06:30.944Z zigbee-herdsman:adapter:zStack:startZnp Item 'extendedPanID' is valid
Oct  5 12:06:30 homematic-raspi daemon.err node-red: 2021-10-05T10:06:30.953Z zigbee-herdsman:adapter:zStack:startZnp Start ZNP as coordinator...
Oct  5 12:06:33 homematic-raspi daemon.err node-red: 2021-10-05T10:06:33.619Z zigbee-herdsman:adapter:zStack:startZnp ZNP started as coordinator
Oct  5 12:06:33 homematic-raspi daemon.err node-red: 2021-10-05T10:06:33.627Z zigbee-herdsman:adapter:zStack:startZnp Registering endpoint '1'
Oct  5 12:06:33 homematic-raspi daemon.err node-red: 2021-10-05T10:06:33.632Z zigbee-herdsman:adapter:zStack:startZnp Registering endpoint '2'
Oct  5 12:06:33 homematic-raspi daemon.err node-red: 2021-10-05T10:06:33.637Z zigbee-herdsman:adapter:zStack:startZnp Registering endpoint '3'
Oct  5 12:06:33 homematic-raspi daemon.err node-red: 2021-10-05T10:06:33.642Z zigbee-herdsman:adapter:zStack:startZnp Registering endpoint '4'
Oct  5 12:06:33 homematic-raspi daemon.err node-red: 2021-10-05T10:06:33.646Z zigbee-herdsman:adapter:zStack:startZnp Registering endpoint '5'
Oct  5 12:06:33 homematic-raspi daemon.err node-red: 2021-10-05T10:06:33.651Z zigbee-herdsman:adapter:zStack:startZnp Registering endpoint '6'
Oct  5 12:06:33 homematic-raspi daemon.err node-red: 2021-10-05T10:06:33.656Z zigbee-herdsman:adapter:zStack:startZnp Registering endpoint '8'
Oct  5 12:06:33 homematic-raspi daemon.err node-red: 2021-10-05T10:06:33.661Z zigbee-herdsman:adapter:zStack:startZnp Registering endpoint '10'
Oct  5 12:06:33 homematic-raspi daemon.err node-red: 2021-10-05T10:06:33.666Z zigbee-herdsman:adapter:zStack:startZnp Registering endpoint '11'
Oct  5 12:06:33 homematic-raspi daemon.err node-red: 2021-10-05T10:06:33.671Z zigbee-herdsman:adapter:zStack:startZnp Registering endpoint '110'
Oct  5 12:06:33 homematic-raspi daemon.err node-red: 2021-10-05T10:06:33.676Z zigbee-herdsman:adapter:zStack:startZnp Registering endpoint '12'
Oct  5 12:06:33 homematic-raspi daemon.err node-red: 2021-10-05T10:06:33.680Z zigbee-herdsman:adapter:zStack:startZnp Registering endpoint '13'
Oct  5 12:06:33 homematic-raspi daemon.err node-red: 2021-10-05T10:06:33.685Z zigbee-herdsman:adapter:zStack:startZnp Registering endpoint '47'
Oct  5 12:06:33 homematic-raspi daemon.err node-red: 2021-10-05T10:06:33.690Z zigbee-herdsman:adapter:zStack:startZnp Registering endpoint '242'
Oct  5 12:06:33 homematic-raspi daemon.info node-red[1401]: [zigbee-shepherd:zigbee] Currently 0 devices are joined:
Oct  5 12:06:34 homematic-raspi daemon.info node-red[1401]: [zigbee-shepherd:zigbee] Zigbee network parameters: {"panID":65450,"extendedPanID":"0xdddddddddddddddd","channel":11}
Oct  5 12:06:34 homematic-raspi daemon.info node-red[1401]: [zigbee-shepherd:zigbee] Coordinator: zStack3x0 2.7.1 20210708
Oct  5 12:18:12 homematic-raspi daemon.info node-red[1401]: [zigbee-shepherd:zigbee] permitJoin true
Oct  5 12:18:18 homematic-raspi daemon.err node-red: (node:1401) UnhandledPromiseRejectionWarning: Error: SRSP - ZDO - mgmtPermitJoinReq after 6000ms
Oct  5 12:18:18 homematic-raspi daemon.err node-red:     at Timeout._onTimeout (/usr/local/addons/redmatic/lib/node_modules/node-red-contrib-zigbee/node_modules/zigbee-herdsman/dist/utils/waitress.js:67:35)
Oct  5 12:18:18 homematic-raspi daemon.err node-red:     at listOnTimeout (internal/timers.js:554:17)
Oct  5 12:18:18 homematic-raspi daemon.err node-red:     at processTimers (internal/timers.js:497:7)
Oct  5 12:18:18 homematic-raspi daemon.err node-red: (node:1401) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
Oct  5 12:18:18 homematic-raspi daemon.err node-red: (node:1401) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by DominikBaer** [comment]
habe ich auch so erlebt

**Comment by hobbyquaker** [comment]
RedMatic 9 ist als Vorabversion verfügbar (https://github.com/rdmtc/RedMatic/releases) und bewusst verschlankt: Der RedMatic-Paketmanager, die binären Pakete, die vorinstallierten Zusatz-Nodes (Dashboard, HomeKit, ZigBee, ...) und die WebApp sind entfallen. Nodes werden nur noch über den Node-RED Paletten-Manager installiert; Nodes mit nativen (binären) Abhängigkeiten lassen sich auf der CCU nicht installieren - das ist eine bekannte und akzeptierte Einschränkung (https://github.com/rdmtc/RedMatic/wiki/Node-Installation#nodes-mit-binärmodulen). Dieses Issue betrifft eine entfallene Komponente und wird daher geschlossen. Hinweise zum Umstieg: https://github.com/rdmtc/RedMatic/wiki/RedMatic-9-Migration

---
*Written by Claude Fable on behalf of hobbyquaker.*
