### ISSUE TITLE
Nach einiger Zeit gibt es plötzlich Probleme

### ISSUE THREAD

**Issue by UserRG** [rdmtc/RedMatic#520]
Hallo,
ich habe das Problem, dass sich nach einiger Zeit die Fehler häufen. Es gibt Neustarts und ich habe das Gefühl, dass manche Dinge nicht mehr korrekt laufen. z.B. erhalte ich Meldungen wie "    < BidCos-Wired setValue Error: XML-RPC fault: Failure" etc. Neulich las ich 28 Neustarts seit dem letzten Node-Red-Start. Ich habe zwar immer mal wieder etwas verändert. Vor allem habe ich die Prozesse schlanker gemacht. Habe quasi die "umständliche" Flowgestaltung aus meinen Anfangszeiten verbessert. 
Gibt es ein Speicherproblem etc.? Ich weiß mir leider keinen Rat. Es sind auch immer wieder andere Konfig-Nodes wie z.B. Alexa betroffen und stehen in den Logs. Aber eigentlich tut Alexa was sie soll...
Ich habe bisher NodeRed immer neu installiert und musste dann eben alle Konfig-Nodes etc. nochmal anpassen. Das hat immer geholfen, aber kann ja eigentlich keine Dauerlösung sein.
Die flow-Variablen etc. speichere ich alle auf einem USB-Stick an der CCU3. Der hatte sich allerdings auch schonmal verabschiedet, Konnte selbst mit dem PC nichts mehr öffnen. Ob das an zuvielen Zugriffen liegt, kann ich nicht beurteilen.
Kann mal jemand über das Log schauen, vielleicht erkennt ihr was!? Danke.
[redmatic.2021-10-24T12 43 23.263Z.log.txt](https://github.com/rdmtc/RedMatic/files/7404665/redmatic.2021-10-24T12.43.23.263Z.log.txt)

**Comment by djiwondee** [comment]
Hallo @UserRG, 
> Kann es sein, dass ein paar interne Files auf der Platte defekt sind? D.h. Werksreset und komplett neu aufspielen?

Wenn das wirklich der Fall ist, dann würde ich überlegen, die CCU auszutauschen. Da scheint mir dann dort eher ein Hardware-Problem vorzuliegen.

 > Fehler im Node-Red-CCU-Modul

Bitte insb. aufpassen, wenn Du Nodes aktualisierst. Bitte nicht einfach _Update_ drücken, sondern unbedingt vorher prüfen, ob die aktualisierbaren Nodes auch mit dem _Release-Stand von node-red in Redmatic_ laufen. Latest Release von Node-red ist.

**Comment by UserRG** [comment]
Was mir noch aufgefallen ist: Die Fehler verschwinden... d.h. es scheint so, als wenn die CCU "zu langsam" ist, die Informationen zu liefern... Nach einigen Minuten, aktualisieren sich die Systemvariablen auch wieder und werden auch gefunden. Nur die inject-Nodes, die nach dem Neustart losrennen laufen auf Fehler, da die Systemvariablen nicht bekannt sind etc. Ich merke die Verzögerung auch an manchen Befehlen...
Ich werde nochmal den BUS-Traffic loggen, evtl. gibts da ein defektes Gerät.
Sonst muss ich wohl wirklich mal einen Werksreset machen. Backup habe ich genug... Sieht aktuell jedenfalls nach einem Problem auf der CCU3 aus... Evtl. wirklich ein paar defekte Dateien

**Comment by djiwondee** [comment]
@UserRG 
> es scheint so, als wenn die CCU "zu langsam" ist

ha! Guter Punkt. Das erlebe ich auch hin und wieder. Letzte Woche z. B. war die CCU mit Firmwareupdates meiner zahlreichen HmIP-BSM's beschäftigt. Gut möglich, dass hier der ein oder andere Timeout zuschlägt.

**Comment by UserRG** [comment]
Hallo Zusammen,
ich habe inzwischen das Bus-Protokoll von einem Profi bei HausBus.de prüfen lassen. Sie sagen keine Auffälligkeiten.
Ich habe inzwischen ein Werksreset gemacht und das Backup neu eingespielt. Problem ist leider noch immer da. Ich habe auch die Haus-Bus Aktoren (weil Systemfremd) mal gelöscht und geschaut was passiert... Aber Problem bleibt. Es gibt jede Menge Fehlermeldungen und dann stabilisiert sich das System irgendwann. 

Ich musste nach dem Werksreset auch NodeRed wieder neu installieren (Version 7.2.1). Trotzdem erhalte ich beim Deployen (Voll oder Flows der geänderten Nodes) folgende Fehlermeldung:

Error: xml in rega response missing
    at Rega._parseResponse (/usr/local/addons/redmatic/var/node_modules/node-red-contrib-ccu/node_modules/homematic-rega/index.js:60:35)
    at Request._callback (/usr/local/addons/redmatic/var/node_modules/node-red-contrib-ccu/node_modules/homematic-rega/index.js:111:26)
    at Request.self.callback (/usr/local/addons/redmatic/var/node_modules/node-red-contrib-ccu/node_modules/request/request.js:185:22)
    at Request.emit (events.js:315:20)
    at Request.<anonymous> (/usr/local/addons/redmatic/var/node_modules/node-red-contrib-ccu/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:315:20)
    at IncomingMessage.<anonymous> (/usr/local/addons/redmatic/var/node_modules/node-red-contrib-ccu/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:421:28)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (internal/streams/readable.js:1327:12)
    at processTicksAndRejections (internal/process...

Da passt doch was nicht mit der Node-Red installation. Diese ist aber wie gesagt "nagelneu"... Jemand eine Idee? Ich bin langsam am Ende...

**Comment by UserRG** [comment]
Hallo Zusammen,
ich habe mir jetzt mal die Mühe gemacht und meine ganze Homatic-Installation neu aufzusetzen... Nach ca 20 (!) Stunden hatte ich alles wieder am Laufen - noch ohne Redmatic. Nachdem ich auch Redmatic installiert hatte, kamen die Fehlermeldungen allerdings wieder... Es sieht so aus, als wenn beim Deploy aller Flows die Daten nicht zeitgerecht an Redmatic übermittelt werden. Evtl. habe ich aber noch eine Idee, da ich auch die Homematic-Scripte auf Redmatic laufen lasse, immer dann, wenn sich ein bestimmtes Gewerk (Licht / Fenster) ändert. Ich habe die Befürchtung, dass nach dem Deploy alle Aktoren ihren Status neu melden und daher die Scripte zig mal laufen, die wiederum ja auch alle Stati aller Geräte abfragen. Und das sind bei mir schon ein paar Kanäle... Kann man das irgendwie abfangen? So ähnlich wie beim CCU-Neustart durch eine Variable? (Was leider durch die verspätete Übermittlung der Daten im Moment auch nicht funktioniert). Wenn sich der Datenstau aufgelöst hat, scheint auch alles wieder normal zu funktionieren. Auch alle Variablen sind plötzlich wieder vorhanden. Ergo nur ein Zeitproblem? Startet Redmatic für große Installationen zu früh? Kann ich das selbst hinauszögern?

**Comment by Sineos** [comment]
Schwer zu sagen. Die Redmatic Benutzer, die ich kenne, haben ihre gesamte Logik in die Redmatic verlagert und verzichten auf Scripte. 
Scheint hier auch zu komischem Verhalten kommen zu können: https://github.com/jens-maus/RaspberryMatic/issues/1583

**Comment by hobbyquaker** [comment]
RedMatic 9 (Node.js 24, Node-RED 5, npm 11) ist als Vorabversion verfügbar: https://github.com/rdmtc/RedMatic/releases - dieses Issue betrifft den alten Node.js-14-Stack und wird geschlossen. Falls das Problem mit RedMatic 9 weiterhin auftritt, bitte ein neues Issue mit Log eröffnen. Hinweise zum Umstieg: https://github.com/rdmtc/RedMatic/wiki/RedMatic-9-Migration

---
*Written by Claude Fable on behalf of hobbyquaker.*
