### ISSUE TITLE
Node-RED exited with non-zero exit status 1

### ISSUE THREAD

**Issue by Matten-Matten** [rdmtc/RedMatic#541]
Sporadische Neustarts von Redmatic.
folgendes steht im Log:
```
Mar 21 18:36:18 ccu3-webui daemon.err node-red: ERROR: undefined
Mar 21 18:36:18 ccu3-webui daemon.err node-red: 21 Mar 18:36:18 - [red] Uncaught Exception:
Mar 21 18:36:18 ccu3-webui daemon.err node-red: 21 Mar 18:36:18 - TypeError: Cannot read property 'toString' of undefined
Mar 21 18:36:18 ccu3-webui daemon.err node-red:     at /usr/local/addons/redmatic/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/flows/Flow.js:443:62
Mar 21 18:36:18 ccu3-webui daemon.err node-red:     at Array.forEach (<anonymous>)
Mar 21 18:36:18 ccu3-webui daemon.err node-red:     at Flow.handleStatus (/usr/local/addons/redmatic/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/flows/Flow.js:435:30)
Mar 21 18:36:18 ccu3-webui daemon.err node-red:     at UnifiNode.Node.status (/usr/local/addons/redmatic/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/nodes/Node.js:575:16)
Mar 21 18:36:18 ccu3-webui daemon.err node-red:     at handleDataCallback (/usr/local/addons/redmatic/var/node_modules/node-red-contrib-unifi/unifi.js:183:26)
Mar 21 18:36:18 ccu3-webui daemon.err node-red:     at /usr/local/addons/redmatic/var/node_modules/node-red-contrib-unifi/unifi-helper.js:1564:25
Mar 21 18:36:18 ccu3-webui daemon.err node-red:     at /usr/local/addons/redmatic/var/node_modules/node-red-contrib-unifi/node_modules/async/dist/async.js:327:20
Mar 21 18:36:18 ccu3-webui daemon.err node-red:     at next (/usr/local/addons/redmatic/var/node_modules/node-red-contrib-unifi/node_modules/async/dist/async.js:5661:29)
Mar 21 18:36:18 ccu3-webui daemon.err node-red:     at Request._callback (/usr/local/addons/redmatic/var/node_modules/node-red-contrib-unifi/unifi-helper.js:1549:25)
Mar 21 18:36:18 ccu3-webui daemon.err node-red:     at Request.self.callback (/usr/local/addons/redmatic/var/node_modules/node-red-contrib-unifi/node_modules/request/request.js:185:22)
Mar 21 18:36:18 ccu3-webui daemon.err node-red:     at Request.emit (events.js:315:20)
Mar 21 18:36:18 ccu3-webui daemon.err node-red:     at Request.<anonymous> (/usr/local/addons/redmatic/var/node_modules/node-red-contrib-unifi/node_modules/request/request.js:1154:10)
Mar 21 18:36:18 ccu3-webui daemon.err node-red:     at Request.emit (events.js:315:20)
Mar 21 18:36:18 ccu3-webui daemon.err node-red:     at IncomingMessage.<anonymous> (/usr/local/addons/redmatic/var/node_modules/node-red-contrib-unifi/node_modules/request/request.js:1076:12)
Mar 21 18:36:18 ccu3-webui daemon.err node-red:     at Object.onceWrapper (events.js:421:28)
Mar 21 18:36:18 ccu3-webui daemon.err node-red:     at IncomingMessage.emit (events.js:327:22)
Mar 21 18:36:18 ccu3-webui daemon.err node-red:     at endReadableNT (_stream_readable.js:1327:12)
Mar 21 18:36:18 ccu3-webui daemon.err node-red:     at processTicksAndRejections (internal/process/task_queues.js:80:21)
Mar 21 18:36:19 ccu3-webui daemon.err node-red: Node-RED exited with non-zero exit status 1
```

Gruß
Matten Matten

**Comment by ptweety** [comment]
Das scheint ein Problem von `node-red-contrib-unifi`zu sein. Du solltest besser im dortigen GitHub einen Issue erstellen.

**Comment by hobbyquaker** [comment]
RedMatic 9 (Node.js 24, Node-RED 5, npm 11) ist als Vorabversion verfügbar: https://github.com/rdmtc/RedMatic/releases - dieses Issue betrifft den alten Node.js-14-Stack und wird geschlossen. Falls das Problem mit RedMatic 9 weiterhin auftritt, bitte ein neues Issue mit Log eröffnen. Hinweise zum Umstieg: https://github.com/rdmtc/RedMatic/wiki/RedMatic-9-Migration

---
*Written by Claude Fable on behalf of hobbyquaker.*
