### ISSUE TITLE
node-red-contrib-dahua-device

### ISSUE THREAD

**Issue by Pezi1978** [rdmtc/RedMatic#551]
Hallo,

kann dieses Paket bitte in die Liste mit aufgenommen werden?
Oder gibt es eine alternative Lösung??

DANKE

2022-07-15T05:48:32.510Z installieren : node-red-contrib-dahua-device 0.0.2

2022-07-15T05:48:32.555Z npm install --no-package-lock --global-style --no-audit --no-update-notifier --no-fund --save --save-prefix=~ --production node-red-contrib-dahua-device@0.0.2
2022-07-15T05:49:02.889Z [err] npm
2022-07-15T05:49:02.890Z [err]  WARN deprecated har-validator@5.1.5: this library is no longer supported
2022-07-15T05:49:03.346Z [err] npm
2022-07-15T05:49:03.347Z [err]  WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
2022-07-15T05:49:03.487Z [err] npm
2022-07-15T05:49:03.488Z [err]  
2022-07-15T05:49:03.489Z [err] WARN
2022-07-15T05:49:03.489Z [err]  
2022-07-15T05:49:03.490Z [err] deprecated
2022-07-15T05:49:03.490Z [err]  request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
2022-07-15T05:49:09.287Z [err] npm
2022-07-15T05:49:09.288Z [err]  ERR! code 1
2022-07-15T05:49:09.288Z [err] npm ERR! path /usr/local/addons/redmatic/var/node_modules/node-red-contrib-dahua-device/node_modules/ffi-napi
2022-07-15T05:49:09.302Z [err] npm ERR! command failed
2022-07-15T05:49:09.302Z [err] npm ERR!
2022-07-15T05:49:09.303Z [err]  command sh -c node-gyp-build
2022-07-15T05:49:09.303Z [err] npm ERR! gyp info it worked if it ends with ok
2022-07-15T05:49:09.303Z [err] npm ERR!
2022-07-15T05:49:09.303Z [err]  gyp info using node-gyp@7.1.2
2022-07-15T05:49:09.303Z [err] npm ERR! gyp info using node@14.16.0 | linux | arm64
2022-07-15T05:49:09.303Z [err] npm ERR! gyp ERR! find Python 
2022-07-15T05:49:09.303Z [err] npm ERR! gyp ERR! find Python Python is not set from command line or npm configuration
2022-07-15T05:49:09.303Z [err] npm ERR!
2022-07-15T05:49:09.304Z [err]  gyp ERR! find Python Python is not set from environment variable PYTHON
2022-07-15T05:49:09.304Z [err] npm ERR! gyp ERR! find Python checking if "python3" can be used
2022-07-15T05:49:09.304Z [err] npm ERR!
2022-07-15T05:49:09.304Z [err]  gyp ERR! find Python - "python3" is not in PATH or produced an error
2022-07-15T05:49:09.304Z [err] npm ERR! gyp ERR! find Python checking if "python" can be used
2022-07-15T05:49:09.304Z [err] npm
2022-07-15T05:49:09.304Z [err]  ERR! gyp ERR! find Python - "python" is not in PATH or produced an error
2022-07-15T05:49:09.304Z [err] npm 
2022-07-15T05:49:09.305Z [err] ERR! gyp ERR! find Python checking if "python2" can be used
2022-07-15T05:49:09.305Z [err] npm ERR!
2022-07-15T05:49:09.305Z [err]  gyp ERR! find Python - "python2" is not in PATH or produced an error
2022-07-15T05:49:09.305Z [err] npm ERR!
2022-07-15T05:49:09.305Z [err]  gyp ERR! find Python 
2022-07-15T05:49:09.305Z [err] npm ERR! gyp ERR! find Python **********************************************************
2022-07-15T05:49:09.305Z [err] npm ERR! gyp ERR! find Python You need to install the latest version of Python.
2022-07-15T05:49:09.305Z [err] npm 
2022-07-15T05:49:09.306Z [err] ERR!
2022-07-15T05:49:09.306Z [err]  gyp ERR! find Python Node-gyp should be able to find and use Python. If not,
2022-07-15T05:49:09.306Z [err] npm ERR!
2022-07-15T05:49:09.306Z [err]  gyp ERR! find Python you can try one of the following options:
2022-07-15T05:49:09.306Z [err] npm ERR!
2022-07-15T05:49:09.306Z [err]  gyp ERR! find Python - Use the switch --python="/path/to/pythonexecutable"
2022-07-15T05:49:09.306Z [err] npm ERR! gyp ERR! find Python   (accepted by both node-gyp and npm)
2022-07-15T05:49:09.306Z [err] npm
2022-07-15T05:49:09.307Z [err]  ERR! gyp ERR! find Python - Set the environment variable PYTHON
2022-07-15T05:49:09.307Z [err] npm 
2022-07-15T05:49:09.307Z [err] ERR! gyp ERR! find Python - Set the npm configuration variable python:
2022-07-15T05:49:09.307Z [err] npm ERR!
2022-07-15T05:49:09.307Z [err]  gyp ERR! find Python   npm config set python "/path/to/pythonexecutable"
2022-07-15T05:49:09.307Z [err] npm ERR!
2022-07-15T05:49:09.307Z [err]  gyp ERR! find Python For more information consult the documentation at:
2022-07-15T05:49:09.307Z [err] npm ERR! gyp ERR! find Python https://github.com/nodejs/node-gyp#installation
2022-07-15T05:49:09.308Z [err] npm ERR! gyp ERR! find Python **********************************************************
2022-07-15T05:49:09.308Z [err] npm
2022-07-15T05:49:09.308Z [err]  ERR! gyp ERR! find Python 
2022-07-15T05:49:09.308Z [err] npm ERR!
2022-07-15T05:49:09.308Z [err]  gyp ERR! configure error 
2022-07-15T05:49:09.308Z [err] npm ERR!
2022-07-15T05:49:09.308Z [err]  gyp ERR! stack Error: Could not find any Python installation to use
2022-07-15T05:49:09.308Z [err] npm ERR! gyp ERR! stack     at PythonFinder.fail (/usr/local/addons/redmatic/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:302:47)
2022-07-15T05:49:09.309Z [err] npm ERR! gyp ERR! stack     at PythonFinder.runChecks (/usr/local/addons/redmatic/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:136:21)
2022-07-15T05:49:09.309Z [err] npm ERR!
2022-07-15T05:49:09.309Z [err]  gyp ERR! stack     at PythonFinder.<anonymous> (/usr/local/addons/redmatic/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:179:16)
2022-07-15T05:49:09.309Z [err] npm ERR!
2022-07-15T05:49:09.309Z [err]  gyp ERR! stack     at PythonFinder.execFileCallback (/usr/local/addons/redmatic/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:266:16)
2022-07-15T05:49:09.309Z [err] npm ERR! gyp ERR! stack     at exithandler (child_process.js:315:5)
2022-07-15T05:49:09.309Z [err] npm ERR! gyp ERR! stack     at ChildProcess.errorhandler (child_process.js:327:5)
2022-07-15T05:49:09.309Z [err] npm
2022-07-15T05:49:09.310Z [err]  ERR! gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
2022-07-15T05:49:09.310Z [err] npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
2022-07-15T05:49:09.310Z [err] npm ERR! gyp ERR! stack     at onErrorNT (internal/child_process.js:465:16)
2022-07-15T05:49:09.310Z [err] npm 
2022-07-15T05:49:09.310Z [err] ERR! gyp ERR! stack     at processTicksAndRejections (internal/process/task_queues.js:80:21)
2022-07-15T05:49:09.310Z [err] npm ERR!
2022-07-15T05:49:09.311Z [err]  gyp ERR! System Linux 5.15.32
2022-07-15T05:49:09.311Z [err] npm ERR! gyp ERR! command "/usr/local/addons/redmatic/bin/node" "/usr/local/addons/redmatic/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
2022-07-15T05:49:09.311Z [err] npm ERR! gyp ERR! cwd /usr/local/addons/redmatic/var/node_modules/node-red-contrib-dahua-device/node_modules/ffi-napi
2022-07-15T05:49:09.311Z [err] npm
2022-07-15T05:49:09.311Z [err]  ERR! gyp ERR! node -v v14.16.0
2022-07-15T05:49:09.311Z [err] npm 
2022-07-15T05:49:09.311Z [err] ERR! gyp ERR! node-gyp -v v7.1.2
2022-07-15T05:49:09.311Z [err] npm ERR!
2022-07-15T05:49:09.311Z [err]  gyp ERR! not ok
2022-07-15T05:49:09.394Z [err] 
2022-07-15T05:49:09.396Z [err] npm ERR! A complete log of this run can be found in:
2022-07-15T05:49:09.396Z [err] npm ERR!     /usr/local/addons/redmatic/var/npm-cache/_logs/2022-07-15T05_49_09_322Z-debug.log
2022-07-15T05:49:09.550Z rc=1

**Comment by djiwondee** [comment]
Hallo @Pezi1978 

> 2022-07-15T05:49:03.347Z [err] WARN deprecated uuid@3.4.0: Please upgrade to version 7 or higher. Older versions may use Math.random() in certain circumstances, which is known to be problematic. See https://v8.dev/blog/math-random for details.

Das sieht aus, als hättest Du versucht mit `node-red-contrib-dahua-device 0.0.2`ein Paket zu installieren, das eine neuere NodeJs- und/oder andere höhere Version eines abhängigen Paketes benötigt.

Leider ist Redmatic schon länger nicht mehr auf dem neusten Stand von NodeRed. Von daher bleibt wohl leider nur die Alternative NodeRed auf ein anderes System auszulagern. Das Repo hier ist leider seit längerer Zeit sehr zum großen Bedauern vieler Nutzer verwaist.

**Comment by hobbyquaker** [comment]
RedMatic 9 (Node.js 24, Node-RED 5, npm 11) ist als Vorabversion verfügbar: https://github.com/rdmtc/RedMatic/releases - dieses Issue betrifft den alten Node.js-14-Stack und wird geschlossen. Falls das Problem mit RedMatic 9 weiterhin auftritt, bitte ein neues Issue mit Log eröffnen. Hinweise zum Umstieg: https://github.com/rdmtc/RedMatic/wiki/RedMatic-9-Migration

---
*Written by Claude Fable on behalf of hobbyquaker.*
