### ISSUE TITLE
Uncaught Exception: Error: socket -24

### ISSUE THREAD

**Issue by ggzengel** [rdmtc/RedMatic#580]
I use RedMatic for writing events to influxdb.
After a view hours the services stops with an uncaught exception.

[redmatic.2023-09-22T16 53 55.634Z.log](https://github.com/rdmtc/RedMatic/files/12709953/redmatic.2023-09-22T16.53.55.634Z.log)

```
Sep 22 18:26:31 lx-homematic daemon.err node-red: 22 Sep 18:26:31 - [red] Uncaught Exception:
Sep 22 18:26:31 lx-homematic daemon.err node-red: 22 Sep 18:26:31 - Error: socket -24
Sep 22 18:26:31 lx-homematic daemon.err node-red:     at errnoException (/usr/local/addons/redmatic/lib/node_modules/ain2/node_modules/unix-dgram/lib/unix_dgram.js:23:11)
Sep 22 18:26:31 lx-homematic daemon.err node-red:     at new Socket (/usr/local/addons/redmatic/lib/node_modules/ain2/node_modules/unix-dgram/lib/unix_dgram.js:65:11)
Sep 22 18:26:31 lx-homematic daemon.err node-red:     at Object.exports.createSocket (/usr/local/addons/redmatic/lib/node_modules/ain2/node_modules/unix-dgram/lib/unix_dgram.js:55:10)
Sep 22 18:26:31 lx-homematic daemon.err node-red:     at getSocket (/usr/local/addons/redmatic/lib/node_modules/ain2/index.js:52:24)
Sep 22 18:26:31 lx-homematic daemon.err node-red:     at SysLogger.unix_dgram [as transport] (/usr/local/addons/redmatic/lib/node_modules/ain2/index.js:131:22)
Sep 22 18:26:31 lx-homematic daemon.err node-red:     at SysLogger._send (/usr/local/addons/redmatic/lib/node_modules/ain2/index.js:338:10)
Sep 22 18:26:31 lx-homematic daemon.err node-red:     at SysLogger.send (/usr/local/addons/redmatic/lib/node_modules/ain2/index.js:350:10)
Sep 22 18:26:31 lx-homematic daemon.err node-red:     at /usr/local/addons/redmatic/lib/logger.js:36:37
Sep 22 18:26:31 lx-homematic daemon.err node-red:     at Array.forEach (<anonymous>)
Sep 22 18:26:31 lx-homematic daemon.err node-red:     at LogHandler.handler (/usr/local/addons/redmatic/lib/logger.js:33:31)
Sep 22 18:26:31 lx-homematic user.err monit[1870]: 'redmatic-nodered' failed protocol test [HTTP] at [localhost]:1880/addons/red/ [TCP/IP] -- HTTP: Error receiving data -- Connection reset by peer
Sep 22 18:26:31 lx-homematic daemon.err node-red: Node-RED exited with non-zero exit status 1
```

**Comment by hobbyquaker** [comment]
RedMatic 9 (Node.js 24, Node-RED 5, npm 11) ist als Vorabversion verfügbar: https://github.com/rdmtc/RedMatic/releases - dieses Issue betrifft den alten Node.js-14-Stack und wird geschlossen. Falls das Problem mit RedMatic 9 weiterhin auftritt, bitte ein neues Issue mit Log eröffnen. Hinweise zum Umstieg: https://github.com/rdmtc/RedMatic/wiki/RedMatic-9-Migration

---
*Written by Claude Fable on behalf of hobbyquaker.*
